#!/usr/bin/env python3
"""MHHS2402 W5 · Anatomy of the Heart & Blood Vessels — regenerated bank (length-matched, no bracket tells, no daredevil)."""
import os, sys, json
HERE = os.path.dirname(os.path.abspath(__file__))
sys.path.insert(0, os.path.join(HERE, "..", "tools"))
from qbank_lib import emit  # noqa

KEY = "cardiovascular_anatomy_mhhs2402_wk5.html"
BANK = json.load(open(os.path.join(HERE, "..", "..", "guide_quizzes.json"), encoding="utf-8"))
META = {k: BANK[KEY][k] for k in ("title", "subject", "unit", "content")}

Q = [
 # ── easy ──────────────────────────────────────────────────────────────
 {"topic": "Sternal angle", "difficulty": "easy",
  "question": "The sternal angle (angle of Louis) marks which vertebral level?",
  "options": ["A. T4", "B. T1",
              "C. T8", "D. L1"],
  "correct_answer": "A",
  "explanation": "The sternal angle marks the T4/T5 plane, the master surface landmark of the thorax.",
  "related": ["Sternal angle", "Thoracic inlet"]},

 {"topic": "Mediastinum", "difficulty": "easy",
  "question": "The heart sits within which subdivision of the mediastinum?",
  "options": ["A. the middle mediastinum", "B. the anterior mediastinum",
              "C. the posterior mediastinum", "D. the superior mediastinum"],
  "correct_answer": "A",
  "explanation": "The heart, pericardium and roots of the great vessels lie in the middle mediastinum.",
  "related": ["Mediastinum", "Pericardium"]},

 {"topic": "Ventricle walls", "difficulty": "easy",
  "question": "The single best clue for identifying the left ventricle in a cut section is its:",
  "options": ["A. thick myocardium", "B. moderator band",
              "C. crista terminalis", "D. pectinate muscle"],
  "correct_answer": "A",
  "explanation": "The left ventricle has a markedly thicker, rounder myocardium, about three times the thin crescentic right ventricle.",
  "related": ["Ventricle walls", "Chambers"]},

 {"topic": "Pacemaker", "difficulty": "easy",
  "question": "The natural pacemaker of the heart is the:",
  "options": ["A. sinoatrial node", "B. atrioventricular node",
              "C. bundle of His", "D. Purkinje fibres"],
  "correct_answer": "A",
  "explanation": "The sinoatrial node in the right atrial wall sets the heart rate; its firing depolarises both atria.",
  "related": ["Pacemaker", "Conduction"]},

 {"topic": "Coronary arteries", "difficulty": "easy",
  "question": "The coronary arteries arise from the aorta just above which valve?",
  "options": ["A. the aortic valve", "B. the pulmonary valve",
              "C. the mitral valve", "D. the tricuspid valve"],
  "correct_answer": "A",
  "explanation": "The coronary arteries arise from the aortic sinuses just above the aortic valve to supply the myocardium.",
  "related": ["Coronary arteries", "Coronary vessels"]},

 # ── medium ────────────────────────────────────────────────────────────
 {"topic": "Sternal angle features", "difficulty": "medium",
  "question": "At the sternal angle, the trachea divides into two bronchi at the:",
  "options": ["A. carina", "B. hilum",
              "C. glottis", "D. larynx"],
  "correct_answer": "A",
  "explanation": "The trachea bifurcates at the carina at the sternal-angle level, where the aortic arch also begins.",
  "related": ["Sternal angle features", "Thoracic inlet"]},

 {"topic": "Pericardium", "difficulty": "medium",
  "question": "The tough outer layer of the pericardium that anchors the heart is the:",
  "options": ["A. fibrous pericardium", "B. serous pericardium",
              "C. visceral pericardium", "D. parietal pericardium"],
  "correct_answer": "A",
  "explanation": "The fibrous pericardium is dense connective tissue that anchors the heart and resists sudden overfilling.",
  "related": ["Pericardium", "Cardiac tamponade"]},

 {"topic": "Pericardial nerve", "difficulty": "medium",
  "question": "Sensory supply to the fibrous and parietal pericardium comes from the:",
  "options": ["A. phrenic nerve", "B. vagus nerve",
              "C. sympathetic trunk", "D. glossopharyngeal nerve"],
  "correct_answer": "A",
  "explanation": "The phrenic nerve (C3 to C5) is sensory to the pericardium, which underlies the referral of cardiac pain to the shoulder.",
  "related": ["Pericardial nerve", "Referred pain"]},

 {"topic": "Heart borders", "difficulty": "medium",
  "question": "The right border of the heart is formed almost entirely by the:",
  "options": ["A. right atrium", "B. right ventricle",
              "C. left atrium", "D. left ventricle"],
  "correct_answer": "A",
  "explanation": "The right border is formed almost entirely by the right atrium; the left border and apex belong to the left ventricle.",
  "related": ["Heart borders", "Surfaces"]},

 {"topic": "Left atrium", "difficulty": "medium",
  "question": "The left atrium is most reliably identified by the entry of the:",
  "options": ["A. four pulmonary veins", "B. superior vena cava",
              "C. coronary sinus", "D. inferior vena cava"],
  "correct_answer": "A",
  "explanation": "The left atrium receives the four pulmonary veins, which carry oxygenated blood, and has a mostly smooth wall.",
  "related": ["Left atrium", "Chambers"]},

 {"topic": "Right ventricle", "difficulty": "medium",
  "question": "Which muscular structure is the give-away that you are viewing the right ventricle?",
  "options": ["A. the moderator band", "B. the crista terminalis",
              "C. the fossa ovalis", "D. the coronary sinus"],
  "correct_answer": "A",
  "explanation": "The moderator band carries the right bundle branch to the anterior papillary muscle and is a right-ventricle signature.",
  "related": ["Right ventricle", "Chambers"]},

 {"topic": "Chordae tendineae", "difficulty": "medium",
  "question": "The chordae tendineae and papillary muscles function to:",
  "options": ["A. stop valve cusps everting", "B. open the atrioventricular valves",
              "C. generate the heartbeat", "D. supply the myocardium"],
  "correct_answer": "A",
  "explanation": "The chordae and papillary muscles tether the AV cusps so they cannot evert into the atrium when the ventricle contracts.",
  "related": ["Chordae tendineae", "Valves"]},

 {"topic": "Heart sounds", "difficulty": "medium",
  "question": "The first heart sound (S1, 'lub') is produced by closure of the:",
  "options": ["A. atrioventricular valves", "B. semilunar valves",
              "C. aortic valve alone", "D. pulmonary valve alone"],
  "correct_answer": "A",
  "explanation": "S1 is the closure of the atrioventricular valves; S2 ('dub') is the closure of the semilunar valves.",
  "related": ["Heart sounds", "Valves"]},

 {"topic": "Coronary branches", "difficulty": "medium",
  "question": "The left anterior descending artery is a branch of which coronary artery?",
  "options": ["A. the left coronary", "B. the right coronary",
              "C. the circumflex", "D. the right marginal"],
  "correct_answer": "A",
  "explanation": "The left coronary stem divides into the left anterior descending (LAD) and the circumflex arteries.",
  "related": ["Coronary branches", "Coronary arteries"]},

 {"topic": "Cardiac veins", "difficulty": "medium",
  "question": "Most cardiac veins drain into which structure before reaching the right atrium?",
  "options": ["A. the coronary sinus", "B. the pulmonary trunk",
              "C. the superior vena cava", "D. the aortic sinus"],
  "correct_answer": "A",
  "explanation": "The cardiac veins converge on the coronary sinus in the posterior AV groove, which empties into the right atrium.",
  "related": ["Cardiac veins", "Coronary vessels"]},

 {"topic": "Conduction pathway", "difficulty": "medium",
  "question": "After the SA node, the electrical impulse next reaches the:",
  "options": ["A. atrioventricular node", "B. bundle of His",
              "C. Purkinje fibres", "D. left bundle branch"],
  "correct_answer": "A",
  "explanation": "The impulse passes from the SA node to the AV node, where it is briefly delayed before travelling down the bundle of His.",
  "related": ["Conduction pathway", "Conduction"]},

 {"topic": "Autonomic supply", "difficulty": "medium",
  "question": "The vagus nerve affects the heart mainly by:",
  "options": ["A. slowing the rate", "B. speeding the rate",
              "C. raising contractile force", "D. dilating the coronaries"],
  "correct_answer": "A",
  "explanation": "The vagus nerve is the parasympathetic brake, slowing heart rate and AV conduction with little effect on force.",
  "related": ["Autonomic supply", "Conduction"]},

 {"topic": "Circulations", "difficulty": "medium",
  "question": "Compared with the systemic circulation, the pulmonary circulation operates at a pressure that is:",
  "options": ["A. much lower", "B. much higher",
              "C. exactly equal", "D. slightly higher"],
  "correct_answer": "A",
  "explanation": "Pulmonary pressures are about 25/10 mmHg, far lower than the systemic 120/80, matching the thin right ventricular wall.",
  "related": ["Circulations", "Ventricle walls"]},

 {"topic": "Aortic arch", "difficulty": "medium",
  "question": "The first and largest branch of the aortic arch is the:",
  "options": ["A. brachiocephalic trunk", "B. left common carotid",
              "C. left subclavian", "D. right subclavian"],
  "correct_answer": "A",
  "explanation": "The brachiocephalic trunk is the first arch branch and splits into the right common carotid and right subclavian.",
  "related": ["Aortic arch", "Great vessels"]},

 # ── hard ──────────────────────────────────────────────────────────────
 {"topic": "Crista terminalis", "difficulty": "hard",
  "question": "In the right atrium, the crista terminalis separates the pectinate wall from the smooth:",
  "options": ["A. sinus venarum", "B. coronary sinus",
              "C. fossa ovalis", "D. auricle wall"],
  "correct_answer": "A",
  "explanation": "The crista terminalis divides the smooth sinus venarum, the venous inflow region, from the rough pectinate part of the atrium.",
  "related": ["Crista terminalis", "Right atrium"]},

 {"topic": "Fibrous skeleton", "difficulty": "hard",
  "question": "Besides anchoring the valves, the cardiac fibrous skeleton acts as an:",
  "options": ["A. electrical insulator", "B. oxygen reservoir",
              "C. active pacemaker", "D. contractile layer"],
  "correct_answer": "A",
  "explanation": "The collagen rings electrically insulate the atria from the ventricles, so the AV node is the only conducting doorway.",
  "related": ["Fibrous skeleton", "Conduction"]},

 {"topic": "Semilunar valves", "difficulty": "hard",
  "question": "Semilunar valves need no chordae because their cup-shaped cusps:",
  "options": ["A. self-seal on backflow", "B. are held by muscle",
              "C. never fully close", "D. open only in diastole"],
  "correct_answer": "A",
  "explanation": "Retrograde blood fills the three pockets, which balloon together and seal, so the harder the backpush the tighter the seal.",
  "related": ["Semilunar valves", "Valves"]},

 {"topic": "Coronary dominance", "difficulty": "hard",
  "question": "Coronary dominance is defined by which vessel gives rise to the:",
  "options": ["A. posterior interventricular artery", "B. left anterior descending artery",
              "C. right marginal artery", "D. left marginal artery"],
  "correct_answer": "A",
  "explanation": "Dominance is defined by which vessel gives the posterior interventricular artery; the RCA does so in about 80 to 85 percent.",
  "related": ["Coronary dominance", "Coronary arteries"]},

 {"topic": "Coronary filling", "difficulty": "hard",
  "question": "The coronary arteries receive most of their blood flow during:",
  "options": ["A. diastole", "B. systole",
              "C. atrial contraction", "D. isovolumetric contraction"],
  "correct_answer": "A",
  "explanation": "During systole the contracting myocardium and open aortic cusps block the ostia, so coronaries fill mainly in diastole.",
  "related": ["Coronary filling", "Coronary arteries"]},

 {"topic": "Inferior MI", "difficulty": "hard",
  "question": "An inferior myocardial infarction classically causes heart block because the RCA usually supplies the:",
  "options": ["A. AV node", "B. left ventricle apex",
              "C. anterior septum", "D. pulmonary valve"],
  "correct_answer": "A",
  "explanation": "The right coronary artery usually supplies the SA and AV nodes, so an inferior MI is a classic cause of complete heart block.",
  "related": ["Inferior MI", "Conduction"]},

 {"topic": "AV delay", "difficulty": "hard",
  "question": "The roughly 0.1 second delay at the AV node exists to:",
  "options": ["A. let the ventricles fill", "B. slow the heart rate",
              "C. protect the coronaries", "D. insulate the atria"],
  "correct_answer": "A",
  "explanation": "The AV delay lets atrial contraction top up ventricular filling before the ventricles contract, maximising stroke volume.",
  "related": ["AV delay", "Conduction"]},

 {"topic": "Referred pain", "difficulty": "hard",
  "question": "Cardiac pain is referred to the left arm and jaw because heart afferents converge with somatic fibres from levels:",
  "options": ["A. T1 to T5", "B. C1 to C4",
              "C. L1 to L5", "D. S2 to S4"],
  "correct_answer": "A",
  "explanation": "The heart's sympathetic afferents (T1 to T5) share second-order neurons with somatic dermatomes, so pain is mislocated to the arm and jaw.",
  "related": ["Referred pain", "Conduction"]},

 {"topic": "Capillary types", "difficulty": "hard",
  "question": "Which capillary type has large pores and passes whole cells, as in bone marrow?",
  "options": ["A. sinusoidal", "B. continuous",
              "C. fenestrated", "D. muscular"],
  "correct_answer": "A",
  "explanation": "Sinusoidal capillaries have an incomplete basement membrane and large pores, passing whole cells in bone marrow, liver and spleen.",
  "related": ["Capillary types", "Vessel walls"]},

 {"topic": "Resistance vessels", "difficulty": "hard",
  "question": "The main controllers of peripheral resistance and blood pressure are the:",
  "options": ["A. arterioles", "B. elastic arteries",
              "C. capillaries", "D. large veins"],
  "correct_answer": "A",
  "explanation": "Arterioles have muscular walls that adjust calibre, making them the main controllers of peripheral resistance and blood pressure.",
  "related": ["Resistance vessels", "Vessel walls"]},

 {"topic": "Foetal shunts", "difficulty": "hard",
  "question": "The ductus arteriosus in the foetus connects the pulmonary trunk to the:",
  "options": ["A. aorta", "B. inferior vena cava",
              "C. left atrium", "D. coronary sinus"],
  "correct_answer": "A",
  "explanation": "The ductus arteriosus connects the pulmonary trunk to the aorta, diverting right-ventricular output away from the collapsed lungs.",
  "related": ["Foetal shunts", "Foetal circulation"]},

 {"topic": "Foetal remnants", "difficulty": "hard",
  "question": "After birth, the foramen ovale becomes which adult structure?",
  "options": ["A. the fossa ovalis", "B. the ligamentum teres",
              "C. the ligamentum venosum", "D. the ligamentum arteriosum"],
  "correct_answer": "A",
  "explanation": "The foramen ovale seals to become the fossa ovalis; the ductus arteriosus becomes the ligamentum arteriosum.",
  "related": ["Foetal remnants", "Foetal circulation"]},

 {"topic": "Carotid receptors", "difficulty": "hard",
  "question": "The carotid sinus at the carotid bifurcation functions as a:",
  "options": ["A. baroreceptor", "B. chemoreceptor",
              "C. pacemaker site", "D. venous reservoir"],
  "correct_answer": "A",
  "explanation": "The carotid sinus is a baroreceptor sensing arterial stretch; the nearby carotid body is a chemoreceptor sensing O2, CO2 and pH.",
  "related": ["Carotid receptors", "Great vessels"]},

 {"topic": "Portal system", "difficulty": "hard",
  "question": "A portal system is defined as a venous circuit that runs blood between:",
  "options": ["A. two capillary beds", "B. two large arteries",
              "C. the atria and ventricles", "D. the lungs and heart"],
  "correct_answer": "A",
  "explanation": "A portal system interposes a second capillary bed, as in the hepatic portal vein carrying gut blood to the liver for first-pass processing.",
  "related": ["Portal system", "Venous drainage"]},

 {"topic": "Auscultation", "difficulty": "hard",
  "question": "The mitral valve is best auscultated at which location?",
  "options": ["A. the cardiac apex", "B. the right 2nd space",
              "C. the left 2nd space", "D. the jugular notch"],
  "correct_answer": "A",
  "explanation": "The mitral valve is heard at the apex in the left 5th intercostal space, midclavicular line, because flow is directed toward the apex.",
  "related": ["Auscultation", "Surface anatomy"]},

 {"topic": "Azygos system", "difficulty": "hard",
  "question": "The azygos venous system provides a collateral channel linking the:",
  "options": ["A. SVC and IVC", "B. aorta and pulmonary trunk",
              "C. two atria", "D. portal vein and liver"],
  "correct_answer": "A",
  "explanation": "The azygos system links the superior and inferior venae cavae along the posterior thoracic wall, a bypass if a cava is obstructed.",
  "related": ["Azygos system", "Venous drainage"]},
]

if __name__ == "__main__":
    sys.exit(emit(KEY, META, Q))
