#!/usr/bin/env python3
"""MHHS2402 W7 · The Circulatory System — Blood Pressure & Flow — regenerated bank (length-matched, no bracket tells, no daredevil)."""
import os, sys, json
HERE = os.path.dirname(os.path.abspath(__file__))
sys.path.insert(0, os.path.join(HERE, "..", "tools"))
from qbank_lib import emit  # noqa

KEY = "circulatory_system_mhhs2402_wk7.html"
BANK = json.load(open(os.path.join(HERE, "..", "..", "guide_quizzes.json"), encoding="utf-8"))
META = {k: BANK[KEY][k] for k in ("title", "subject", "unit", "content")}

Q = [
 # ── easy ──────────────────────────────────────────────────────────────
 {"topic": "Vessel order", "difficulty": "easy",
  "question": "Leaving the heart, blood passes through the vessels in which order?",
  "options": ["A. arteries, arterioles, capillaries, venules, veins",
              "B. veins, venules, capillaries, arterioles, arteries",
              "C. arteries, capillaries, arterioles, veins, venules",
              "D. arterioles, arteries, capillaries, veins, venules"],
  "correct_answer": "A",
  "explanation": "Blood always runs arteries, then arterioles, then capillaries, then venules, then veins, in both circuits.",
  "related": ["Vessel order", "Two circuits"]},

 {"topic": "Exchange vessels", "difficulty": "easy",
  "question": "Exchange of oxygen, nutrients and waste occurs across which vessels?",
  "options": ["A. capillaries", "B. arteries",
              "C. veins", "D. arterioles"],
  "correct_answer": "A",
  "explanation": "Capillaries are one cell thick, the only place where oxygen, carbon dioxide, nutrients and waste cross the vessel wall.",
  "related": ["Exchange vessels", "Vessel order"]},

 {"topic": "Blood pressure", "difficulty": "easy",
  "question": "Pulse pressure is calculated as systolic pressure minus:",
  "options": ["A. diastolic pressure", "B. mean pressure",
              "C. venous pressure", "D. atmospheric pressure"],
  "correct_answer": "A",
  "explanation": "Pulse pressure is simply the height of the arterial wave, the systolic pressure minus the diastolic pressure.",
  "related": ["Blood pressure", "Pressure wave"]},

 {"topic": "Resistance vessels", "difficulty": "easy",
  "question": "Which vessels are the body's main adjustable controllers of blood flow?",
  "options": ["A. arterioles", "B. capillaries",
              "C. large veins", "D. the aorta"],
  "correct_answer": "A",
  "explanation": "The small muscular arterioles set resistance and regional flow, acting as the body's adjustable taps.",
  "related": ["Resistance vessels", "Flow"]},

 {"topic": "Blood volume", "difficulty": "easy",
  "question": "At rest, most of the body's blood volume is held in the:",
  "options": ["A. systemic veins", "B. systemic arteries",
              "C. capillaries", "D. heart chambers"],
  "correct_answer": "A",
  "explanation": "About 64 percent of blood volume sits in the compliant systemic veins, the mobilisable capacitance reservoir.",
  "related": ["Blood volume", "Compliance"]},

 # ── medium ────────────────────────────────────────────────────────────
 {"topic": "Harvey", "difficulty": "medium",
  "question": "William Harvey proved blood circulates using an argument based on:",
  "options": ["A. the quantity of blood pumped", "B. the colour of the blood",
              "C. the pulse rate alone", "D. the shape of the heart"],
  "correct_answer": "A",
  "explanation": "Harvey showed the volume pumped per hour far exceeds what food could supply, so blood must be recirculated, not consumed.",
  "related": ["Harvey", "Circulation"]},

 {"topic": "Artery definition", "difficulty": "medium",
  "question": "An artery is defined as a vessel that carries blood:",
  "options": ["A. away from the heart", "B. toward the heart",
              "C. that is always oxygenated", "D. that is always red"],
  "correct_answer": "A",
  "explanation": "An artery carries blood away from the heart regardless of oxygen, which is why pulmonary arteries can be deoxygenated.",
  "related": ["Artery definition", "Two circuits"]},

 {"topic": "Vessel walls", "difficulty": "medium",
  "question": "The middle coat of a vessel wall that sets its diameter is the:",
  "options": ["A. tunica media", "B. tunica intima",
              "C. tunica adventitia", "D. the endothelium"],
  "correct_answer": "A",
  "explanation": "The tunica media of smooth muscle, elastin and collagen bears load and actively sets the vessel's diameter.",
  "related": ["Vessel walls", "Vessel structure"]},

 {"topic": "Windkessel", "difficulty": "medium",
  "question": "The elastic aorta smooths the heart's pulsatile ejection into steady flow, an effect called:",
  "options": ["A. the Windkessel effect", "B. the Bernoulli effect",
              "C. the Starling effect", "D. the Bohr effect"],
  "correct_answer": "A",
  "explanation": "The Windkessel effect: the elastic aorta stores part of each stroke in systole and recoils in diastole, giving near-continuous capillary flow.",
  "related": ["Windkessel", "Compliance"]},

 {"topic": "Compliance", "difficulty": "medium",
  "question": "Compliance of a vessel is defined as the change in volume divided by the change in:",
  "options": ["A. pressure", "B. flow",
              "C. resistance", "D. radius"],
  "correct_answer": "A",
  "explanation": "Compliance C equals change in volume over change in pressure; veins are far more compliant than arteries.",
  "related": ["Compliance", "Windkessel"]},

 {"topic": "MAP", "difficulty": "medium",
  "question": "Mean arterial pressure is best described as the:",
  "options": ["A. time-average of the pressure wave", "B. midpoint of systolic and diastolic",
              "C. peak of the pressure wave", "D. lowest arterial pressure"],
  "correct_answer": "A",
  "explanation": "MAP is the time-average of the whole pressure wave, sitting nearer diastolic because diastole lasts longer.",
  "related": ["MAP", "Pressure wave"]},

 {"topic": "Flow equation", "difficulty": "medium",
  "question": "Blood flow through a vessel equals the pressure gradient divided by the:",
  "options": ["A. resistance", "B. compliance",
              "C. radius", "D. viscosity"],
  "correct_answer": "A",
  "explanation": "Flow equals pressure difference over resistance, the fluid analogue of Ohm's law where pressure is the push and resistance the friction.",
  "related": ["Flow equation", "Resistance"]},

 {"topic": "Ohm analogy", "difficulty": "medium",
  "question": "In the electrical analogy for blood flow, blood flow corresponds to which electrical quantity?",
  "options": ["A. current", "B. voltage",
              "C. resistance", "D. capacitance"],
  "correct_answer": "A",
  "explanation": "Flow is the analogue of current, pressure difference of voltage, and resistance of resistance in the fluid version of Ohm's law.",
  "related": ["Ohm analogy", "Flow equation"]},

 {"topic": "MAP equation", "difficulty": "medium",
  "question": "Mean arterial pressure is approximately the product of cardiac output and:",
  "options": ["A. total peripheral resistance", "B. stroke volume",
              "C. pulse pressure", "D. venous compliance"],
  "correct_answer": "A",
  "explanation": "MAP is approximately cardiac output times total peripheral resistance, the master equation of blood pressure control.",
  "related": ["MAP equation", "MAP"]},

 {"topic": "Autoregulation", "difficulty": "medium",
  "question": "Autoregulation is a tissue's ability to keep its own blood flow steady despite changes in:",
  "options": ["A. systemic blood pressure", "B. blood cell shape",
              "C. body posture", "D. plasma colour"],
  "correct_answer": "A",
  "explanation": "Autoregulation holds local flow constant despite systemic pressure swings; it is strongest in the brain and coronary beds.",
  "related": ["Autoregulation", "Local control"]},

 {"topic": "Hyperaemia", "difficulty": "medium",
  "question": "The rise in blood flow to a muscle while it is active is called:",
  "options": ["A. active hyperaemia", "B. reactive hyperaemia",
              "C. autoregulation failure", "D. venous return"],
  "correct_answer": "A",
  "explanation": "Active hyperaemia is the flow rise driven by vasodilator metabolites during tissue activity; supply is matched to demand.",
  "related": ["Hyperaemia", "Local control"]},

 {"topic": "Blood composition", "difficulty": "medium",
  "question": "Blood consists of plasma plus the formed elements, which are red cells, platelets and:",
  "options": ["A. white cells", "B. hormones",
              "C. antibodies", "D. electrolytes"],
  "correct_answer": "A",
  "explanation": "The formed elements are red blood cells, white blood cells and platelets, suspended in the fluid plasma.",
  "related": ["Blood composition", "Blood constituents"]},

 # ── hard ──────────────────────────────────────────────────────────────
 {"topic": "Radius and resistance", "difficulty": "hard",
  "question": "By Poiseuille's law, resistance is inversely proportional to the vessel radius raised to the:",
  "options": ["A. fourth power", "B. second power",
              "C. first power", "D. third power"],
  "correct_answer": "A",
  "explanation": "Resistance varies as one over radius to the fourth power, so flow is proportional to the pressure gradient times radius to the fourth.",
  "related": ["Radius and resistance", "Flow equation"]},

 {"topic": "Halving radius", "difficulty": "hard",
  "question": "If a vessel's radius is halved at constant pressure, its flow falls to about:",
  "options": ["A. one sixteenth", "B. one half",
              "C. one quarter", "D. one eighth"],
  "correct_answer": "A",
  "explanation": "Because flow scales with radius to the fourth power, halving the radius cuts flow to two to the fourth, or one sixteenth.",
  "related": ["Halving radius", "Radius and resistance"]},

 {"topic": "Arteriole wall", "difficulty": "hard",
  "question": "Arterioles have the highest wall-thickness-to-radius ratio because this lets them:",
  "options": ["A. clamp down to set resistance", "B. store large blood volumes",
              "C. exchange gases rapidly", "D. conduct flow with no loss"],
  "correct_answer": "A",
  "explanation": "A thick wall on a narrow bore lets an arteriole generate a large pressure drop without tearing, so it can set resistance.",
  "related": ["Arteriole wall", "Resistance vessels"]},

 {"topic": "MAP estimate", "difficulty": "hard",
  "question": "The estimate MAP equals diastolic plus one third of pulse pressure is weighted toward diastole because:",
  "options": ["A. diastole lasts longer", "B. systole lasts longer",
              "C. diastole has higher pressure", "D. systole has lower pressure"],
  "correct_answer": "A",
  "explanation": "At rest the heart spends about two-thirds of each cycle in diastole, so the time-average weights the lower diastolic pressure more.",
  "related": ["MAP estimate", "MAP"]},

 {"topic": "Incisura", "difficulty": "hard",
  "question": "On the aortic pressure wave, the incisura (small notch) is caused by:",
  "options": ["A. aortic valve closure", "B. wave reflection",
              "C. atrial contraction", "D. mitral valve opening"],
  "correct_answer": "A",
  "explanation": "The incisura on the aortic wave marks aortic valve closure; the peripheral dichrotic notch has similar timing but arises from wave travel.",
  "related": ["Incisura", "Pressure wave"]},

 {"topic": "Peripheral systolic", "difficulty": "hard",
  "question": "Systolic pressure is higher in the radial artery than in the aorta because of:",
  "options": ["A. wave reflection", "B. lower resistance",
              "C. valve closure", "D. greater compliance"],
  "correct_answer": "A",
  "explanation": "Reflected pressure waves add onto the forward wave in the stiffer peripheral arteries, augmenting the systolic peak.",
  "related": ["Peripheral systolic", "Pressure wave"]},

 {"topic": "Pressure gradient", "difficulty": "hard",
  "question": "The steepest fall in mean pressure across the systemic circulation occurs at the:",
  "options": ["A. arterioles", "B. large arteries",
              "C. capillaries", "D. large veins"],
  "correct_answer": "A",
  "explanation": "The arterioles carry most of the resistance, so the biggest pressure drop happens across them, making them the flow-control point.",
  "related": ["Pressure gradient", "Resistance vessels"]},

 {"topic": "Shock", "difficulty": "hard",
  "question": "Using MAP equals cardiac output times resistance, septic shock lowers blood pressure chiefly by reducing:",
  "options": ["A. total peripheral resistance", "B. cardiac output",
              "C. blood viscosity", "D. venous compliance"],
  "correct_answer": "A",
  "explanation": "Septic and anaphylactic shock cause runaway vasodilation, dropping total peripheral resistance; hypovolaemic and cardiogenic shock drop cardiac output.",
  "related": ["Shock", "MAP equation"]},

 {"topic": "Essential hypertension", "difficulty": "hard",
  "question": "In most essential hypertension, cardiac output is near normal but there is a chronic rise in:",
  "options": ["A. total peripheral resistance", "B. stroke volume",
              "C. venous compliance", "D. pulse pressure"],
  "correct_answer": "A",
  "explanation": "Essential hypertension usually has near-normal output with chronically raised total peripheral resistance from narrowed arterioles.",
  "related": ["Essential hypertension", "MAP equation"]},

 {"topic": "Autoregulation theories", "difficulty": "hard",
  "question": "The myogenic theory of autoregulation holds that a rise in pressure makes vascular smooth muscle:",
  "options": ["A. contract when stretched", "B. relax when stretched",
              "C. release nitric oxide", "D. accumulate metabolites"],
  "correct_answer": "A",
  "explanation": "In the myogenic theory, stretch opens calcium channels so the smooth muscle contracts, raising resistance to oppose the pressure rise.",
  "related": ["Autoregulation theories", "Autoregulation"]},

 {"topic": "Vasodilator metabolites", "difficulty": "hard",
  "question": "Which substance, released as ATP is broken down, is a key local vasodilator in low oxygen?",
  "options": ["A. adenosine", "B. albumin",
              "C. fibrinogen", "D. collagen"],
  "correct_answer": "A",
  "explanation": "Adenosine, along with carbon dioxide, potassium and hydrogen ions, is released in low oxygen and dilates the local arterioles.",
  "related": ["Vasodilator metabolites", "Autoregulation theories"]},

 {"topic": "Reactive hyperaemia", "difficulty": "hard",
  "question": "Reactive hyperaemia is the surge of flow that occurs after:",
  "options": ["A. an occlusion is released", "B. a meal is digested",
              "C. the heart rate slows", "D. blood is transfused"],
  "correct_answer": "A",
  "explanation": "During occlusion metabolites accumulate and dilate the bed; when flow returns, the low-resistance bed lets a large compensatory surge through.",
  "related": ["Reactive hyperaemia", "Hyperaemia"]},

 {"topic": "Nitric oxide", "difficulty": "hard",
  "question": "The endothelium releases nitric oxide, which relaxes vascular smooth muscle by raising:",
  "options": ["A. cGMP", "B. cAMP",
              "C. calcium", "D. sodium"],
  "correct_answer": "A",
  "explanation": "NO activates guanylate cyclase, which converts GTP to cGMP, and cGMP relaxes the smooth muscle, causing vasodilation.",
  "related": ["Nitric oxide", "Local control"]},

 {"topic": "NO trigger", "difficulty": "hard",
  "question": "Endothelial nitric oxide release is triggered mechanically by:",
  "options": ["A. flow shear stress", "B. falling blood volume",
              "C. rising body temperature", "D. platelet clumping"],
  "correct_answer": "A",
  "explanation": "Shear stress from blood flowing along the wall activates nitric oxide synthase, converting L-arginine to nitric oxide.",
  "related": ["NO trigger", "Nitric oxide"]},

 {"topic": "Oxygen delivery", "difficulty": "hard",
  "question": "Oxygen delivery to a tissue equals blood flow multiplied by the:",
  "options": ["A. oxygen content", "B. pulse pressure",
              "C. vessel radius", "D. plasma volume"],
  "correct_answer": "A",
  "explanation": "Delivery equals flow times oxygen content, so when content falls, as in anaemia or CO poisoning, only raising flow can defend delivery.",
  "related": ["Oxygen delivery", "Blood constituents"]},

 {"topic": "Carbon monoxide", "difficulty": "hard",
  "question": "Carbon monoxide poisoning starves tissues despite an apparently normal blood pressure because it lowers:",
  "options": ["A. blood oxygen content", "B. blood flow rate",
              "C. total peripheral resistance", "D. arterial radius"],
  "correct_answer": "A",
  "explanation": "CO binds haemoglobin far tighter than oxygen, collapsing oxygen content even though flow and blood pressure look normal.",
  "related": ["Carbon monoxide", "Oxygen delivery"]},
]

if __name__ == "__main__":
    sys.exit(emit(KEY, META, Q))
