#!/usr/bin/env python3
"""MEDI2200 W6 · Gene Expression (transcription & translation) — regenerated bank."""
import os, sys, json
HERE = os.path.dirname(os.path.abspath(__file__))
sys.path.insert(0, os.path.join(HERE, "..", "tools"))
from qbank_lib import emit  # noqa

KEY = "gene_expression_medi2200_wk6.html"
BANK = json.load(open(os.path.join(HERE, "..", "..", "guide_quizzes.json"), encoding="utf-8"))
META = {k: BANK[KEY][k] for k in ("title", "subject", "unit", "content")}

Q = [
 {"topic": "RNA synthesis", "difficulty": "medium",
  "question": "In which direction is a new RNA strand synthesised?",
  "options": ["A. 5′ → 3′, adding to the free 3′-OH",
              "B. 3′ → 5′, adding to the free 5′-OH",
              "C. both ends at the same time",
              "D. from the middle of the strand outward"],
  "correct_answer": "A",
  "explanation": "The only reactive site for chain growth is the free 3′-OH, so RNA is always extended 5′ → 3′.",
  "related": ["RNA synthesis", "RNA polymerases"]},

 {"topic": "Base pairing", "difficulty": "easy",
  "question": "In RNA, adenine base-pairs with which base?",
  "options": ["A. uracil", "B. thymine", "C. guanine", "D. cytosine"],
  "correct_answer": "A",
  "explanation": "RNA uses uracil in place of thymine, so A pairs U while C pairs G — each a purine with a pyrimidine.",
  "related": ["Base pairing", "RNA chemistry"]},

 {"topic": "Codons", "difficulty": "easy",
  "question": "Which codon starts translation, and which amino acid does it specify?",
  "options": ["A. AUG — methionine", "B. UAA — leucine",
              "C. GUA — valine", "D. UGA — tryptophan"],
  "correct_answer": "A",
  "explanation": "AUG is the start codon and codes for methionine; it also sets the reading frame.",
  "related": ["Codons", "Initiation"]},

 {"topic": "Codons", "difficulty": "easy",
  "question": "Which set lists the three stop codons?",
  "options": ["A. UAA, UAG, UGA", "B. AUG, UGG, UAC",
              "C. UAA, AUG, GUA", "D. UGA, UGG, UGC"],
  "correct_answer": "A",
  "explanation": "UAA, UAG and UGA are the three termination codons; none specifies an amino acid.",
  "related": ["Codons", "Termination"]},

 {"topic": "RNA polymerases", "difficulty": "easy",
  "question": "Which eukaryotic RNA polymerase synthesises mRNA?",
  "options": ["A. RNA polymerase II", "B. RNA polymerase I",
              "C. RNA polymerase III", "D. DNA polymerase δ"],
  "correct_answer": "A",
  "explanation": "RNA Pol II makes mRNA (plus snRNA and miRNA); Pol I makes pre-rRNA and Pol III makes tRNA.",
  "related": ["RNA polymerases", "RNA synthesis"]},

 {"topic": "5′ cap", "difficulty": "medium",
  "question": "What molecule forms the 5′ cap added to eukaryotic mRNA?",
  "options": ["A. 7-methylguanosine", "B. a poly-A tail",
              "C. a branch-point adenosine", "D. a Kozak sequence"],
  "correct_answer": "A",
  "explanation": "A 7-methylguanosine is added to the 5′ end via an unusual 5′-to-5′ linkage soon after transcription starts.",
  "related": ["5′ cap", "RNA processing"]},

 {"topic": "Genetic code", "difficulty": "medium",
  "question": "Of the 64 codons, how many specify amino acids versus stop?",
  "options": ["A. 61 code, 3 stop", "B. 60 code, 4 stop",
              "C. 64 code, 0 stop", "D. 58 code, 6 stop"],
  "correct_answer": "A",
  "explanation": "Of 64 codons, 61 specify amino acids and 3 are stop codons — which is why the code is redundant.",
  "related": ["Genetic code", "Redundancy of the code"]},

 {"topic": "Ribosome sites", "difficulty": "medium",
  "question": "Which ribosomal site binds the incoming charged tRNA?",
  "options": ["A. the A site", "B. the P site",
              "C. the E site", "D. the anticodon loop"],
  "correct_answer": "A",
  "explanation": "The A site accepts the incoming charged tRNA; the P site holds the growing peptide; the E site is the exit.",
  "related": ["Ribosome sites", "Elongation"]},

 {"topic": "Ribosome assembly", "difficulty": "medium",
  "question": "Which two subunits join to form the eukaryotic 80S ribosome?",
  "options": ["A. 40S + 60S", "B. 30S + 50S", "C. 40S + 40S", "D. 60S + 60S"],
  "correct_answer": "A",
  "explanation": "The small 40S and large 60S subunits, assembled in the nucleolus, join on the mRNA to form the 80S ribosome.",
  "related": ["Ribosome assembly", "Svedberg units"]},

 {"topic": "tRNA", "difficulty": "easy",
  "question": "Which part of a tRNA base-pairs with the mRNA codon?",
  "options": ["A. the anticodon", "B. the acceptor stem",
              "C. the amino acid", "D. the 5′ cap"],
  "correct_answer": "A",
  "explanation": "The anticodon — three bases in the anticodon loop — pairs the complementary codon; the amino acid attaches at the acceptor stem.",
  "related": ["tRNA", "Codons"]},

 {"topic": "RNA chemistry", "difficulty": "medium",
  "question": "How does ribose's 2′-OH group affect RNA compared with DNA?",
  "options": ["A. it makes RNA more reactive and less stable",
              "B. it makes RNA more stable and quite inert",
              "C. it lets RNA store the archival copy",
              "D. it stops RNA from ever base-pairing again"],
  "correct_answer": "A",
  "explanation": "The reactive 2′-OH, absent in DNA, makes RNA less stable — why DNA is the archival copy and mRNA is disposable.",
  "related": ["RNA chemistry", "Base pairing"]},

 {"topic": "Gene structure", "difficulty": "medium",
  "question": "What distinguishes an exon from an intron?",
  "options": ["A. exons stay in mature mRNA; introns are removed",
              "B. introns stay in mature mRNA; exons are removed",
              "C. exons are never transcribed in the first place",
              "D. introns code directly for the final protein"],
  "correct_answer": "A",
  "explanation": "Both are transcribed, but introns are spliced out and the exons (expressed sequences) are joined for the mature mRNA.",
  "related": ["Gene structure", "Splicing"]},

 {"topic": "Template vs coding strand", "difficulty": "medium",
  "question": "Why is the non-template strand called the 'coding' strand?",
  "options": ["A. its sequence equals the RNA, T replacing U",
              "B. it is the strand actually read by polymerase",
              "C. it carries all the introns of the gene",
              "D. it is always shorter than the template"],
  "correct_answer": "A",
  "explanation": "The template strand is read by the polymerase; the coding strand is named for matching the RNA sequence, with T in place of U.",
  "related": ["Template vs coding strand", "RNA synthesis"]},

 {"topic": "RNA polymerases", "difficulty": "medium",
  "question": "Compared with DNA polymerase, RNA polymerase:",
  "options": ["A. needs no primer and proofreads only modestly",
              "B. needs a primer and proofreads very tightly",
              "C. cannot start a chain without a primer",
              "D. copies DNA with perfect fidelity always"],
  "correct_answer": "A",
  "explanation": "RNA polymerase starts a chain without a primer and proofreads only modestly (~1 error per 10⁴ nt), acceptable for disposable transcripts.",
  "related": ["RNA polymerases", "RNA synthesis"]},

 {"topic": "Pre-initiation complex", "difficulty": "medium",
  "question": "What forms the conserved core of a Pol II pre-initiation complex?",
  "options": ["A. Pol II, TBP and the general transcription factors",
              "B. Pol II, DNA ligase and a poly-A polymerase",
              "C. Pol III, primase and a sliding clamp",
              "D. Pol I, helicase and a single-strand binding protein"],
  "correct_answer": "A",
  "explanation": "The PIC core is RNA Pol II plus the TATA-binding protein and the general transcription factors; TBP nucleates the complex.",
  "related": ["Pre-initiation complex", "Promoter recognition"]},

 {"topic": "Splicing", "difficulty": "medium",
  "question": "In the first splicing step, the branch-point adenosine:",
  "options": ["A. attacks the 5′ splice site",
              "B. binds the 5′ cap of the transcript",
              "C. adds the poly-A tail to the 3′ end",
              "D. joins the two exons directly together"],
  "correct_answer": "A",
  "explanation": "The branch-point A attacks the phosphodiester bond at the 5′ splice site, cleaving the 5′ exon and forming a lariat intermediate.",
  "related": ["Splicing", "Gene structure"]},

 {"topic": "Polyadenylation", "difficulty": "medium",
  "question": "Which factor recognises the AAUAAA polyadenylation signal?",
  "options": ["A. CPSF", "B. CstF", "C. TFIIH", "D. eRF1"],
  "correct_answer": "A",
  "explanation": "CPSF binds the AAUAAA signal while CstF binds the downstream GU-rich sequence; poly-A polymerase then adds the tail.",
  "related": ["Polyadenylation", "RNA processing"]},

 {"topic": "Wobble", "difficulty": "medium",
  "question": "At which codon position is 'wobble' pairing tolerated?",
  "options": ["A. the third position", "B. the first position",
              "C. the second position", "D. every position equally"],
  "correct_answer": "A",
  "explanation": "Pairing is strict at positions 1 and 2, but a purine–pyrimidine wobble is tolerated at the third position, aiding redundancy.",
  "related": ["Wobble", "tRNA"]},

 {"topic": "Initiation", "difficulty": "medium",
  "question": "How does the small subunit locate the start codon during initiation?",
  "options": ["A. it scans the 5′ cap to the AUG",
              "B. it binds straight onto the poly-A tail",
              "C. it starts at the 3′ end reading back",
              "D. it locks onto the branch-point adenosine first"],
  "correct_answer": "A",
  "explanation": "The 40S subunit with initiation factors and initiator tRNA-Met scans from the 5′ cap to the first AUG in a Kozak context.",
  "related": ["Initiation", "Codons"]},

 {"topic": "Elongation", "difficulty": "medium",
  "question": "What powers each step of translation elongation, and how fast is it?",
  "options": ["A. GTP hydrolysis, about 15 amino acids per second",
              "B. ATP hydrolysis, about 2 amino acids per second",
              "C. GTP hydrolysis, about 1 amino acid per minute",
              "D. proton flow, about 50 amino acids per second"],
  "correct_answer": "A",
  "explanation": "Elongation factors spend GTP for each of the three steps; eukaryotic elongation runs at ~15 amino acids per second.",
  "related": ["Elongation", "Ribosome sites"]},

 {"topic": "Cell cycle timing", "difficulty": "hard",
  "question": "When do DNA replication and most transcription occur in the cycle?",
  "options": ["A. replication in S-phase; most transcription in G1",
              "B. both entirely during mitosis itself",
              "C. replication in G1; transcription in S-phase",
              "D. both only during the G0 resting phase"],
  "correct_answer": "A",
  "explanation": "DNA is replicated in S-phase before division; transcription happens mainly in G1, after division, when the cell grows.",
  "related": ["Cell cycle timing", "RNA synthesis"]},

 {"topic": "Energetics", "difficulty": "hard",
  "question": "Where does the energy for adding each nucleotide during transcription come from?",
  "options": ["A. hydrolysis of the incoming rNTP to rNMP",
              "B. hydrolysis of a separate ATP molecule",
              "C. breakdown of the DNA template strand",
              "D. cleavage of the 5′ cap structure"],
  "correct_answer": "A",
  "explanation": "Each incoming ribonucleotide triphosphate is hydrolysed to rNMP plus pyrophosphate; releasing pyrophosphate drives the addition.",
  "related": ["Energetics", "RNA synthesis"]},

 {"topic": "Polymerase inhibition", "difficulty": "hard",
  "question": "The death-cap toxin α-amanitin is lethal chiefly because it inhibits:",
  "options": ["A. RNA polymerase II, halting mRNA synthesis",
              "B. RNA polymerase I, halting rRNA synthesis",
              "C. DNA polymerase, halting replication",
              "D. the ribosome, halting translation directly"],
  "correct_answer": "A",
  "explanation": "α-amanitin specifically blocks RNA Pol II; with mRNA synthesis shut down, protein production collapses.",
  "related": ["Polymerase inhibition", "RNA polymerases"]},

 {"topic": "TFIIH", "difficulty": "hard",
  "question": "Which two activities does TFIIH bring to transcription initiation?",
  "options": ["A. a DNA helicase and a CDK7 kinase",
              "B. a ligase and an exonuclease",
              "C. a primase and a sliding clamp",
              "D. a poly-A polymerase and a capping enzyme"],
  "correct_answer": "A",
  "explanation": "TFIIH's helicase/ATPase opens the DNA into the open complex, and its CDK7 kinase phosphorylates Pol II to start elongation.",
  "related": ["TFIIH", "Pre-initiation complex"]},

 {"topic": "Promoter recognition", "difficulty": "hard",
  "question": "Why is TATA-binding protein still needed at promoters lacking a TATA box?",
  "options": ["A. it is a conserved PIC core component",
              "B. it directly transcribes the first few bases",
              "C. it splices the introns from the transcript",
              "D. it adds the 5′ cap before elongation"],
  "correct_answer": "A",
  "explanation": "TBP is part of the universal PIC core; it nucleates the complex and positions the polymerase at TATA and TATA-less promoters alike.",
  "related": ["Promoter recognition", "Pre-initiation complex"]},

 {"topic": "Alternative splicing", "difficulty": "hard",
  "question": "What is the main functional consequence of alternative splicing?",
  "options": ["A. one gene can make several protein species",
              "B. one gene can make only one protein",
              "C. it permanently deletes the gene's exons",
              "D. it stops the transcript from leaving the nucleus"],
  "correct_answer": "A",
  "explanation": "By choosing which exons to keep, alternative splicing lets one DNA sequence encode multiple related proteins.",
  "related": ["Alternative splicing", "Splicing"]},

 {"topic": "Redundancy of the code", "difficulty": "hard",
  "question": "Saying the genetic code is 'redundant' (degenerate) means:",
  "options": ["A. one amino acid can have several codons",
              "B. one codon can code several amino acids",
              "C. every amino acid has exactly one codon",
              "D. most codons specify no amino acid"],
  "correct_answer": "A",
  "explanation": "With 61 coding codons for 20 amino acids, most amino acids are specified by several codons — one to six each.",
  "related": ["Redundancy of the code", "Genetic code"]},

 {"topic": "tRNA charging", "difficulty": "hard",
  "question": "How does an aminoacyl-tRNA synthetase help drive later peptide-bond formation?",
  "options": ["A. it joins amino acid to tRNA with ATP",
              "B. it hydrolyses GTP inside the ribosome",
              "C. it reads the codon in the A site",
              "D. it removes the stop codon from mRNA"],
  "correct_answer": "A",
  "explanation": "Each synthetase charges its tRNA using ATP, forming a high-energy amino-acid–tRNA bond whose energy later drives peptide-bond formation.",
  "related": ["tRNA charging", "Elongation"]},

 {"topic": "Termination", "difficulty": "hard",
  "question": "Why does a stop codon end translation even though it enters the A site?",
  "options": ["A. no tRNA fits it, so eRF1 binds instead",
              "B. a special tRNA delivers a stop amino acid",
              "C. the ribosome reverses to the start codon",
              "D. the mRNA cap is cleaved at that point"],
  "correct_answer": "A",
  "explanation": "No tRNA has an anticodon for a stop codon; instead release factor eRF1 recognises it in the A site and frees the polypeptide.",
  "related": ["Termination", "Ribosome sites"]},

 {"topic": "Svedberg units", "difficulty": "hard",
  "question": "Why do a 40S and a 60S subunit combine into an 80S ribosome, not a 100S one?",
  "options": ["A. S values are sedimentation rates, not additive",
              "B. some mass is lost when the subunits join",
              "C. the mRNA subtracts twenty S units",
              "D. one subunit shrinks during assembly"],
  "correct_answer": "A",
  "explanation": "The 'S' is a Svedberg sedimentation unit reflecting both mass and shape, so the values are not simply additive.",
  "related": ["Svedberg units", "Ribosome assembly"]},
]

if __name__ == "__main__":
    sys.exit(emit(KEY, META, Q))
