#!/usr/bin/env python3
"""MHHS2402 W6 · The Heart — Cardiac Cycle, Conduction & Output — regenerated bank (length-matched, no bracket tells, no daredevil)."""
import os, sys, json
HERE = os.path.dirname(os.path.abspath(__file__))
sys.path.insert(0, os.path.join(HERE, "..", "tools"))
from qbank_lib import emit  # noqa

KEY = "heart_physiology_mhhs2402_wk6.html"
BANK = json.load(open(os.path.join(HERE, "..", "..", "guide_quizzes.json"), encoding="utf-8"))
META = {k: BANK[KEY][k] for k in ("title", "subject", "unit", "content")}

Q = [
 # ── easy ──────────────────────────────────────────────────────────────
 {"topic": "Myocardial cells", "difficulty": "easy",
  "question": "Which cardiac cell type does most of the actual pumping?",
  "options": ["A. contractile cells", "B. autorhythmic cells",
              "C. conductive cells", "D. pacemaker cells"],
  "correct_answer": "A",
  "explanation": "Contractile myocytes make up the bulk of the heart and do the pumping; the pacemaker and conductive cells are few.",
  "related": ["Myocardial cells", "Contractile cells"]},

 {"topic": "Cardiac action potential", "difficulty": "easy",
  "question": "Which ion produces the long plateau of the cardiac action potential?",
  "options": ["A. calcium", "B. sodium",
              "C. potassium", "D. chloride"],
  "correct_answer": "A",
  "explanation": "Calcium entering through L-type channels holds the plateau, the hallmark of the cardiac action potential and the trigger for contraction.",
  "related": ["Cardiac action potential", "Plateau"]},

 {"topic": "Stroke volume", "difficulty": "easy",
  "question": "Stroke volume is calculated as end-diastolic volume minus:",
  "options": ["A. end-systolic volume", "B. cardiac output",
              "C. ejection fraction", "D. heart rate"],
  "correct_answer": "A",
  "explanation": "Stroke volume equals end-diastolic volume minus end-systolic volume, the blood ejected by a ventricle in one beat.",
  "related": ["Stroke volume", "Cardiac output"]},

 {"topic": "Cardiac output", "difficulty": "easy",
  "question": "Cardiac output equals stroke volume multiplied by:",
  "options": ["A. heart rate", "B. ejection fraction",
              "C. blood pressure", "D. end-systolic volume"],
  "correct_answer": "A",
  "explanation": "Cardiac output is stroke volume times heart rate, giving the total blood flow in litres per minute.",
  "related": ["Cardiac output", "Stroke volume"]},

 {"topic": "ECG waves", "difficulty": "easy",
  "question": "On the ECG, ventricular depolarisation produces which deflection?",
  "options": ["A. the QRS complex", "B. the P wave",
              "C. the T wave", "D. the U wave"],
  "correct_answer": "A",
  "explanation": "The QRS complex is ventricular depolarisation; the P wave is atrial depolarisation and the T wave is ventricular repolarisation.",
  "related": ["ECG waves", "Electrocardiogram"]},

 # ── medium ────────────────────────────────────────────────────────────
 {"topic": "Circuits in series", "difficulty": "medium",
  "question": "The outputs of the right and left ventricles must be equal because the circuits are:",
  "options": ["A. in series", "B. in parallel",
              "C. independent", "D. reversed"],
  "correct_answer": "A",
  "explanation": "The pulmonary and systemic circuits are in series, so over time each ventricle must pump the same volume or blood dams up.",
  "related": ["Circuits in series", "Pump"]},

 {"topic": "Intercalated discs", "difficulty": "medium",
  "question": "Which component of the intercalated disc provides electrical coupling between cardiac cells?",
  "options": ["A. gap junctions", "B. desmosomes",
              "C. sarcomeres", "D. mitochondria"],
  "correct_answer": "A",
  "explanation": "Gap junctions let ionic current flow cell to cell, while desmosomes provide the mechanical anchoring within the disc.",
  "related": ["Intercalated discs", "Contractile cells"]},

 {"topic": "Desmosomes", "difficulty": "medium",
  "question": "Within the intercalated disc, desmosomes function to:",
  "options": ["A. anchor cells mechanically", "B. conduct the impulse",
              "C. store calcium ions", "D. generate the beat"],
  "correct_answer": "A",
  "explanation": "Desmosomes rivet cardiac cells together so the force of contraction does not tear them apart, acting like staples.",
  "related": ["Desmosomes", "Intercalated discs"]},

 {"topic": "Resting potential", "difficulty": "medium",
  "question": "The resting membrane potential of a cardiac contractile cell sits near:",
  "options": ["A. minus 90 millivolts", "B. plus 20 millivolts",
              "C. zero millivolts", "D. plus 81 millivolts"],
  "correct_answer": "A",
  "explanation": "At rest the membrane is most permeable to potassium, so the potential sits near minus 90 millivolts, close to the potassium equilibrium.",
  "related": ["Resting potential", "Cardiac action potential"]},

 {"topic": "AP upstroke", "difficulty": "medium",
  "question": "The rapid upstroke (phase 0) of the cardiac action potential is driven by influx of:",
  "options": ["A. sodium", "B. calcium",
              "C. potassium", "D. chloride"],
  "correct_answer": "A",
  "explanation": "A fast sodium influx drives phase 0, rocketing the membrane from minus 90 toward positive voltages.",
  "related": ["AP upstroke", "Cardiac action potential"]},

 {"topic": "Repolarisation", "difficulty": "medium",
  "question": "Repolarisation of the cardiac action potential is achieved mainly by efflux of:",
  "options": ["A. potassium", "B. sodium",
              "C. calcium", "D. bicarbonate"],
  "correct_answer": "A",
  "explanation": "Potassium leaving the cell carries positive charge out, returning the membrane toward its resting potential.",
  "related": ["Repolarisation", "Cardiac action potential"]},

 {"topic": "Conduction pathway", "difficulty": "medium",
  "question": "After the atrioventricular node, the impulse travels next into the:",
  "options": ["A. bundle of His", "B. Purkinje fibres",
              "C. sinoatrial node", "D. coronary sinus"],
  "correct_answer": "A",
  "explanation": "From the AV node the impulse passes into the bundle of His, which divides into the left and right bundle branches.",
  "related": ["Conduction pathway", "Conduction"]},

 {"topic": "SA node", "difficulty": "medium",
  "question": "The sinoatrial node sets the heart rate because it has the:",
  "options": ["A. steepest prepotential", "B. slowest prepotential",
              "C. largest cell mass", "D. longest refractory period"],
  "correct_answer": "A",
  "explanation": "The SA node's prepotential rises fastest, so it reaches threshold first and resets the slower backup pacemakers each beat.",
  "related": ["SA node", "Pacemaker hierarchy"]},

 {"topic": "Diastole", "difficulty": "medium",
  "question": "During diastole, the ventricles are:",
  "options": ["A. relaxed and filling", "B. contracting and ejecting",
              "C. fully emptied", "D. electrically silent"],
  "correct_answer": "A",
  "explanation": "In diastole the ventricles relax and fill through the open AV valves, ending at the end-diastolic volume.",
  "related": ["Diastole", "Cardiac cycle"]},

 {"topic": "Ejection fraction", "difficulty": "medium",
  "question": "A normal resting ejection fraction is approximately:",
  "options": ["A. one-half to two-thirds", "B. one-tenth to one-fifth",
              "C. nearly one hundred percent", "D. under one-quarter"],
  "correct_answer": "A",
  "explanation": "A normal ejection fraction is roughly one-half to two-thirds of the filled ventricle ejected each beat.",
  "related": ["Ejection fraction", "Cardiac output"]},

 {"topic": "Einthoven's triangle", "difficulty": "medium",
  "question": "The three bipolar limb leads (I, II, III) are formed from electrodes on the:",
  "options": ["A. arms and left leg", "B. chest wall alone",
              "C. both legs and head", "D. neck and both arms"],
  "correct_answer": "A",
  "explanation": "Einthoven's triangle uses right arm, left arm and left leg electrodes to define the three bipolar limb leads.",
  "related": ["Einthoven's triangle", "Electrocardiogram"]},

 # ── hard ──────────────────────────────────────────────────────────────
 {"topic": "Excitation-contraction", "difficulty": "hard",
  "question": "In cardiac muscle, calcium entering through L-type channels triggers a larger release from the:",
  "options": ["A. sarcoplasmic reticulum", "B. intercalated disc",
              "C. mitochondria", "D. T-tubule lumen"],
  "correct_answer": "A",
  "explanation": "A small calcium influx triggers a larger release from the sarcoplasmic reticulum through ryanodine receptors, called calcium-induced calcium release.",
  "related": ["Excitation-contraction", "Plateau"]},

 {"topic": "Extracellular calcium", "difficulty": "hard",
  "question": "Cardiac muscle differs from skeletal muscle in that its contraction depends on:",
  "options": ["A. extracellular calcium", "B. stored glycogen",
              "C. motor nerve input", "D. a single nucleus"],
  "correct_answer": "A",
  "explanation": "Cardiac contraction needs an extracellular calcium trigger to spark SR release; without it there is no contraction.",
  "related": ["Extracellular calcium", "Excitation-contraction"]},

 {"topic": "Refractory period", "difficulty": "hard",
  "question": "The long cardiac action potential prevents the heart from being:",
  "options": ["A. tetanised", "B. depolarised",
              "C. relaxed", "D. filled"],
  "correct_answer": "A",
  "explanation": "The long action potential gives a long refractory period, so contractions cannot summate into tetanus and the heart always refills.",
  "related": ["Refractory period", "Plateau"]},

 {"topic": "Oxygen extraction", "difficulty": "hard",
  "question": "The heart has little oxygen reserve because at rest it already extracts about:",
  "options": ["A. 70 to 80 percent", "B. 20 to 30 percent",
              "C. 5 to 10 percent", "D. 40 to 50 percent"],
  "correct_answer": "A",
  "explanation": "The myocardium extracts 70 to 80 percent of delivered oxygen, so extra demand must be met by raising coronary blood flow.",
  "related": ["Oxygen extraction", "Contractile cells"]},

 {"topic": "Nernst potential", "difficulty": "hard",
  "question": "The equilibrium potential predicted for a single ion is given by which equation?",
  "options": ["A. the Nernst equation", "B. the Frank-Starling law",
              "C. the Fick equation", "D. Poiseuille's law"],
  "correct_answer": "A",
  "explanation": "The Nernst equation gives the voltage at which an ion's diffusion is balanced by the electrical pull, such as plus 81 mV for sodium.",
  "related": ["Nernst potential", "Resting potential"]},

 {"topic": "AV delay", "difficulty": "hard",
  "question": "The deliberate delay at the AV node allows time for the:",
  "options": ["A. atrial kick to fill ventricles", "B. ventricles to repolarise fully",
              "C. coronary arteries to refill", "D. SA node to reset itself"],
  "correct_answer": "A",
  "explanation": "The AV delay lets the atria finish contracting and deliver their atrial kick before the ventricles eject, maximising stroke volume.",
  "related": ["AV delay", "Conduction"]},

 {"topic": "Conduction velocity", "difficulty": "hard",
  "question": "Which cardiac tissue conducts the impulse fastest?",
  "options": ["A. Purkinje fibres", "B. ventricular muscle",
              "C. atrial muscle", "D. the AV node"],
  "correct_answer": "A",
  "explanation": "Purkinje fibres conduct around 4 metres per second, far faster than ventricular muscle, so the ventricles depolarise almost together.",
  "related": ["Conduction velocity", "Conduction"]},

 {"topic": "Overdrive suppression", "difficulty": "hard",
  "question": "The SA node keeps the slower pacemakers silent by a mechanism called:",
  "options": ["A. overdrive suppression", "B. calcium sparking",
              "C. wave summation", "D. the atrial kick"],
  "correct_answer": "A",
  "explanation": "By firing first and resetting the others each cycle, the SA node imposes its rate through overdrive suppression.",
  "related": ["Overdrive suppression", "Pacemaker hierarchy"]},

 {"topic": "Complete heart block", "difficulty": "hard",
  "question": "In complete heart block, the ECG shows P waves that are:",
  "options": ["A. independent of the QRS", "B. locked to each QRS",
              "C. completely absent", "D. inverted before each QRS"],
  "correct_answer": "A",
  "explanation": "In complete block the atria and ventricles beat separately, so P waves march independently of the QRS complexes.",
  "related": ["Complete heart block", "Pacemaker hierarchy"]},

 {"topic": "PR interval", "difficulty": "hard",
  "question": "A prolonged PR interval on the ECG indicates:",
  "options": ["A. first-degree heart block", "B. left ventricular hypertrophy",
              "C. a bundle branch block", "D. an anterior infarct"],
  "correct_answer": "A",
  "explanation": "The PR interval measures atrial conduction plus the AV delay, so a prolonged PR interval indicates first-degree heart block.",
  "related": ["PR interval", "Electrocardiogram"]},

 {"topic": "Intervals versus amplitudes", "difficulty": "hard",
  "question": "On the ECG, the amplitude (height) of a wave chiefly reports the:",
  "options": ["A. mass of muscle depolarising", "B. speed of conduction",
              "C. duration of the beat", "D. direction of the arrow"],
  "correct_answer": "A",
  "explanation": "Amplitude scales with the mass of muscle depolarising together, so tall waves suggest hypertrophy; intervals instead report conduction.",
  "related": ["Intervals versus amplitudes", "Electrocardiogram"]},

 {"topic": "Contractility", "difficulty": "hard",
  "question": "Raising contractility increases stroke volume mainly by lowering the:",
  "options": ["A. end-systolic volume", "B. end-diastolic volume",
              "C. heart rate", "D. ejection fraction"],
  "correct_answer": "A",
  "explanation": "A stronger squeeze empties the ventricle more completely, lowering the end-systolic volume and so widening the stroke volume.",
  "related": ["Contractility", "Stroke volume"]},

 {"topic": "Digoxin", "difficulty": "hard",
  "question": "Digoxin boosts contractility by partially blocking which pump?",
  "options": ["A. the sodium-potassium ATPase", "B. the L-type calcium channel",
              "C. the ryanodine receptor", "D. the sodium fast channel"],
  "correct_answer": "A",
  "explanation": "Digoxin blocks the sodium-potassium ATPase, raising intracellular sodium, which slows calcium export so more calcium stays to boost contraction.",
  "related": ["Digoxin", "Excitation-contraction"]},

 {"topic": "Systolic heart failure", "difficulty": "hard",
  "question": "In systolic heart failure, falling contractility causes both stroke volume and ejection fraction to:",
  "options": ["A. drop", "B. rise",
              "C. stay normal", "D. double"],
  "correct_answer": "A",
  "explanation": "Reduced contractility leaves more blood behind each beat, raising end-systolic volume so stroke volume and ejection fraction fall.",
  "related": ["Systolic heart failure", "Contractility"]},

 {"topic": "Cells on the ECG", "difficulty": "hard",
  "question": "Pacemaker and conductive cells barely appear on the ECG because they have:",
  "options": ["A. too little tissue mass", "B. no action potentials",
              "C. no gap junctions", "D. a very short plateau"],
  "correct_answer": "A",
  "explanation": "The ECG sums activity in proportion to tissue mass, so the few small pacemaker and conductive cells are swamped by the contractile muscle.",
  "related": ["Cells on the ECG", "Myocardial cells"]},

 {"topic": "ST segment", "difficulty": "hard",
  "question": "A shift in the ST segment on the ECG is the key sign of:",
  "options": ["A. myocardial ischaemia", "B. atrial enlargement",
              "C. a slow heart rate", "D. bundle branch block"],
  "correct_answer": "A",
  "explanation": "ST-segment shift is the key marker of ischaemia or infarction, and its lead pattern points to the culprit coronary artery.",
  "related": ["ST segment", "Electrocardiogram"]},
]

if __name__ == "__main__":
    sys.exit(emit(KEY, META, Q))
