#!/usr/bin/env python3
"""MEDI2200 W4 · Meiosis — regenerated bank (length-matched, no bracket tells, no daredevil)."""
import os, sys, json
HERE = os.path.dirname(os.path.abspath(__file__))
sys.path.insert(0, os.path.join(HERE, "..", "tools"))
from qbank_lib import emit  # noqa

KEY = "meiosis_medi2200_wk4.html"
BANK = json.load(open(os.path.join(HERE, "..", "..", "guide_quizzes.json"), encoding="utf-8"))
META = {k: BANK[KEY][k] for k in ("title", "subject", "unit", "content")}

Q = [
 {"topic": "Purpose", "difficulty": "easy",
  "question": "Gametes must be haploid so that fertilisation:",
  "options": ["A. restores the normal diploid number",
              "B. doubles the diploid number each generation",
              "C. keeps every offspring genetically identical",
              "D. removes one chromosome from the zygote"],
  "correct_answer": "A",
  "explanation": "Two haploid gametes fuse to a diploid zygote, holding chromosome number constant; diploid gametes would double it each generation.",
  "related": ["Purpose", "Fertilisation"]},

 {"topic": "Fertilisation", "difficulty": "easy",
  "question": "In terms of ploidy, fertilisation is:",
  "options": ["A. n + n → 2n", "B. 2n + 2n → 4n", "C. 2n + n → 3n", "D. n + n → n"],
  "correct_answer": "A",
  "explanation": "Two haploid (n) gametes fuse to form one diploid (2n) zygote.",
  "related": ["Fertilisation", "Purpose"]},

 {"topic": "Location", "difficulty": "medium",
  "question": "Meiosis takes place only in:",
  "options": ["A. germ cells of the ovaries and testes",
              "B. somatic cells throughout the body",
              "C. red blood cells within the bone marrow",
              "D. skin cells during wound repair"],
  "correct_answer": "A",
  "explanation": "Meiosis is confined to germ cells during gametogenesis; somatic cells everywhere else divide by mitosis.",
  "related": ["Location", "Gamete"]},

 {"topic": "Meiosis vs mitosis", "difficulty": "medium",
  "question": "Compared with mitosis, meiosis produces:",
  "options": ["A. four haploid cells from two divisions",
              "B. two diploid cells from one division",
              "C. two haploid cells from one division",
              "D. four diploid cells from two divisions"],
  "correct_answer": "A",
  "explanation": "Two meiotic divisions give up to four haploid cells; mitosis's single division gives two diploid cells.",
  "related": ["Meiosis vs mitosis", "Replication"]},

 {"topic": "Replication", "difficulty": "medium",
  "question": "Across the whole of meiosis, DNA is replicated:",
  "options": ["A. once, before meiosis I",
              "B. once between meiosis I and II",
              "C. twice, before each division",
              "D. never, since cells start diploid"],
  "correct_answer": "A",
  "explanation": "A single S-phase precedes meiosis I with none between the two divisions — two divisions on one replication.",
  "related": ["Replication", "Meiosis vs mitosis"]},

 {"topic": "Unique to meiosis", "difficulty": "hard",
  "question": "Which event happens in meiosis but never in mitosis?",
  "options": ["A. homologous chromosomes pairing together",
              "B. sister chromatids being separated",
              "C. the nuclear envelope breaking down",
              "D. the spindle attaching to chromosomes"],
  "correct_answer": "A",
  "explanation": "Homologue pairing (synapsis) in prophase I is unique to meiosis; the other events occur in both processes.",
  "related": ["Unique to meiosis", "Synapsis"]},

 {"topic": "Meiosis I", "difficulty": "easy",
  "question": "Meiosis I separates:",
  "options": ["A. homologous chromosomes", "B. sister chromatids",
              "C. individual DNA bases", "D. the two centrioles"],
  "correct_answer": "A",
  "explanation": "Meiosis I is reductional — homologues part while sister chromatids stay joined until meiosis II.",
  "related": ["Meiosis I", "Meiosis II"]},

 {"topic": "Meiosis II", "difficulty": "easy",
  "question": "Meiosis II separates:",
  "options": ["A. sister chromatids", "B. homologous chromosomes",
              "C. whole bivalents", "D. paired centromeres only"],
  "correct_answer": "A",
  "explanation": "Meiosis II resembles mitosis — sister chromatids separate, giving four haploid cells with single chromosomes.",
  "related": ["Meiosis II", "Meiosis I"]},

 {"topic": "Anaphase", "difficulty": "hard",
  "question": "Which statement about meiotic anaphase is correct?",
  "options": ["A. anaphase I parts homologues; anaphase II parts sisters",
              "B. anaphase I parts sisters; anaphase II parts homologues",
              "C. both anaphases separate only the sister chromatids",
              "D. both anaphases separate only the homologous pairs"],
  "correct_answer": "A",
  "explanation": "Anaphase I pulls homologues apart with sisters still joined; anaphase II then pulls the sister chromatids apart.",
  "related": ["Anaphase", "Meiosis I"]},

 {"topic": "After meiosis I", "difficulty": "medium",
  "question": "The cells produced at the end of meiosis I are:",
  "options": ["A. haploid, with chromosomes of two chromatids",
              "B. diploid, with chromosomes of two chromatids",
              "C. haploid, with single-chromatid chromosomes",
              "D. diploid, with single-chromatid chromosomes"],
  "correct_answer": "A",
  "explanation": "Meiosis I halves the chromosome number but each chromosome still carries two sister chromatids until meiosis II.",
  "related": ["After meiosis I", "Meiosis II"]},

 {"topic": "Meiosis II", "difficulty": "medium",
  "question": "Meiosis II is said to resemble mitosis because it:",
  "options": ["A. separates the sister chromatids of each chromosome",
              "B. pairs homologues before they separate",
              "C. replicates the DNA one more time first",
              "D. doubles the chromosome number again"],
  "correct_answer": "A",
  "explanation": "Like mitosis, meiosis II separates sister chromatids — but from a haploid cell with no preceding replication.",
  "related": ["Meiosis II", "Meiosis vs mitosis"]},

 {"topic": "Crossing over", "difficulty": "easy",
  "question": "Crossing over takes place during:",
  "options": ["A. prophase I", "B. metaphase II", "C. anaphase I", "D. telophase II"],
  "correct_answer": "A",
  "explanation": "Homologues pair and exchange segments during prophase I.",
  "related": ["Crossing over", "Prophase I"]},

 {"topic": "Crossing over", "difficulty": "medium",
  "question": "Crossing over exchanges DNA between:",
  "options": ["A. non-sister chromatids of paired homologues",
              "B. the two sister chromatids of one chromosome",
              "C. two entirely unrelated chromosomes",
              "D. the two arms of a single chromatid"],
  "correct_answer": "A",
  "explanation": "Recombination swaps segments between non-sister chromatids of the paired homologues, mixing maternal and paternal alleles.",
  "related": ["Crossing over", "Chiasmata"]},

 {"topic": "Prophase I", "difficulty": "hard",
  "question": "During which substage of prophase I does crossing over occur?",
  "options": ["A. pachytene", "B. leptotene", "C. zygotene", "D. diplotene"],
  "correct_answer": "A",
  "explanation": "Homologues condense (leptotene), pair (zygotene), cross over (pachytene), then show chiasmata (diplotene).",
  "related": ["Prophase I", "Crossing over"]},

 {"topic": "Chiasmata", "difficulty": "medium",
  "question": "Chiasmata are:",
  "options": ["A. the visible crossover points between homologues",
              "B. the spindle fibres that pull chromatids",
              "C. the centromeres joining sister chromatids",
              "D. the caps protecting each chromosome end"],
  "correct_answer": "A",
  "explanation": "Chiasmata are the crossover points seen once the synaptonemal complex dissolves; they tether homologues for correct segregation.",
  "related": ["Chiasmata", "Crossing over"]},

 {"topic": "Independent assortment", "difficulty": "medium",
  "question": "Independent assortment of homologous pairs occurs at:",
  "options": ["A. metaphase I", "B. metaphase II", "C. anaphase II", "D. prophase II"],
  "correct_answer": "A",
  "explanation": "At metaphase I the homologue pairs line up in random orientation, so each gamete inherits a random mix.",
  "related": ["Independent assortment", "Variation"]},

 {"topic": "Third source", "difficulty": "hard",
  "question": "Random assortment in meiosis II adds variation because the sister chromatids are now:",
  "options": ["A. no longer identical, owing to crossing over",
              "B. identical copies of one another still",
              "C. fused permanently at the centromere",
              "D. reduced to a single DNA strand each"],
  "correct_answer": "A",
  "explanation": "Crossing over in prophase I made the sisters non-identical, so their random orientation in meiosis II reshuffles alleles again.",
  "related": ["Third source", "Crossing over"]},

 {"topic": "Synapsis", "difficulty": "medium",
  "question": "Synapsis refers to:",
  "options": ["A. the pairing of homologous chromosomes",
              "B. the splitting of sister chromatids",
              "C. the breakdown of the nuclear envelope",
              "D. the copying of DNA in S phase"],
  "correct_answer": "A",
  "explanation": "Synapsis is the close pairing of homologues into a bivalent in prophase I, enabling crossing over.",
  "related": ["Synapsis", "Prophase I"]},

 {"topic": "Assortment maths", "difficulty": "hard",
  "question": "For 23 chromosome pairs, independent assortment alone yields how many gamete combinations?",
  "options": ["A. 2^23", "B. 23^2", "C. 23 × 2", "D. 46^2"],
  "correct_answer": "A",
  "explanation": "Each of the 23 pairs orients two independent ways, giving 2^23 (~8 million) combinations before crossing over adds more.",
  "related": ["Assortment maths", "Independent assortment"]},

 {"topic": "Non-disjunction", "difficulty": "medium",
  "question": "Non-disjunction is:",
  "options": ["A. failure of chromosomes to separate properly",
              "B. exchange of DNA between homologues",
              "C. random alignment on the metaphase plate",
              "D. normal halving of the chromosome number"],
  "correct_answer": "A",
  "explanation": "Non-disjunction is failed separation — of homologues in meiosis I or sister chromatids in meiosis II.",
  "related": ["Non-disjunction", "Aneuploidy"]},

 {"topic": "Non-disjunction", "difficulty": "hard",
  "question": "Non-disjunction during meiosis I specifically means that:",
  "options": ["A. homologous chromosomes fail to separate",
              "B. sister chromatids fail to separate",
              "C. the DNA fails to replicate at all",
              "D. the spindle fails to form entirely"],
  "correct_answer": "A",
  "explanation": "In meiosis I the failure is of homologues to separate; a meiosis-II failure instead involves the sister chromatids.",
  "related": ["Non-disjunction", "Aneuploidy"]},

 {"topic": "Aneuploidy", "difficulty": "medium",
  "question": "Non-disjunction produces gametes that:",
  "options": ["A. have an extra or missing chromosome",
              "B. carry exactly the normal chromosome set",
              "C. contain double the usual DNA amount",
              "D. lack any centromeres at all"],
  "correct_answer": "A",
  "explanation": "A gamete gains or loses a chromosome, so the resulting individual is aneuploid — a wrong chromosome number.",
  "related": ["Aneuploidy", "Non-disjunction"]},

 {"topic": "Trisomy 21", "difficulty": "easy",
  "question": "Three copies of chromosome 21 cause:",
  "options": ["A. Down syndrome", "B. Turner syndrome",
              "C. Klinefelter syndrome", "D. Marfan syndrome"],
  "correct_answer": "A",
  "explanation": "Trisomy 21 (47,+21) is Down syndrome — the commonest autosomal aneuploidy.",
  "related": ["Trisomy 21", "Aneuploidy"]},

 {"topic": "Turner syndrome", "difficulty": "medium",
  "question": "The karyotype of Turner syndrome is:",
  "options": ["A. 45,X", "B. 47,XXY", "C. 47,+21", "D. 46,XY"],
  "correct_answer": "A",
  "explanation": "Turner syndrome is a single X — 45,X, i.e. 45 chromosomes instead of 46.",
  "related": ["Turner syndrome", "Aneuploidy"]},

 {"topic": "Klinefelter", "difficulty": "medium",
  "question": "Klinefelter syndrome has the karyotype:",
  "options": ["A. 47,XXY", "B. 45,X", "C. 47,+21", "D. 46,XX"],
  "correct_answer": "A",
  "explanation": "Klinefelter syndrome is an extra X in a male — 47,XXY.",
  "related": ["Klinefelter", "Aneuploidy"]},

 {"topic": "Chiasmata & errors", "difficulty": "hard",
  "question": "Failure to form chiasmata can cause non-disjunction because chiasmata normally:",
  "options": ["A. hold homologues aligned for correct segregation",
              "B. copy the DNA before the first division",
              "C. dissolve the nuclear envelope at prophase",
              "D. attach the spindle to each telomere"],
  "correct_answer": "A",
  "explanation": "Chiasmata physically tether paired homologues in correct orientation until anaphase I; without them a pair may missegregate.",
  "related": ["Chiasmata & errors", "Non-disjunction"]},

 {"topic": "Maternal age", "difficulty": "hard",
  "question": "Trisomy 21 risk rises with maternal age chiefly because of:",
  "options": ["A. errors in the long-arrested oocyte's meiosis I",
              "B. faster oocyte division in older women",
              "C. extra rounds of DNA replication with age",
              "D. loss of all telomeres from the oocyte"],
  "correct_answer": "A",
  "explanation": "Oocytes stay arrested in meiosis I for years; the longer arrest raises the chance of meiosis-I non-disjunction with age.",
  "related": ["Maternal age", "Non-disjunction"]},

 {"topic": "Gamete", "difficulty": "medium",
  "question": "A gamete is:",
  "options": ["A. a haploid reproductive cell",
              "B. a diploid somatic cell",
              "C. a fertilised diploid zygote",
              "D. a resting germ-line stem cell"],
  "correct_answer": "A",
  "explanation": "Gametes are the haploid products of meiosis — sperm or ova — that fuse at fertilisation.",
  "related": ["Gamete", "Purpose"]},

 {"topic": "Gametogenesis", "difficulty": "medium",
  "question": "The formation of sperm cells is specifically called:",
  "options": ["A. spermatogenesis", "B. oogenesis", "C. fertilisation", "D. synapsis"],
  "correct_answer": "A",
  "explanation": "Spermatogenesis makes sperm; oogenesis makes ova — both are forms of gametogenesis by meiosis.",
  "related": ["Gametogenesis", "Gamete"]},

 {"topic": "Bivalent", "difficulty": "hard",
  "question": "The four-chromatid structure formed when homologues pair in prophase I is a:",
  "options": ["A. bivalent, or tetrad",
              "B. single sister chromatid",
              "C. lone unpaired chromosome",
              "D. fully condensed karyotype"],
  "correct_answer": "A",
  "explanation": "Two paired homologues, each of two chromatids, form a four-strand bivalent (tetrad) where crossing over occurs.",
  "related": ["Bivalent", "Synapsis"]},
]

if __name__ == "__main__":
    sys.exit(emit(KEY, META, Q))
