#!/usr/bin/env python3
"""MHHS2401 W4 · Muscle Physiology II (tension & performance) — regenerated bank (length-matched, no bracket tells, no daredevil)."""
import os, sys, json
HERE = os.path.dirname(os.path.abspath(__file__))
sys.path.insert(0, os.path.join(HERE, "..", "tools"))
from qbank_lib import emit  # noqa

KEY = "muscle_physiology_2_mhhs2401.html"
BANK = json.load(open(os.path.join(HERE, "..", "..", "guide_quizzes.json"), encoding="utf-8"))
META = {k: BANK[KEY][k] for k in ("title", "subject", "unit", "content")}

Q = [
 # ── easy ──────────────────────────────────────────────────────────────
 {"topic": "Energy systems", "difficulty": "easy",
  "question": "Which energy system yields the most ATP per glucose molecule?",
  "options": ["A. aerobic respiration", "B. anaerobic glycolysis",
              "C. the phosphagen system", "D. creatine phosphate"],
  "correct_answer": "A",
  "explanation": "Aerobic respiration makes about 32 ATP per glucose in the mitochondria, far more than glycolysis or the phosphagen system.",
  "related": ["Energy systems", "Aerobic respiration"]},

 {"topic": "Fibre types", "difficulty": "easy",
  "question": "Which fibre type is slow, red and best suited to endurance?",
  "options": ["A. type I", "B. type IIa",
              "C. type IIb", "D. type III"],
  "correct_answer": "A",
  "explanation": "Type I slow oxidative fibres are red, rich in mitochondria and myoglobin, and fatigue-resistant, ideal for endurance and posture.",
  "related": ["Fibre types", "Aerobic respiration"]},

 {"topic": "Contraction types", "difficulty": "easy",
  "question": "An isometric contraction is one in which the muscle:",
  "options": ["A. holds a constant length", "B. shortens against a load",
              "C. lengthens under control", "D. changes tension only"],
  "correct_answer": "A",
  "explanation": "Isometric means same length: the muscle holds an object without moving, whereas isotonic contractions keep tension constant while moving.",
  "related": ["Contraction types", "Muscle tension"]},

 {"topic": "Motor unit", "difficulty": "easy",
  "question": "A motor unit consists of one motor neuron and:",
  "options": ["A. all its muscle fibres", "B. one single muscle fibre",
              "C. the whole muscle organ", "D. one entire fascicle"],
  "correct_answer": "A",
  "explanation": "A motor unit is a single motor neuron plus all the muscle fibres its axon branches innervate; they contract together.",
  "related": ["Motor unit", "Stimulation"]},

 {"topic": "Duchenne muscular dystrophy", "difficulty": "easy",
  "question": "Duchenne muscular dystrophy is caused by the absence of which protein?",
  "options": ["A. dystrophin", "B. titin",
              "C. nebulin", "D. troponin"],
  "correct_answer": "A",
  "explanation": "DMD results from a deleted dystrophin gene, so the fibre lacks the lateral anchor and the sarcolemma becomes fragile.",
  "related": ["Duchenne muscular dystrophy", "Structural proteins"]},

 # ── medium ────────────────────────────────────────────────────────────
 {"topic": "Phosphagen system", "difficulty": "medium",
  "question": "The phosphagen system regenerates ATP rapidly using which stored molecule?",
  "options": ["A. phosphocreatine", "B. muscle glycogen",
              "C. free fatty acids", "D. blood glucose"],
  "correct_answer": "A",
  "explanation": "Creatine kinase strips phosphate from phosphocreatine to regenerate ATP almost instantly, bridging the first seconds of effort.",
  "related": ["Phosphagen system", "Energy systems"]},

 {"topic": "Anaerobic glycolysis", "difficulty": "medium",
  "question": "Anaerobic glycolysis produces how many ATP per glucose, plus pyruvate?",
  "options": ["A. two ATP", "B. one ATP",
              "C. sixteen ATP", "D. thirty-two ATP"],
  "correct_answer": "A",
  "explanation": "Anaerobic glycolysis yields 2 ATP plus pyruvate in the cytoplasm; without oxygen the excess pyruvate becomes lactic acid.",
  "related": ["Anaerobic glycolysis", "Energy systems"]},

 {"topic": "ATPases", "difficulty": "medium",
  "question": "Which ATPase spends ATP to pump calcium back into the sarcoplasmic reticulum?",
  "options": ["A. the calcium ATPase", "B. the myosin ATPase",
              "C. the sodium-potassium ATPase", "D. the proton ATPase"],
  "correct_answer": "A",
  "explanation": "The calcium ATPase pumps calcium back into the SR to end contraction, showing relaxation itself costs ATP.",
  "related": ["ATPases", "Relaxation"]},

 {"topic": "Energy timeline", "difficulty": "medium",
  "question": "Which energy system dominates a maximal effort lasting only a few seconds?",
  "options": ["A. the phosphagen system", "B. aerobic respiration",
              "C. fatty acid oxidation", "D. oxidative phosphorylation"],
  "correct_answer": "A",
  "explanation": "The phosphagen system delivers ATP fastest but for only about 15 seconds, so it dominates brief maximal efforts like a sprint.",
  "related": ["Energy timeline", "Phosphagen system"]},

 {"topic": "Muscle tension", "difficulty": "medium",
  "question": "Sarcomere length affects tension because it determines the amount of:",
  "options": ["A. filament overlap", "B. calcium storage",
              "C. glycogen fuel", "D. myoglobin present"],
  "correct_answer": "A",
  "explanation": "Filament overlap sets how many cross-bridges can form, so tension peaks at the optimal resting length of about 2.0 to 2.3 micrometres.",
  "related": ["Muscle tension", "Length-tension"]},

 {"topic": "Length-tension", "difficulty": "medium",
  "question": "Maximum tension is generated when a sarcomere is at which length?",
  "options": ["A. its optimal resting length", "B. its shortest possible length",
              "C. its longest stretched length", "D. any length at all"],
  "correct_answer": "A",
  "explanation": "At the optimal resting length, thin and thick filament overlap allows the most cross-bridges and therefore the greatest tension.",
  "related": ["Length-tension", "Muscle tension"]},

 {"topic": "Structural proteins", "difficulty": "medium",
  "question": "Which structural protein acts as a molecular spring from the Z disc to the M-line?",
  "options": ["A. titin", "B. nebulin",
              "C. dystrophin", "D. laminin"],
  "correct_answer": "A",
  "explanation": "Titin runs from Z disc to M-line, stabilising myosin and providing elasticity that recentres the sarcomere.",
  "related": ["Structural proteins", "Sarcomere"]},

 {"topic": "Structural proteins", "difficulty": "medium",
  "question": "Which structural protein aligns and stabilises the thin actin filament?",
  "options": ["A. nebulin", "B. titin",
              "C. dystrophin", "D. myosin"],
  "correct_answer": "A",
  "explanation": "Nebulin spans the Z disc along actin, aligning and stabilising the thin filament; titin does this job for myosin.",
  "related": ["Structural proteins", "Sarcomere"]},

 {"topic": "Twitch summation", "difficulty": "medium",
  "question": "Wave summation increases tension because the fibre is stimulated again before it can:",
  "options": ["A. fully relax", "B. depolarise again",
              "C. store calcium", "D. make more ATP"],
  "correct_answer": "A",
  "explanation": "When stimuli arrive before full relaxation, cytoplasmic calcium stacks up and successive twitches partially add, raising tension.",
  "related": ["Twitch summation", "Stimulation"]},

 {"topic": "Tetanus", "difficulty": "medium",
  "question": "Complete tetanus is best described as:",
  "options": ["A. smooth maximal tension", "B. widely spaced twitches",
              "C. a bumpy relaxing plateau", "D. a single brief twitch"],
  "correct_answer": "A",
  "explanation": "In complete tetanus, twitches fully fuse into a smooth steady maximum because calcium never falls between rapid stimuli.",
  "related": ["Tetanus", "Stimulation"]},

 {"topic": "Contraction types", "difficulty": "medium",
  "question": "Lowering a weight slowly under control is which kind of contraction?",
  "options": ["A. eccentric isotonic", "B. concentric isotonic",
              "C. an isometric hold", "D. a resting twitch"],
  "correct_answer": "A",
  "explanation": "An eccentric isotonic contraction lengthens the muscle under control at constant tension, as when lowering a load.",
  "related": ["Contraction types", "Muscle tension"]},

 {"topic": "Muscle tone", "difficulty": "medium",
  "question": "Muscle tone is best defined as:",
  "options": ["A. muscle tension at rest", "B. maximum voluntary force",
              "C. the speed of shortening", "D. total glycogen stored"],
  "correct_answer": "A",
  "explanation": "Muscle tone is resting muscle tension from low-frequency twitches, keeping you upright and balanced.",
  "related": ["Muscle tone", "Stimulation"]},

 {"topic": "Fibre types", "difficulty": "medium",
  "question": "Type IIb fast glycolytic fibres are characterised by:",
  "options": ["A. high glycogen and few mitochondria", "B. high myoglobin and many mitochondria",
              "C. slow speed and red colour", "D. strong fatigue resistance"],
  "correct_answer": "A",
  "explanation": "Type IIb fibres run on anaerobic glycolysis, so they hoard glycogen but have few mitochondria and capillaries, are pale and fatigue fast.",
  "related": ["Fibre types", "Anaerobic glycolysis"]},

 # ── hard ──────────────────────────────────────────────────────────────
 {"topic": "Oxygen debt", "difficulty": "hard",
  "question": "The alactacid part of recovery uses aerobic ATP mainly to:",
  "options": ["A. restore phosphocreatine and myoglobin", "B. convert lactate back to glucose",
              "C. build new muscle myofibrils", "D. remove all carbon dioxide"],
  "correct_answer": "A",
  "explanation": "The alactacid component restores phosphocreatine and refills muscle oxygen stores in myoglobin; the lactacid component clears lactate.",
  "related": ["Oxygen debt", "Fatigue"]},

 {"topic": "Fatigue", "difficulty": "hard",
  "question": "Accumulation theories of muscle fatigue attribute it to a build-up of lactate and a fall in:",
  "options": ["A. pH", "B. calcium",
              "C. glycogen", "D. temperature"],
  "correct_answer": "A",
  "explanation": "Accumulation theories say rising lactate lowers pH, impairing enzymes like the ATPases and calcium binding to troponin.",
  "related": ["Fatigue", "Energy systems"]},

 {"topic": "Aerobic respiration", "difficulty": "hard",
  "question": "The oxygen for aerobic respiration in muscle is stored locally by which molecule?",
  "options": ["A. myoglobin", "B. haemoglobin",
              "C. creatine kinase", "D. glycogen"],
  "correct_answer": "A",
  "explanation": "Myoglobin stores oxygen within the muscle, while haemoglobin delivers oxygen from the blood; both feed aerobic respiration.",
  "related": ["Aerobic respiration", "Fibre types"]},

 {"topic": "Duchenne muscular dystrophy", "difficulty": "hard",
  "question": "Duchenne muscular dystrophy follows which pattern of inheritance?",
  "options": ["A. X-linked recessive", "B. autosomal dominant",
              "C. autosomal recessive", "D. mitochondrial maternal"],
  "correct_answer": "A",
  "explanation": "DMD is X-linked recessive, affecting roughly 1 in 5000 male births, and also weakens the diaphragm and heart.",
  "related": ["Duchenne muscular dystrophy", "Structural proteins"]},

 {"topic": "Dystrophin complex", "difficulty": "hard",
  "question": "Dystrophin transfers force laterally by linking internal actin out to which matrix protein?",
  "options": ["A. laminin", "B. troponin",
              "C. myoglobin", "D. tropomyosin"],
  "correct_answer": "A",
  "explanation": "Dystrophin links the internal actin cytoskeleton through membrane proteins out to laminin in the extracellular matrix.",
  "related": ["Dystrophin complex", "Structural proteins"]},

 {"topic": "Isometric contraction", "difficulty": "hard",
  "question": "During an isometric contraction, overall muscle length stays constant because:",
  "options": ["A. elastic elements stretch to compensate", "B. no cross-bridges form at all",
              "C. calcium is never released", "D. the sarcomeres cannot shorten"],
  "correct_answer": "A",
  "explanation": "Sarcomeres do shorten as cross-bridges cycle, but elastic elements such as titin stretch by the same amount, so total length is unchanged.",
  "related": ["Isometric contraction", "Structural proteins"]},

 {"topic": "Motor neuron disease", "difficulty": "hard",
  "question": "Amyotrophic lateral sclerosis, the commonest motor neuron disease, affects:",
  "options": ["A. both upper and lower neurons", "B. only the lower motor neurons",
              "C. only the upper motor neurons", "D. only the muscle receptors"],
  "correct_answer": "A",
  "explanation": "ALS degenerates both upper and lower motor neurons, causing atrophy, weakness and impaired respiration and speech.",
  "related": ["Motor neuron disease", "Muscle tone"]},

 {"topic": "Hypertrophy", "difficulty": "hard",
  "question": "Muscle hypertrophy from training reflects an increase in:",
  "options": ["A. myofibrils per fibre", "B. the number of fibres",
              "C. the number of neurons", "D. the number of sarcomeres only"],
  "correct_answer": "A",
  "explanation": "Hypertrophy means more myofibrils within each fibre, not more fibres, along with more phosphocreatine, glycogen and mitochondria.",
  "related": ["Hypertrophy", "Performance"]},

 {"topic": "Fibre recruitment", "difficulty": "hard",
  "question": "In what order are the fibre types typically recruited as force demand rises?",
  "options": ["A. type I, then IIa, then IIb", "B. type IIb, then IIa, then I",
              "C. type IIa, then I, then IIb", "D. type IIb, then I, then IIa"],
  "correct_answer": "A",
  "explanation": "Fatigue-resistant type I fibres are recruited first, then type IIa, and finally the powerful fatigable type IIb fibres.",
  "related": ["Fibre recruitment", "Fibre types"]},

 {"topic": "Nature versus nurture", "difficulty": "hard",
  "question": "About how much can training shift a person's relative proportion of fibre types?",
  "options": ["A. around 10 percent", "B. around 50 percent",
              "C. around 90 percent", "D. none at all"],
  "correct_answer": "A",
  "explanation": "Fibre proportion is mostly genetic, but training can shift it by roughly 10 percent and also increase fibre diameter.",
  "related": ["Nature versus nurture", "Fibre types"]},
]

if __name__ == "__main__":
    sys.exit(emit(KEY, META, Q))
