#!/usr/bin/env python3
"""MHHS2401 W3 · Muscle Physiology I (excitation & contraction) — regenerated bank (length-matched, no bracket tells, no daredevil)."""
import os, sys, json
HERE = os.path.dirname(os.path.abspath(__file__))
sys.path.insert(0, os.path.join(HERE, "..", "tools"))
from qbank_lib import emit  # noqa

KEY = "muscle_physiology_1_mhhs2401.html"
BANK = json.load(open(os.path.join(HERE, "..", "..", "guide_quizzes.json"), encoding="utf-8"))
META = {k: BANK[KEY][k] for k in ("title", "subject", "unit", "content")}

Q = [
 # ── easy ──────────────────────────────────────────────────────────────
 {"topic": "Muscle types", "difficulty": "easy",
  "question": "Skeletal muscle is best described as:",
  "options": ["A. striated and voluntary", "B. smooth and voluntary",
              "C. striated and involuntary", "D. smooth and involuntary"],
  "correct_answer": "A",
  "explanation": "Skeletal muscle is striated, multinucleate and under voluntary control, unlike involuntary cardiac and smooth muscle.",
  "related": ["Muscle types", "Skeletal muscle"]},

 {"topic": "Sarcomere", "difficulty": "easy",
  "question": "The contractile unit of a myofibril, running from Z disc to Z disc, is the:",
  "options": ["A. sarcomere", "B. fascicle",
              "C. myofibril", "D. endomysium"],
  "correct_answer": "A",
  "explanation": "The sarcomere is the contractile unit, running Z disc to Z disc; sarcomeres sit in series along each myofibril.",
  "related": ["Sarcomere", "Muscle structure"]},

 {"topic": "Neuromuscular junction", "difficulty": "easy",
  "question": "Which neurotransmitter carries the signal across the neuromuscular junction?",
  "options": ["A. acetylcholine", "B. noradrenaline",
              "C. dopamine", "D. glutamate"],
  "correct_answer": "A",
  "explanation": "Somatic motor neurons release acetylcholine at the neuromuscular junction, and its effect on skeletal muscle is always excitatory.",
  "related": ["Neuromuscular junction", "Neural control"]},

 {"topic": "Sarcoplasmic reticulum", "difficulty": "easy",
  "question": "Which structure inside the muscle fibre stores calcium?",
  "options": ["A. the sarcoplasmic reticulum", "B. the transverse tubule",
              "C. the myofibril bundle", "D. the mitochondrion"],
  "correct_answer": "A",
  "explanation": "The sarcoplasmic reticulum is modified endoplasmic reticulum wrapping each myofibril; it is the fibre's calcium store.",
  "related": ["Sarcoplasmic reticulum", "Muscle fibre"]},

 {"topic": "Contractile proteins", "difficulty": "easy",
  "question": "The thick filament of the sarcomere is made of which protein?",
  "options": ["A. myosin", "B. actin",
              "C. troponin", "D. tropomyosin"],
  "correct_answer": "A",
  "explanation": "Myosin forms the thick filament and performs the power stroke; actin forms the thin filament it pulls on.",
  "related": ["Contractile proteins", "Sarcomere"]},

 # ── medium ────────────────────────────────────────────────────────────
 {"topic": "Connective sheaths", "difficulty": "medium",
  "question": "Which connective-tissue sheath wraps an individual muscle fibre?",
  "options": ["A. the endomysium", "B. the perimysium",
              "C. the epimysium", "D. the periosteum"],
  "correct_answer": "A",
  "explanation": "Endomysium wraps each fibre, perimysium wraps each fascicle, and epimysium wraps the whole muscle; all merge into the tendon.",
  "related": ["Connective sheaths", "Muscle structure"]},

 {"topic": "Connective sheaths", "difficulty": "medium",
  "question": "Which sheath surrounds a fascicle, a bundle of muscle fibres?",
  "options": ["A. the perimysium", "B. the endomysium",
              "C. the epimysium", "D. the sarcolemma"],
  "correct_answer": "A",
  "explanation": "Perimysium wraps each fascicle and carries the larger nerves and vessels; endomysium wraps single fibres.",
  "related": ["Connective sheaths", "Muscle structure"]},

 {"topic": "T-tubules", "difficulty": "medium",
  "question": "The transverse (T) tubules of a muscle fibre function to:",
  "options": ["A. carry the action potential inward", "B. store calcium for release",
              "C. supply ATP to myosin", "D. anchor the thin filaments"],
  "correct_answer": "A",
  "explanation": "T-tubules are infoldings of the sarcolemma that carry the action potential deep into the fibre so it contracts as one.",
  "related": ["T-tubules", "Muscle fibre"]},

 {"topic": "Sarcomere bands", "difficulty": "medium",
  "question": "The I band of the sarcomere contains:",
  "options": ["A. actin only", "B. myosin only",
              "C. actin and myosin", "D. neither filament"],
  "correct_answer": "A",
  "explanation": "The I band is the light band of actin only, either side of the Z disc; the H zone is myosin only.",
  "related": ["Sarcomere bands", "Sarcomere"]},

 {"topic": "Sarcomere bands", "difficulty": "medium",
  "question": "The Z disc of the sarcomere serves to anchor which filament?",
  "options": ["A. actin", "B. myosin",
              "C. titin", "D. tropomyosin"],
  "correct_answer": "A",
  "explanation": "The Z disc anchors actin and marks the sarcomere edge; the M line at the middle anchors myosin.",
  "related": ["Sarcomere bands", "Sarcomere"]},

 {"topic": "Regulatory proteins", "difficulty": "medium",
  "question": "At rest, the myosin-binding sites on actin are physically blocked by:",
  "options": ["A. tropomyosin", "B. troponin",
              "C. myosin heads", "D. calcium ions"],
  "correct_answer": "A",
  "explanation": "Tropomyosin lies over actin's binding sites as a safety catch; troponin pulls it aside when calcium binds.",
  "related": ["Regulatory proteins", "Sarcomere"]},

 {"topic": "nAChR", "difficulty": "medium",
  "question": "The nicotinic ACh receptor at the motor end plate is a:",
  "options": ["A. ligand-gated ion channel", "B. voltage-gated ion channel",
              "C. G-protein-coupled receptor", "D. mechanically gated channel"],
  "correct_answer": "A",
  "explanation": "The nicotinic ACh receptor is a ligand-gated ion channel: it opens when ACh binds, not in response to voltage.",
  "related": ["nAChR", "Neuromuscular junction"]},

 {"topic": "End-plate potential", "difficulty": "medium",
  "question": "The nAChR passes both sodium and potassium, but the end plate depolarises because:",
  "options": ["A. sodium influx exceeds potassium efflux", "B. potassium efflux exceeds sodium influx",
              "C. only sodium can cross it", "D. only potassium can cross it"],
  "correct_answer": "A",
  "explanation": "The channel is non-specific, but sodium influx exceeds potassium efflux, so the net inward current depolarises the end plate.",
  "related": ["End-plate potential", "nAChR"]},

 {"topic": "Neurotoxins", "difficulty": "medium",
  "question": "Botulinum toxin causes flaccid paralysis by:",
  "options": ["A. blocking ACh release", "B. blocking inhibitory CNS interneurons",
              "C. destroying the ACh receptors", "D. activating the ACh receptors"],
  "correct_answer": "A",
  "explanation": "Botulinum toxin inhibits ACh release from the axon terminal, so there is no depolarisation and the muscle goes flaccid.",
  "related": ["Neurotoxins", "Neuromuscular junction"]},

 {"topic": "Neurotoxins", "difficulty": "medium",
  "question": "Tetanus toxin produces spastic paralysis because it:",
  "options": ["A. blocks inhibitory CNS interneurons", "B. blocks ACh release from axons",
              "C. destroys the muscle receptors", "D. pumps calcium into the SR"],
  "correct_answer": "A",
  "explanation": "Tetanus toxin inhibits inhibitory interneurons in the CNS, causing disinhibition so motor neurons fire unchecked and muscles go rigid.",
  "related": ["Neurotoxins", "Neuromuscular junction"]},

 {"topic": "Myasthenia gravis", "difficulty": "medium",
  "question": "Myasthenia gravis is caused by autoimmune destruction of the:",
  "options": ["A. ACh receptors", "B. calcium channels",
              "C. sodium channels", "D. myosin filaments"],
  "correct_answer": "A",
  "explanation": "In myasthenia gravis, antibodies destroy the nicotinic ACh receptors, so the muscle responds less to ACh and contraction weakens.",
  "related": ["Myasthenia gravis", "nAChR"]},

 {"topic": "Sliding filaments", "difficulty": "medium",
  "question": "During contraction, the A band of the sarcomere:",
  "options": ["A. stays unchanged", "B. narrows noticeably",
              "C. widens noticeably", "D. disappears entirely"],
  "correct_answer": "A",
  "explanation": "The A band is unchanged because myosin length is fixed; the I band and H zone narrow as filaments slide together.",
  "related": ["Sliding filaments", "Sarcomere bands"]},

 {"topic": "E-C coupling", "difficulty": "medium",
  "question": "In excitation-contraction coupling, calcium is released from the SR into the:",
  "options": ["A. sarcoplasm", "B. synaptic cleft",
              "C. T-tubule lumen", "D. extracellular fluid"],
  "correct_answer": "A",
  "explanation": "When the RyR opens, calcium floods out of the SR store into the sarcoplasm, the trigger for the cross-bridge cycle.",
  "related": ["E-C coupling", "Sarcoplasmic reticulum"]},

 {"topic": "Muscle types", "difficulty": "medium",
  "question": "Which feature is unique to cardiac muscle among the three muscle types?",
  "options": ["A. intercalated discs", "B. a single nucleus",
              "C. voluntary control", "D. absence of striations"],
  "correct_answer": "A",
  "explanation": "Cardiac muscle is striated, branched and involuntary and is joined by intercalated discs found only in the heart.",
  "related": ["Muscle types", "Cardiac muscle"]},

 # ── hard ──────────────────────────────────────────────────────────────
 {"topic": "E-C coupling", "difficulty": "hard",
  "question": "In the T-tubule, the voltage sensor that mechanically opens the SR calcium channel is the:",
  "options": ["A. DHP receptor", "B. ryanodine receptor",
              "C. nicotinic receptor", "D. calcium ATPase"],
  "correct_answer": "A",
  "explanation": "The DHP receptor in the T-tubule senses voltage and physically tugs open the ryanodine receptor on the SR to release calcium.",
  "related": ["E-C coupling", "T-tubules"]},

 {"topic": "Cross-bridge cycle", "difficulty": "hard",
  "question": "In the cross-bridge cycle, the power stroke that pulls actin is triggered by release of:",
  "options": ["A. inorganic phosphate", "B. calcium ions",
              "C. acetylcholine", "D. potassium ions"],
  "correct_answer": "A",
  "explanation": "After myosin binds actin, release of inorganic phosphate (Pi) triggers the power stroke that pivots myosin and pulls actin.",
  "related": ["Cross-bridge cycle", "Contraction"]},

 {"topic": "Cross-bridge cycle", "difficulty": "hard",
  "question": "When calcium binds troponin, the immediate effect on the thin filament is to:",
  "options": ["A. pull tropomyosin off the sites", "B. split ATP on the myosin head",
              "C. detach myosin from actin", "D. pump calcium back into the SR"],
  "correct_answer": "A",
  "explanation": "Calcium binding troponin changes its shape and pulls tropomyosin aside, exposing actin's myosin-binding sites.",
  "related": ["Cross-bridge cycle", "Regulatory proteins"]},

 {"topic": "Relaxation", "difficulty": "hard",
  "question": "What breaks the myosin-actin cross-bridge to allow relaxation?",
  "options": ["A. fresh ATP binding myosin", "B. inorganic phosphate release",
              "C. calcium binding to troponin", "D. an action potential arriving"],
  "correct_answer": "A",
  "explanation": "A fresh ATP binding to myosin detaches it from actin; without ATP the muscle stays locked, as in rigor mortis.",
  "related": ["Relaxation", "Cross-bridge cycle"]},

 {"topic": "Relaxation", "difficulty": "hard",
  "question": "Calcium is returned to the SR during relaxation by which mechanism?",
  "options": ["A. an active ATPase pump", "B. simple passive diffusion",
              "C. the ryanodine receptor", "D. the DHP voltage sensor"],
  "correct_answer": "A",
  "explanation": "The SR calcium ATPase (SERCA) actively pumps calcium back into the store against its gradient, using ATP.",
  "related": ["Relaxation", "Sarcoplasmic reticulum"]},

 {"topic": "Rigor mortis", "difficulty": "hard",
  "question": "Rigor mortis occurs after death because there is no ATP to:",
  "options": ["A. detach myosin from actin", "B. trigger the power stroke",
              "C. release calcium from the SR", "D. depolarise the end plate"],
  "correct_answer": "A",
  "explanation": "At death the SR leaks calcium so cross-bridges keep forming, but no ATP is made to detach myosin, so muscle locks stiff.",
  "related": ["Rigor mortis", "Relaxation"]},

 {"topic": "Muscle relaxants", "difficulty": "hard",
  "question": "Curariform muscle relaxants used in surgery cause paralysis by:",
  "options": ["A. blocking the nAChR", "B. activating the nAChR",
              "C. blocking ACh release", "D. destroying the nAChR"],
  "correct_answer": "A",
  "explanation": "Curariform relaxants bind and inhibit the nAChR so the muscle cannot be depolarised, giving controlled surgical paralysis.",
  "related": ["Muscle relaxants", "nAChR"]},

 {"topic": "Myasthenia gravis", "difficulty": "hard",
  "question": "Myasthenia gravis is treated with neostigmine, which works by:",
  "options": ["A. slowing ACh breakdown", "B. replacing the lost receptors",
              "C. blocking ACh release", "D. pumping calcium into the SR"],
  "correct_answer": "A",
  "explanation": "Neostigmine is an acetylcholinesterase inhibitor; by slowing ACh breakdown it leaves more ACh to find the surviving receptors.",
  "related": ["Myasthenia gravis", "Neuromuscular junction"]},

 {"topic": "ACh release", "difficulty": "hard",
  "question": "Arrival of the action potential at the axon terminal triggers ACh release by opening:",
  "options": ["A. voltage-gated calcium channels", "B. ligand-gated cation channels",
              "C. ryanodine receptor channels", "D. calcium ATPase pumps"],
  "correct_answer": "A",
  "explanation": "The action potential opens voltage-gated calcium channels in the terminal, and the calcium influx triggers ACh vesicle release.",
  "related": ["ACh release", "Neuromuscular junction"]},
]

if __name__ == "__main__":
    sys.exit(emit(KEY, META, Q))
