#!/usr/bin/env python3
"""MHHS2401 W1 · Musculoskeletal System (introduction) — regenerated bank (length-matched, no bracket tells, no daredevil)."""
import os, sys, json
HERE = os.path.dirname(os.path.abspath(__file__))
sys.path.insert(0, os.path.join(HERE, "..", "tools"))
from qbank_lib import emit  # noqa

KEY = "musculoskeletal_system_mhhs2401.html"
BANK = json.load(open(os.path.join(HERE, "..", "..", "guide_quizzes.json"), encoding="utf-8"))
META = {k: BANK[KEY][k] for k in ("title", "subject", "unit", "content")}

Q = [
 # ── easy ──────────────────────────────────────────────────────────────
 {"topic": "Skeleton divisions", "difficulty": "easy",
  "question": "How many bones make up the adult human skeleton?",
  "options": ["A. 206", "B. 186",
              "C. 226", "D. 246"],
  "correct_answer": "A",
  "explanation": "The adult skeleton has 206 bones: 80 axial plus 126 appendicular.",
  "related": ["Skeleton divisions", "Skeletal functions"]},

 {"topic": "Bone cells", "difficulty": "easy",
  "question": "Which bone cell breaks down (resorbs) bone?",
  "options": ["A. the osteoclast", "B. the osteoblast",
              "C. the osteocyte", "D. the chondroblast"],
  "correct_answer": "A",
  "explanation": "Osteoclasts resorb bone; the suffix -clast means carve, while -blast builds and -cyte maintains.",
  "related": ["Bone cells", "Remodelling"]},

 {"topic": "Bone shapes", "difficulty": "easy",
  "question": "The femur and humerus are examples of which bone shape?",
  "options": ["A. long bones", "B. short bones",
              "C. flat bones", "D. irregular bones"],
  "correct_answer": "A",
  "explanation": "Long bones have a shaft and two ends and act as levers; the femur and humerus are classic examples.",
  "related": ["Bone shapes", "Long bone"]},

 {"topic": "Joints", "difficulty": "easy",
  "question": "Which joint type is freely movable and has a fluid-filled cavity?",
  "options": ["A. synovial", "B. fibrous",
              "C. cartilaginous", "D. sutural"],
  "correct_answer": "A",
  "explanation": "Synovial joints have a fluid-filled cavity and are the freely-movable family, such as the knee and shoulder.",
  "related": ["Joints", "Synovial joint"]},

 {"topic": "Muscle attachments", "difficulty": "easy",
  "question": "A structure that attaches a muscle to a bone is a:",
  "options": ["A. tendon", "B. ligament",
              "C. cartilage", "D. capsule"],
  "correct_answer": "A",
  "explanation": "A tendon attaches muscle to bone; a ligament joins bone to bone.",
  "related": ["Muscle attachments", "Muscle"]},

 # ── medium ────────────────────────────────────────────────────────────
 {"topic": "Skeleton divisions", "difficulty": "medium",
  "question": "Which of these belongs to the axial skeleton?",
  "options": ["A. the thoracic cage", "B. the pelvic girdle",
              "C. the humerus bone", "D. the pectoral girdle"],
  "correct_answer": "A",
  "explanation": "The axial skeleton is the skull, vertebral column, sacrum, coccyx and thoracic cage; limbs and girdles are appendicular.",
  "related": ["Skeleton divisions", "Skeletal functions"]},

 {"topic": "Osteon", "difficulty": "medium",
  "question": "In compact bone, the central (Haversian) canal of an osteon carries:",
  "options": ["A. blood vessels and nerves", "B. only synovial fluid",
              "C. yellow marrow fat", "D. mineral crystals alone"],
  "correct_answer": "A",
  "explanation": "The central canal runs up the osteon core carrying blood vessels and nerves that feed the buried osteocytes.",
  "related": ["Osteon", "Compact bone"]},

 {"topic": "Osteon", "difficulty": "medium",
  "question": "Osteocytes reside in small spaces within the bone matrix called:",
  "options": ["A. lacunae", "B. canaliculi",
              "C. lamellae", "D. trabeculae"],
  "correct_answer": "A",
  "explanation": "Osteocytes sit in lacunae; the tiny canaliculi connecting lacunae let them exchange nutrients and signals.",
  "related": ["Osteon", "Bone cells"]},

 {"topic": "Ossification", "difficulty": "medium",
  "question": "Which type of ossification forms most long bones from a cartilage model?",
  "options": ["A. endochondral ossification", "B. intramembranous ossification",
              "C. appositional deposition", "D. direct membrane ossification"],
  "correct_answer": "A",
  "explanation": "Endochondral ossification replaces a cartilage model with bone and forms most long bones; flat bones form intramembranously.",
  "related": ["Ossification", "Bone formation"]},

 {"topic": "Ossification", "difficulty": "medium",
  "question": "Flat bones such as those of the skull form by which process?",
  "options": ["A. intramembranous ossification", "B. endochondral ossification",
              "C. cartilage replacement", "D. epiphyseal growth"],
  "correct_answer": "A",
  "explanation": "Flat bones form by intramembranous ossification, where osteoblasts deposit osteoid directly with no cartilage model.",
  "related": ["Ossification", "Bone formation"]},

 {"topic": "Long bone", "difficulty": "medium",
  "question": "The shaft of a long bone is called the:",
  "options": ["A. diaphysis", "B. epiphysis",
              "C. metaphysis", "D. periosteum"],
  "correct_answer": "A",
  "explanation": "The diaphysis is the shaft, compact bone around the medullary cavity; the epiphyses are the expanded ends.",
  "related": ["Long bone", "Bone shapes"]},

 {"topic": "Long bone", "difficulty": "medium",
  "question": "Which membrane covers the outer surface of a bone and carries its nerves?",
  "options": ["A. the periosteum", "B. the endosteum",
              "C. the synovium", "D. the perichondrium"],
  "correct_answer": "A",
  "explanation": "The periosteum covers the outer bone, is richly innervated and vascular, and is anchored by Sharpey's fibres.",
  "related": ["Long bone", "Periosteum"]},

 {"topic": "Growth plate", "difficulty": "medium",
  "question": "Growth in the length of a long bone occurs at the epiphyseal plate, made of:",
  "options": ["A. hyaline cartilage", "B. fibrocartilage",
              "C. compact bone", "D. dense fibrous tissue"],
  "correct_answer": "A",
  "explanation": "The epiphyseal plate is hyaline cartilage between diaphysis and epiphysis; it becomes the epiphyseal line when growth stops.",
  "related": ["Growth plate", "Long bone"]},

 {"topic": "Functional joints", "difficulty": "medium",
  "question": "A joint that permits no movement, such as a skull suture, is a:",
  "options": ["A. synarthrosis", "B. amphiarthrosis",
              "C. diarthrosis", "D. symphysis"],
  "correct_answer": "A",
  "explanation": "Functionally, a synarthrosis allows no movement, an amphiarthrosis slight movement, and a diarthrosis free movement.",
  "related": ["Functional joints", "Joints"]},

 {"topic": "Synovial types", "difficulty": "medium",
  "question": "The shoulder and hip are examples of which synovial joint type?",
  "options": ["A. ball-and-socket", "B. hinge",
              "C. pivot", "D. saddle"],
  "correct_answer": "A",
  "explanation": "Ball-and-socket joints such as the shoulder and hip allow movement in all planes.",
  "related": ["Synovial types", "Joints"]},

 {"topic": "Synovial types", "difficulty": "medium",
  "question": "The elbow, which moves in a single plane, is which type of synovial joint?",
  "options": ["A. hinge", "B. pivot",
              "C. planar", "D. condyloid"],
  "correct_answer": "A",
  "explanation": "The elbow is a hinge joint, allowing flexion and extension in one plane.",
  "related": ["Synovial types", "Joints"]},

 {"topic": "Fascicle arrangement", "difficulty": "medium",
  "question": "Which fascicle arrangement packs many short fibres to maximise force?",
  "options": ["A. pennate", "B. parallel",
              "C. circular", "D. fusiform"],
  "correct_answer": "A",
  "explanation": "Pennate muscles angle many short fascicles onto a tendon, packing in more fibres for greater force at the cost of range.",
  "related": ["Fascicle arrangement", "Muscle"]},

 {"topic": "Muscle attachments", "difficulty": "medium",
  "question": "In muscle terminology, the insertion is the attachment to the:",
  "options": ["A. movable bone", "B. stationary bone",
              "C. nearest tendon", "D. deep fascia"],
  "correct_answer": "A",
  "explanation": "The insertion attaches to the movable bone (usually distal) and is pulled toward the origin on the fixed bone.",
  "related": ["Muscle attachments", "Muscle"]},

 {"topic": "Upper limb vessels", "difficulty": "medium",
  "question": "In the cubital fossa, the brachial artery divides into the radial artery and the:",
  "options": ["A. ulnar artery", "B. axillary artery",
              "C. subclavian artery", "D. digital artery"],
  "correct_answer": "A",
  "explanation": "The brachial artery splits in the cubital fossa into the larger ulnar and smaller radial arteries.",
  "related": ["Upper limb vessels", "Upper limb"]},

 {"topic": "Brachial plexus", "difficulty": "medium",
  "question": "The nerves of the upper limb arise from the brachial plexus, roots:",
  "options": ["A. C5 to T1", "B. C1 to C4",
              "C. T2 to T6", "D. L1 to L5"],
  "correct_answer": "A",
  "explanation": "The brachial plexus arises from spinal roots C5 to T1 and supplies the upper limb with mixed motor and sensory nerves.",
  "related": ["Brachial plexus", "Upper limb"]},

 {"topic": "Connective tissue", "difficulty": "medium",
  "question": "A broad, flat sheet that connects muscle to muscle or bone is a(n):",
  "options": ["A. aponeurosis", "B. tendon",
              "C. ligament", "D. bursa"],
  "correct_answer": "A",
  "explanation": "An aponeurosis is a broad flat sheet; a tendon is a rope-like cord, and both attach muscle to its target.",
  "related": ["Connective tissue", "Muscle"]},

 {"topic": "Skeletal functions", "difficulty": "medium",
  "question": "The formation of blood cells within red marrow is called:",
  "options": ["A. haematopoiesis", "B. ossification",
              "C. remodelling", "D. mineralisation"],
  "correct_answer": "A",
  "explanation": "Blood cell production, or haematopoiesis, occurs in red marrow and is one of the five skeletal functions.",
  "related": ["Skeletal functions", "Long bone"]},

 # ── hard ──────────────────────────────────────────────────────────────
 {"topic": "Bone origin", "difficulty": "hard",
  "question": "The whole musculoskeletal system develops from which embryonic germ layer?",
  "options": ["A. mesoderm", "B. ectoderm",
              "C. endoderm", "D. epiblast"],
  "correct_answer": "A",
  "explanation": "The entire MSK system arises from mesoderm; its connective-tissue precursor is mesenchyme.",
  "related": ["Bone origin", "Limb development"]},

 {"topic": "Cartilaginous joints", "difficulty": "hard",
  "question": "The pubic symphysis, joined by fibrocartilage, is which structural joint?",
  "options": ["A. a symphysis", "B. a synchondrosis",
              "C. a syndesmosis", "D. a gomphosis"],
  "correct_answer": "A",
  "explanation": "A symphysis is a secondary cartilaginous joint united by fibrocartilage; a synchondrosis uses hyaline cartilage.",
  "related": ["Cartilaginous joints", "Joints"]},

 {"topic": "Synovial stability", "difficulty": "hard",
  "question": "Stability of a synovial joint depends on articular shape, muscle tone and:",
  "options": ["A. ligaments", "B. bursae",
              "C. red marrow", "D. periosteum"],
  "correct_answer": "A",
  "explanation": "Synovial stability rests on three things: the shape of the articular surfaces, the ligaments, and muscle tone.",
  "related": ["Synovial stability", "Synovial joint"]},

 {"topic": "Accessory structures", "difficulty": "hard",
  "question": "A fibrocartilage ring that deepens a socket, as at the shoulder, is a:",
  "options": ["A. labrum", "B. bursa",
              "C. meniscus", "D. capsule"],
  "correct_answer": "A",
  "explanation": "A labrum is a fibrocartilage ring that deepens a socket; an articular disc lies between surfaces and a bursa cuts friction.",
  "related": ["Accessory structures", "Synovial joint"]},

 {"topic": "Carpal tunnel", "difficulty": "hard",
  "question": "Compression within the carpal tunnel affects which nerve?",
  "options": ["A. the median nerve", "B. the ulnar nerve",
              "C. the radial nerve", "D. the axillary nerve"],
  "correct_answer": "A",
  "explanation": "The carpal tunnel is a rigid space under the flexor retinaculum; swelling squeezes the median nerve, causing carpal tunnel syndrome.",
  "related": ["Carpal tunnel", "Upper limb"]},

 {"topic": "Dermatome and myotome", "difficulty": "hard",
  "question": "A strip of skin supplied by a single spinal nerve is called a:",
  "options": ["A. dermatome", "B. myotome",
              "C. sclerotome", "D. somite"],
  "correct_answer": "A",
  "explanation": "A dermatome is the skin strip of one spinal nerve; a myotome is the muscle group supplied by one spinal nerve.",
  "related": ["Dermatome and myotome", "Upper limb"]},

 {"topic": "Limb development", "difficulty": "hard",
  "question": "Which structure caps the limb bud and signals the mesoderm to keep growing?",
  "options": ["A. the apical ectodermal ridge", "B. the lateral plate mesoderm",
              "C. the paraxial somite", "D. the neural crest"],
  "correct_answer": "A",
  "explanation": "The apical ectodermal ridge caps the limb bud and signals the mesoderm beneath it to keep growing, driving outgrowth.",
  "related": ["Limb development", "Bone origin"]},

 {"topic": "Limb development", "difficulty": "hard",
  "question": "Fingers and toes are separated during development by:",
  "options": ["A. interdigital apoptosis", "B. increased cell division",
              "C. cartilage deposition", "D. AER duplication"],
  "correct_answer": "A",
  "explanation": "Apoptosis deletes the tissue between the digital rays; if it fails, digits stay webbed, causing syndactyly.",
  "related": ["Limb development", "Limb anomalies"]},

 {"topic": "Limb anomalies", "difficulty": "hard",
  "question": "Achondroplasia, producing short limbs, results from a mutation in which gene?",
  "options": ["A. FGFR3", "B. COL1A1",
              "C. FBN1", "D. DMD"],
  "correct_answer": "A",
  "explanation": "Achondroplasia is an autosomal dominant FGFR3 mutation that brakes endochondral ossification, so long bones cannot lengthen.",
  "related": ["Limb anomalies", "Ossification"]},

 {"topic": "Limb development", "difficulty": "hard",
  "question": "Which mesoderm gives rise to the muscle that migrates into the limb?",
  "options": ["A. paraxial mesoderm", "B. lateral plate mesoderm",
              "C. intermediate mesoderm", "D. cardiac mesoderm"],
  "correct_answer": "A",
  "explanation": "Paraxial mesoderm (somites) forms the limb muscle, while lateral plate mesoderm forms the skeleton and connective tissue.",
  "related": ["Limb development", "Bone origin"]},

 {"topic": "Fascia", "difficulty": "hard",
  "question": "Rising pressure inside a closed fascial compartment after injury causes:",
  "options": ["A. compartment syndrome", "B. carpal tunnel syndrome",
              "C. an aponeurosis tear", "D. a bursa inflammation"],
  "correct_answer": "A",
  "explanation": "Non-stretchy deep fascia lets pressure climb in a closed compartment until it chokes vessels and nerves, causing compartment syndrome.",
  "related": ["Fascia", "Upper limb"]},
]

if __name__ == "__main__":
    sys.exit(emit(KEY, META, Q))
