#!/usr/bin/env python3
"""MHHS2401 W1 · Shoulder Region — regenerated bank (length-matched, no bracket tells, no daredevil)."""
import os, sys, json
HERE = os.path.dirname(os.path.abspath(__file__))
sys.path.insert(0, os.path.join(HERE, "..", "tools"))
from qbank_lib import emit  # noqa

KEY = "shoulder_region_mhhs2401_wk1.html"
BANK = json.load(open(os.path.join(HERE, "..", "..", "guide_quizzes.json"), encoding="utf-8"))
META = {k: BANK[KEY][k] for k in ("title", "subject", "unit", "content")}

Q = [
 # ── easy ──────────────────────────────────────────────────────────────
 {"topic": "Pectoral girdle", "difficulty": "easy",
  "question": "The pectoral girdle is an incomplete bony ring made of which two bones?",
  "options": ["A. clavicle and scapula", "B. clavicle and humerus",
              "C. scapula and sternum", "D. humerus and sternum"],
  "correct_answer": "A",
  "explanation": "The pectoral girdle is the clavicle plus the scapula; its only bony link to the axial skeleton is the sternoclavicular joint.",
  "related": ["Pectoral girdle", "Sternoclavicular joint"]},

 {"topic": "Rotator cuff", "difficulty": "easy",
  "question": "Which muscle of the rotator cuff (SITS) inserts on the lesser tubercle?",
  "options": ["A. subscapularis", "B. supraspinatus",
              "C. infraspinatus", "D. teres minor"],
  "correct_answer": "A",
  "explanation": "Subscapularis is the only anterior cuff muscle; it inserts on the lesser tubercle, while S, I and T reach the greater tubercle.",
  "related": ["Rotator cuff", "Proximal humerus"]},

 {"topic": "Glenohumeral joint", "difficulty": "easy",
  "question": "Which joint is the most mobile joint in the body?",
  "options": ["A. the glenohumeral joint", "B. the acromioclavicular joint",
              "C. the sternoclavicular joint", "D. the scapulothoracic joint"],
  "correct_answer": "A",
  "explanation": "The glenohumeral ball-and-socket joint is the most mobile in the body, trading bony stability for range of motion.",
  "related": ["Glenohumeral joint", "Shoulder dislocation"]},

 {"topic": "Clavicle", "difficulty": "easy",
  "question": "Which bone is described as the most commonly fractured long bone?",
  "options": ["A. the clavicle", "B. the scapula",
              "C. the humerus", "D. the sternum"],
  "correct_answer": "A",
  "explanation": "The clavicle is the most commonly fractured long bone; force along the strut fails at the middle/lateral-third junction.",
  "related": ["Clavicle", "Sternoclavicular joint"]},

 {"topic": "Axillary nerve", "difficulty": "easy",
  "question": "Which nerve is most at risk with a surgical-neck fracture of the humerus?",
  "options": ["A. the axillary nerve", "B. the radial nerve",
              "C. the median nerve", "D. the ulnar nerve"],
  "correct_answer": "A",
  "explanation": "The axillary nerve winds around the surgical neck, so a fracture there can paralyse deltoid and numb the 'regimental badge' area.",
  "related": ["Axillary nerve", "Proximal humerus"]},

 # ── medium ────────────────────────────────────────────────────────────
 {"topic": "Scapula", "difficulty": "medium",
  "question": "The long head of biceps brachii originates from which scapular landmark?",
  "options": ["A. the supraglenoid tubercle", "B. the infraglenoid tubercle",
              "C. the coracoid process", "D. the acromion process"],
  "correct_answer": "A",
  "explanation": "The supraglenoid tubercle (above the glenoid) gives origin to the long head of biceps; the infraglenoid tubercle gives the long head of triceps.",
  "related": ["Scapula", "Proximal humerus"]},

 {"topic": "Scapula", "difficulty": "medium",
  "question": "The long head of triceps brachii originates from which scapular landmark?",
  "options": ["A. the infraglenoid tubercle", "B. the supraglenoid tubercle",
              "C. the coracoid process", "D. the scapular spine"],
  "correct_answer": "A",
  "explanation": "The infraglenoid tubercle (below the glenoid) gives origin to the long head of triceps; biceps takes the supraglenoid tubercle.",
  "related": ["Scapula", "Proximal humerus"]},

 {"topic": "Serratus anterior", "difficulty": "medium",
  "question": "Serratus anterior receives its sole motor supply from which nerve?",
  "options": ["A. the long thoracic nerve", "B. the dorsal scapular nerve",
              "C. the thoracodorsal nerve", "D. the suprascapular nerve"],
  "correct_answer": "A",
  "explanation": "The long thoracic nerve is the sole supply to serratus anterior; running superficially, it is vulnerable to injury.",
  "related": ["Serratus anterior", "Winged scapula"]},

 {"topic": "Winged scapula", "difficulty": "medium",
  "question": "A winged scapula results from paralysis of which muscle?",
  "options": ["A. serratus anterior", "B. the trapezius",
              "C. the rhomboid major", "D. levator scapulae"],
  "correct_answer": "A",
  "explanation": "Losing serratus anterior stops the scapula being held to the ribs, so it lifts off as a winged scapula and overhead abduction fails.",
  "related": ["Winged scapula", "Serratus anterior"]},

 {"topic": "Acromioclavicular joint", "difficulty": "medium",
  "question": "The two bands of the coracoclavicular ligament are named the:",
  "options": ["A. trapezoid and conoid", "B. superior and inferior",
              "C. anterior and posterior", "D. medial and lateral"],
  "correct_answer": "A",
  "explanation": "The coracoclavicular ligament has a lateral trapezoid band and a medial conoid band, anchoring to the clavicle's matching marks.",
  "related": ["Acromioclavicular joint", "Clavicle"]},

 {"topic": "Acromioclavicular joint", "difficulty": "medium",
  "question": "True stability of the acromioclavicular joint comes chiefly from which ligament?",
  "options": ["A. the coracoclavicular ligament", "B. the coracoacromial ligament",
              "C. the coracohumeral ligament", "D. the transverse humeral ligament"],
  "correct_answer": "A",
  "explanation": "The extrinsic coracoclavicular ligament slings the scapula from the clavicle and bears the limb's weight, providing real AC stability.",
  "related": ["Acromioclavicular joint", "AC separation"]},

 {"topic": "Deltoid", "difficulty": "medium",
  "question": "The deltoid muscle is supplied by which nerve?",
  "options": ["A. the axillary nerve", "B. the suprascapular nerve",
              "C. the thoracodorsal nerve", "D. the subscapular nerve"],
  "correct_answer": "A",
  "explanation": "Deltoid is supplied by the axillary nerve; its damage in surgical-neck fracture or dislocation abolishes abduction.",
  "related": ["Deltoid", "Axillary nerve"]},

 {"topic": "Latissimus dorsi", "difficulty": "medium",
  "question": "Latissimus dorsi inserts into which part of the intertubercular groove?",
  "options": ["A. the groove floor", "B. the medial lip",
              "C. the lateral lip", "D. the greater tubercle"],
  "correct_answer": "A",
  "explanation": "In the 'lady between two majors', latissimus dorsi (the lady) inserts on the floor, with pec major laterally and teres major medially.",
  "related": ["Latissimus dorsi", "Proximal humerus"]},

 {"topic": "Pectoralis major", "difficulty": "medium",
  "question": "Pectoralis major inserts onto which part of the intertubercular groove?",
  "options": ["A. the lateral lip", "B. the medial lip",
              "C. the floor of the groove", "D. the lesser tubercle"],
  "correct_answer": "A",
  "explanation": "Pectoralis major inserts on the lateral lip of the bicipital groove; teres major takes the medial lip and latissimus the floor.",
  "related": ["Pectoralis major", "Proximal humerus"]},

 {"topic": "Trapezius", "difficulty": "medium",
  "question": "The trapezius receives its motor supply from which nerve?",
  "options": ["A. the accessory nerve", "B. the dorsal scapular nerve",
              "C. the long thoracic nerve", "D. the thoracodorsal nerve"],
  "correct_answer": "A",
  "explanation": "Trapezius is supplied by the spinal accessory nerve (CN XI) for motor function, with C3/C4 carrying sensation.",
  "related": ["Trapezius", "Scapular movers"]},

 {"topic": "Scapulohumeral rhythm", "difficulty": "medium",
  "question": "Scapulohumeral rhythm during abduction follows roughly which glenohumeral-to-scapular ratio?",
  "options": ["A. about two to one", "B. about one to one",
              "C. about one to two", "D. about four to one"],
  "correct_answer": "A",
  "explanation": "Overall abduction is roughly 2:1 — about 120 degrees glenohumeral plus 60 degrees scapular rotation for around 180 degrees total.",
  "related": ["Scapulohumeral rhythm", "Glenohumeral joint"]},

 {"topic": "Supraspinatus", "difficulty": "medium",
  "question": "Which muscle initiates the first 0-15 degrees of arm abduction?",
  "options": ["A. supraspinatus", "B. the deltoid",
              "C. infraspinatus", "D. teres minor"],
  "correct_answer": "A",
  "explanation": "Supraspinatus initiates the first 15 degrees of abduction and pulls the head into the glenoid, after which deltoid takes over.",
  "related": ["Supraspinatus", "Deltoid"]},

 {"topic": "Sternoclavicular joint", "difficulty": "medium",
  "question": "The sternoclavicular joint is formed by the clavicle, the manubrium and the:",
  "options": ["A. first costal cartilage", "B. first thoracic vertebra",
              "C. acromion of scapula", "D. coracoid of scapula"],
  "correct_answer": "A",
  "explanation": "The SC joint unites the sternal clavicle, the clavicular notch of the manubrium and part of the first costal cartilage.",
  "related": ["Sternoclavicular joint", "Clavicle"]},

 {"topic": "Rotator cuff", "difficulty": "medium",
  "question": "Which three rotator-cuff muscles insert on the greater tubercle?",
  "options": ["A. supraspinatus, infraspinatus, teres minor",
              "B. supraspinatus, infraspinatus, subscapularis",
              "C. infraspinatus, teres minor, subscapularis",
              "D. supraspinatus, teres minor, subscapularis"],
  "correct_answer": "A",
  "explanation": "Supraspinatus, infraspinatus and teres minor all reach the greater tubercle; only subscapularis inserts on the lesser tubercle.",
  "related": ["Rotator cuff", "Proximal humerus"]},

 {"topic": "Teres major", "difficulty": "medium",
  "question": "Teres major inserts into which part of the intertubercular groove?",
  "options": ["A. the medial lip", "B. the lateral lip",
              "C. the floor of the groove", "D. the greater tubercle"],
  "correct_answer": "A",
  "explanation": "Teres major takes the medial lip of the bicipital groove, flanking latissimus (floor) opposite pec major (lateral lip).",
  "related": ["Teres major", "Proximal humerus"]},

 # ── hard ──────────────────────────────────────────────────────────────
 {"topic": "Clavicle", "difficulty": "hard",
  "question": "A clavicle fracture most often occurs at which point along the bone?",
  "options": ["A. the middle/lateral-third junction", "B. the sternal-end enlargement",
              "C. the acromial-end flat facet", "D. the subclavian groove floor"],
  "correct_answer": "A",
  "explanation": "Force concentrates where the forward convex medial curve meets the concave lateral curve — the middle/lateral-third junction fails.",
  "related": ["Clavicle", "Sternoclavicular joint"]},

 {"topic": "Shoulder dislocation", "difficulty": "hard",
  "question": "The humeral head most commonly dislocates in which direction?",
  "options": ["A. antero-inferiorly", "B. postero-superiorly",
              "C. directly superiorly", "D. directly posteriorly"],
  "correct_answer": "A",
  "explanation": "The capsule is weakest antero-inferiorly and the arch blocks superior escape, so dislocation is usually antero-inferior in abduction and external rotation.",
  "related": ["Shoulder dislocation", "Glenohumeral joint"]},

 {"topic": "Rotator cuff", "difficulty": "hard",
  "question": "Supraspinatus and infraspinatus are both supplied by which nerve?",
  "options": ["A. the suprascapular nerve", "B. the axillary nerve",
              "C. the dorsal scapular nerve", "D. the upper subscapular nerve"],
  "correct_answer": "A",
  "explanation": "The suprascapular nerve supplies supraspinatus and infraspinatus; subscapularis takes the subscapular nerves and teres minor the axillary.",
  "related": ["Rotator cuff", "Suprascapular nerve"]},

 {"topic": "Rotator cuff", "difficulty": "hard",
  "question": "Teres minor, a rotator-cuff muscle, is supplied by which nerve?",
  "options": ["A. the axillary nerve", "B. the suprascapular nerve",
              "C. the subscapular nerve", "D. the dorsal scapular nerve"],
  "correct_answer": "A",
  "explanation": "Teres minor is supplied by the axillary nerve, unlike the other cuff muscles which take the suprascapular or subscapular nerves.",
  "related": ["Rotator cuff", "Axillary nerve"]},

 {"topic": "Coraco-acromial arch", "difficulty": "hard",
  "question": "Which structure is chiefly pinched in subacromial impingement under the coraco-acromial arch?",
  "options": ["A. the supraspinatus tendon", "B. the subscapularis tendon",
              "C. the long head of triceps", "D. the coracohumeral ligament"],
  "correct_answer": "A",
  "explanation": "The supraspinatus tendon and subacromial bursa run through the tight space under the arch, so supraspinatus impinges and tears first.",
  "related": ["Coraco-acromial arch", "Supraspinatus"]},

 {"topic": "Glenohumeral joint", "difficulty": "hard",
  "question": "The fibrocartilage glenoid labrum contributes to the joint chiefly by:",
  "options": ["A. deepening the shallow socket", "B. producing the joint fluid",
              "C. limiting external rotation", "D. anchoring the biceps head"],
  "correct_answer": "A",
  "explanation": "The labrum is a fibrocartilage rim that deepens the shallow glenoid about 50 percent; tearing it (Bankart lesion) eases dislocation.",
  "related": ["Glenohumeral joint", "Shoulder dislocation"]},

 {"topic": "Glenohumeral ligaments", "difficulty": "hard",
  "question": "The transverse humeral ligament functions to:",
  "options": ["A. hold the biceps tendon in place", "B. deepen the glenoid cavity rim",
              "C. block superior head displacement", "D. bind the clavicle to rib one"],
  "correct_answer": "A",
  "explanation": "The transverse humeral ligament bridges the tubercles and roofs the bicipital groove, keeping the long head of biceps tendon in place.",
  "related": ["Glenohumeral ligaments", "Proximal humerus"]},

 {"topic": "Impingement", "difficulty": "hard",
  "question": "A painful arc from subacromial impingement classically occurs over which range of abduction?",
  "options": ["A. about 60 to 120 degrees", "B. about 0 to 15 degrees",
              "C. about 15 to 45 degrees", "D. about 150 to 180 degrees"],
  "correct_answer": "A",
  "explanation": "Impingement gives a painful arc around 60-120 degrees of abduction, with weak initiation and a positive 'empty can' test.",
  "related": ["Impingement", "Supraspinatus"]},

 {"topic": "Sternoclavicular joint", "difficulty": "hard",
  "question": "The sternoclavicular joint is structurally a saddle joint that functions as a:",
  "options": ["A. ball-and-socket joint", "B. simple hinge joint",
              "C. plane gliding joint", "D. fixed fibrous joint"],
  "correct_answer": "A",
  "explanation": "The SC joint is a synovial saddle joint that functions as a ball-and-socket, serving as the pivot for all girdle movement.",
  "related": ["Sternoclavicular joint", "Pectoral girdle"]},
]

if __name__ == "__main__":
    sys.exit(emit(KEY, META, Q))
