#!/usr/bin/env python3
"""SOCI1010 W3 · Not So Mundane — Theorising the Everyday — regenerated bank."""
import os, sys, json
HERE = os.path.dirname(os.path.abspath(__file__))
sys.path.insert(0, os.path.join(HERE, "..", "tools"))
from qbank_lib import emit  # noqa

KEY = "soci1010_wk3_not_so_mundane.html"
BANK = json.load(open(os.path.join(HERE, "..", "..", "guide_quizzes.json"), encoding="utf-8"))
META = {k: BANK[KEY][k] for k in ("title", "subject", "unit", "content")}

Q = [
 {"topic": "Why the everyday", "difficulty": "medium",
  "question": "Susie Scott's Week-3 warning about everyday sites is that:",
  "options": ["A. routine and familiarity don't free sites from power",
              "B. everyday sites are wholly free of any control",
              "C. familiar places have no rules whatsoever",
              "D. only formal institutions ever exercise power"],
  "correct_answer": "A",
  "explanation": "Scott warns that although everyday sites are marked by repetition and familiarity, they remain shaped by power and control.",
  "related": ["Why the everyday", "Moral consensus"]},

 {"topic": "Moral consensus", "difficulty": "hard",
  "question": "The shared norms essential to society's smooth functioning were called 'moral consensus' by:",
  "options": ["A. Durkheim", "B. Weber", "C. Simmel", "D. Goffman"],
  "correct_answer": "A",
  "explanation": "The shared norms essential to society's smooth functioning are Durkheim's idea of moral consensus.",
  "related": ["Moral consensus", "Reflexivity"]},

 {"topic": "Reflexivity", "difficulty": "hard",
  "question": "'Reflexivity', as used in the lecture, means that:",
  "options": ["A. people are shaped by interaction and shape it too",
              "B. people are shaped by biology alone",
              "C. interaction has no effect on identity",
              "D. individuals never influence their own wider society at all"],
  "correct_answer": "A",
  "explanation": "Reflexivity is the two-way loop: interaction shapes people's thoughts and identity, and they shape interaction in turn.",
  "related": ["Reflexivity", "Symbolic interactionism"]},

 {"topic": "Sztompka's framework", "difficulty": "hard",
  "question": "Which is one of Sztompka's five points for analysing a social event?",
  "options": ["A. the presence of bystanders distinguishing public from private",
              "B. the exact weather during the event",
              "C. the price of admission to attend",
              "D. the total population of the whole entire country"],
  "correct_answer": "A",
  "explanation": "One of Sztompka's five points is the presence of bystanders, which separates a public event from a private one.",
  "related": ["Sztompka's framework", "Co-presence"]},

 {"topic": "Co-presence", "difficulty": "medium",
  "question": "A face-to-face conversation and an exchange over social media differ mainly in that the latter is:",
  "options": ["A. distant and mediated rather than co-present",
              "B. always slower than a phone call",
              "C. impossible to conduct in real time",
              "D. free of any social norms at all"],
  "correct_answer": "A",
  "explanation": "Sztompka's first point distinguishes direct face-to-face co-presence from distant, mediated exchange like social media.",
  "related": ["Co-presence", "Sztompka's framework"]},

 {"topic": "Rites of passage", "difficulty": "medium",
  "question": "Putting on slippers at home and logging on at work are examples of:",
  "options": ["A. rites of passage marking a change of context",
              "B. a purely economic financial transaction",
              "C. random personal habits with no real hidden meaning",
              "D. formal ceremonies run by the state"],
  "correct_answer": "A",
  "explanation": "Small daily rituals — slippers at home, logging on at work — mark transitions between one context and another.",
  "related": ["Rites of passage", "Interactive ritual"]},

 {"topic": "Banal nationalism", "difficulty": "hard",
  "question": "Michael Billig's 'banal nationalism' refers to:",
  "options": ["A. the unnoticed daily reproduction of national belonging",
              "B. aggressive flag-waving at political rallies",
              "C. formal citizenship tests for migrants",
              "D. the total abolition of all national symbols"],
  "correct_answer": "A",
  "explanation": "Banal nationalism (Billig) is the routine, taken-for-granted marking of the nation in everyday life.",
  "related": ["Banal nationalism", "The footpath"]},

 {"topic": "The footpath", "difficulty": "hard",
  "question": "Nicholas Blomley's term 'pedestrianism' describes the sidewalk's governing logic as:",
  "options": ["A. prioritising smooth movement over democratic assembly",
              "B. banning all pedestrians from the street",
              "C. turning footpaths into private gardens",
              "D. encouraging crowds to gather and protest"],
  "correct_answer": "A",
  "explanation": "Blomley's 'pedestrianism' treats the sidewalk as a transport corridor, prioritising unhindered flow over public assembly.",
  "related": ["The footpath", "Public space & race"]},

 {"topic": "The footpath", "difficulty": "medium",
  "question": "Under 'pedestrianism', people standing around on the footpath are likely to be:",
  "options": ["A. moved on as obstruction or 'visual clutter'",
              "B. welcomed as a lively big public gathering",
              "C. given seats and refreshments there",
              "D. ignored entirely by the authorities"],
  "correct_answer": "A",
  "explanation": "Because the golden rule is unhindered flow, loiterers can be moved on as obstruction or 'visual clutter'.",
  "related": ["The footpath", "Banal nationalism"]},

 {"topic": "Public space & race", "difficulty": "medium",
  "question": "Under Jim Crow segregation, the footpath encoded racial order by requiring Black pedestrians to:",
  "options": ["A. step off the sidewalk or 'give whites the wall'",
              "B. walk freely wherever they wished to go completely alone",
              "C. use only the very centre of the road",
              "D. build entirely separate private footpaths"],
  "correct_answer": "A",
  "explanation": "Jim Crow racial etiquette required Black pedestrians to give way — stepping off the sidewalk or 'giving whites the wall'.",
  "related": ["Public space & race", "The footpath"]},

 {"topic": "Ordinary Streets", "difficulty": "hard",
  "question": "The 'urban mutualism' seen on Rye Lane, Peckham refers to:",
  "options": ["A. one shop subdivided into small compatible units",
              "B. many shops merged into one large store",
              "C. shops owned entirely by the government",
              "D. a street with no commercial activity"],
  "correct_answer": "A",
  "explanation": "Urban mutualism on Rye Lane means subdividing a shop into tiny compatible spaces — a migrant startup strategy.",
  "related": ["Ordinary Streets", "The footpath"]},

 {"topic": "Weber", "difficulty": "hard",
  "question": "Weber's argument in 'The Protestant Ethic' is that Protestant values:",
  "options": ["A. aligned with and encouraged a capitalist mindset",
              "B. single-handedly caused modern capitalism",
              "C. actively opposed all forms of private profit",
              "D. had no connection to economic life"],
  "correct_answer": "A",
  "explanation": "Weber does not claim Protestantism caused capitalism; its values of hard work and discipline aligned with and encouraged it.",
  "related": ["Weber", "Rationalisation"]},

 {"topic": "Rationalisation", "difficulty": "medium",
  "question": "Which is one of Weber's four dimensions of rationalisation?",
  "options": ["A. calculability — a concern with numerical data",
              "B. tradition — respect for ancient custom",
              "C. spontaneity — acting on sudden feeling",
              "D. enchantment — belief in magic and miracle"],
  "correct_answer": "A",
  "explanation": "Weber's four dimensions are efficiency, predictability, calculability and dehumanisation; calculability concerns numerical data.",
  "related": ["Rationalisation", "Bureaucracy"]},

 {"topic": "Bureaucracy", "difficulty": "hard",
  "question": "In Weber's bureaucracy, we obey a tax official or clerk because of:",
  "options": ["A. the role and its rules, not the person",
              "B. their personal charm and their strong individual character",
              "C. the fear of physical force alone",
              "D. an ancient and sacred family tradition"],
  "correct_answer": "A",
  "explanation": "Bureaucratic authority is impersonal: it attaches to the role and its formal rules, not to the individual who holds it.",
  "related": ["Bureaucracy", "Rationalisation"]},

 {"topic": "Bureaucracy", "difficulty": "medium",
  "question": "Which is one of the five features of bureaucracy?",
  "options": ["A. a clear hierarchy of authority",
              "B. rule by personal favour alone",
              "C. an absence of any written rules",
              "D. decisions made by random chance"],
  "correct_answer": "A",
  "explanation": "Bureaucracy's five features include formal rules, a clear hierarchy of authority, specialisation, impersonality and merit.",
  "related": ["Bureaucracy", "Iron cage"]},

 {"topic": "Iron cage", "difficulty": "hard",
  "question": "Weber's 'iron cage' names the danger that:",
  "options": ["A. over-rationalisation imprisons people in rules",
              "B. society becomes joyfully spontaneous again",
              "C. all bureaucratic rules are abolished",
              "D. magic and religion return to public life"],
  "correct_answer": "A",
  "explanation": "The iron cage is the 'irrationality of rationality' — rules meant to serve efficiency end up imprisoning people.",
  "related": ["Iron cage", "Bureaucracy"]},

 {"topic": "Emotional labour", "difficulty": "hard",
  "question": "Arlie Hochschild's 'emotional labour' is:",
  "options": ["A. managing one's feelings for a required paid display",
              "B. hard physical work done for very low wages",
              "C. the pay received for overtime hours",
              "D. emotions felt privately and never shown"],
  "correct_answer": "A",
  "explanation": "Emotional labour (Hochschild) is the management of feeling to create a required, paid emotional display at work.",
  "related": ["Emotional labour", "Simmel"]},

 {"topic": "Emotional labour", "difficulty": "hard",
  "question": "The difference between 'display rules' and 'feeling rules' is that:",
  "options": ["A. display rules from the firm, feeling rules from society",
              "B. both are set entirely by the single lone individual worker",
              "C. both are written into formal employment law",
              "D. neither has any effect on real behaviour"],
  "correct_answer": "A",
  "explanation": "Display rules are organisationally prescribed — how you must express emotion; feeling rules are society's expectations about what to feel.",
  "related": ["Emotional labour", "Authenticity dilemma"]},

 {"topic": "Emotional labour", "difficulty": "medium",
  "question": "Plastering on a smile while feeling annoyed is Hochschild's:",
  "options": ["A. surface acting", "B. deep acting",
              "C. method acting", "D. emotional labour"],
  "correct_answer": "A",
  "explanation": "Surface acting modifies only the outward expression; deep acting tries to actually feel the required emotion.",
  "related": ["Emotional labour", "Authenticity dilemma"]},

 {"topic": "Emotional labour", "difficulty": "medium",
  "question": "The 'authenticity dilemma' of emotional labour is the tension between:",
  "options": ["A. the genuine self and the work self",
              "B. two different employers at once",
              "C. one's distant past self and future self",
              "D. the conscious and the unconscious mind"],
  "correct_answer": "A",
  "explanation": "Emotional labour can open a gap between one's genuine self and the self required by the job — the authenticity dilemma.",
  "related": ["Emotional labour", "Symbolic interactionism"]},

 {"topic": "Simmel", "difficulty": "hard",
  "question": "Simmel argued sociology should study:",
  "options": ["A. the forms of interaction rather than their content",
              "B. the content of interaction rather than its form",
              "C. only the biology of the human brain",
              "D. large-scale economic statistics alone"],
  "correct_answer": "A",
  "explanation": "Simmel stressed studying the forms of social relationship, working bottom-up from patterns of interaction.",
  "related": ["Simmel", "The Stranger"]},

 {"topic": "Simmel", "difficulty": "medium",
  "question": "For Simmel, a two-person dyad differs from a three-person triad because:",
  "options": ["A. the number of parties changes the interaction",
              "B. more people always means less conflict",
              "C. group size has no effect on interaction",
              "D. only two-person groups are truly social"],
  "correct_answer": "A",
  "explanation": "Simmel noticed the number of parties itself shapes interaction — a dyad differs fundamentally from a triad.",
  "related": ["Simmel", "The Stranger"]},

 {"topic": "The Stranger", "difficulty": "hard",
  "question": "Simmel's figure of 'the Stranger' captures someone who is:",
  "options": ["A. both near and far at the same time",
              "B. entirely outside the group forever",
              "C. fully and permanently inside the whole entire group",
              "D. unknown to absolutely everyone around"],
  "correct_answer": "A",
  "explanation": "The Stranger combines distance and closeness — near and far at once — a distinctive social form for Simmel.",
  "related": ["The Stranger", "Simmel"]},

 {"topic": "Metropolis", "difficulty": "medium",
  "question": "Simmel's 'blasé attitude' is a response to:",
  "options": ["A. the overstimulation of city life",
              "B. the calm silence of the countryside",
              "C. a total lack of any stimulation",
              "D. warm intimacy with close neighbours"],
  "correct_answer": "A",
  "explanation": "In 'Metropolis and Mental Life', the city's bombardment of stimuli forces a protective blasé detachment.",
  "related": ["Metropolis", "Philosophy of Money"]},

 {"topic": "Philosophy of Money", "difficulty": "hard",
  "question": "In 'The Philosophy of Money', Simmel argues money:",
  "options": ["A. makes ties instrumental, reducing quality to quantity",
              "B. money deepens warm, personal, social human bonds",
              "C. has no effect on human relationships",
              "D. restores older traditional obligations"],
  "correct_answer": "A",
  "explanation": "Money makes ties calculable and instrumental — 'hi, latte, bye' — reducing quality to quantity.",
  "related": ["Philosophy of Money", "Metropolis"]},

 {"topic": "Lefebvre", "difficulty": "hard",
  "question": "In 'The Production of Space', Lefebvre's central claim is that space is:",
  "options": ["A. socially produced, not a neutral container",
              "B. a fixed, neutral, empty container",
              "C. purely a matter of physics and geometry",
              "D. irrelevant to social and political life"],
  "correct_answer": "A",
  "explanation": "Lefebvre argues space is socially produced through a triad of practices, never a neutral container.",
  "related": ["Lefebvre", "Spatial triad"]},

 {"topic": "Spatial triad", "difficulty": "hard",
  "question": "In Lefebvre's spatial triad, the planners' and engineers' abstract conception of space is:",
  "options": ["A. representations of space", "B. spatial practice",
              "C. representational spaces", "D. the iron cage"],
  "correct_answer": "A",
  "explanation": "In Lefebvre's triad, the planners' and engineers' abstract conception of space is 'representations of space'.",
  "related": ["Spatial triad", "Lefebvre"]},

 {"topic": "Lefebvre", "difficulty": "hard",
  "question": "The drive-through is used to illustrate Lefebvre's idea of:",
  "options": ["A. abstract space produced for capitalist consumption",
              "B. a shared community gathering place",
              "C. sacred space for religious ritual",
              "D. wild space untouched by any planning"],
  "correct_answer": "A",
  "explanation": "The drive-through is single-purpose 'abstract space' — planner-dominated and privatised for consumption over community.",
  "related": ["Lefebvre", "Spatial triad"]},

 {"topic": "Foucault", "difficulty": "hard",
  "question": "In 'Discipline and Punish', Foucault charts a shift to power that is:",
  "options": ["A. invisible and internalised, so we discipline ourselves",
              "B. more public and violent than ever before",
              "C. focused only on physical torture again",
              "D. abolished entirely in modern society"],
  "correct_answer": "A",
  "explanation": "Medieval torture put power outside the body and made it visible; the modern prison makes discipline invisible and internalised.",
  "related": ["Foucault", "Panopticon"]},

 {"topic": "Panopticon", "difficulty": "hard",
  "question": "The panopticon disciplines people because they:",
  "options": ["A. never know if they are watched, so self-regulate",
              "B. are always physically chained down in their place",
              "C. are watched constantly by many guards",
              "D. face no surveillance of any kind"],
  "correct_answer": "A",
  "explanation": "The central watchtower means one might always be observed; that uncertainty leads people to regulate themselves.",
  "related": ["Panopticon", "Foucault"]},

 {"topic": "Foucault", "difficulty": "medium",
  "question": "For Foucault, power in modern society is best described as:",
  "options": ["A. everywhere and productive, not merely repressive",
              "B. held only by the state and police",
              "C. purely repressive and negative always",
              "D. located in one central ruler alone"],
  "correct_answer": "A",
  "explanation": "Foucault sees power as diffuse and productive — shaping subjects and conduct, not merely repressing them.",
  "related": ["Foucault", "Panopticon"]},

 {"topic": "Ethnomethodology", "difficulty": "hard",
  "question": "Garfinkel's ethnomethodology studies:",
  "options": ["A. how people make sense of and produce order",
              "B. how the state enforces its written laws",
              "C. how our genes fully determine all human behaviour",
              "D. how markets set the price of goods"],
  "correct_answer": "A",
  "explanation": "Ethnomethodology (people + method + study) examines how people make sense of and produce social order.",
  "related": ["Ethnomethodology", "Breaching experiments"]},

 {"topic": "Breaching experiments", "difficulty": "hard",
  "question": "A 'breaching experiment' works by:",
  "options": ["A. deliberately breaking a tacit rule to expose it",
              "B. carefully following every social rule closely",
              "C. surveying a very large random sample of people",
              "D. testing a chemical reaction in a lab"],
  "correct_answer": "A",
  "explanation": "Breaching experiments break an unwritten rule of interaction to make the tacit rule suddenly visible.",
  "related": ["Breaching experiments", "Ethnomethodology"]},

 {"topic": "Norms", "difficulty": "medium",
  "question": "The difference between formal and informal norms is that:",
  "options": ["A. formal norms are written; informal ones are unwritten",
              "B. formal norms are unwritten; informal ones written",
              "C. both kinds of norm are always fully written down",
              "D. neither kind of norm is ever enforced"],
  "correct_answer": "A",
  "explanation": "Formal norms are society's written rules; informal norms are the unwritten expectations of everyday conduct.",
  "related": ["Norms", "Breaching experiments"]},

 {"topic": "Symbolic interactionism", "difficulty": "hard",
  "question": "The core premise of symbolic interactionism is that:",
  "options": ["A. people act toward things based on their meanings",
              "B. people act purely on their inborn biological instinct",
              "C. meanings are fixed and never change",
              "D. objects have no meaning for anyone"],
  "correct_answer": "A",
  "explanation": "Symbolic interactionism's premise is that people act toward things on the basis of the meanings those things hold.",
  "related": ["Symbolic interactionism", "Goffman"]},

 {"topic": "Goffman", "difficulty": "hard",
  "question": "Goffman's 'dramaturgical' model treats social life as:",
  "options": ["A. theatre — the performance of roles on stages",
              "B. warfare — a constant battle for power",
              "C. a machine — fixed cogs turning together",
              "D. an economy — the buyers and sellers always trading"],
  "correct_answer": "A",
  "explanation": "In 'The Presentation of Self' (1959), Goffman treats interactions as performances of roles on social stages.",
  "related": ["Goffman", "Impression management"]},

 {"topic": "Goffman", "difficulty": "hard",
  "question": "The difference between Goffman's 'front stage' and 'back stage' is:",
  "options": ["A. front stage performs to an audience; back stage off-role",
              "B. both stages always perform to an audience",
              "C. neither stage involves any performance",
              "D. back stage performs while front stage stays entirely private"],
  "correct_answer": "A",
  "explanation": "Front stage is where we perform to an audience following the role's conventions; back stage is where we drop the role.",
  "related": ["Goffman", "Impression management"]},

 {"topic": "Goffman", "difficulty": "medium",
  "question": "Controlling the impression others form of us is Goffman's:",
  "options": ["A. impression management", "B. emotional labour",
              "C. surface acting", "D. banal nationalism"],
  "correct_answer": "A",
  "explanation": "Impression management is the everyday work of shaping how others perceive us.",
  "related": ["Goffman", "Emotional labour"]},

 {"topic": "Interactive ritual", "difficulty": "hard",
  "question": "Goffman extends Durkheim's sacred/profane distinction by arguing that:",
  "options": ["A. all interaction, like greetings, is 'interactive ritual'",
              "B. only religious ceremonies count as ritual",
              "C. ritual has vanished from modern life",
              "D. greetings carry no social meaning at all"],
  "correct_answer": "A",
  "explanation": "Where Durkheim tied ritual to the sacred, Goffman treats all interaction — even greetings — as interactive ritual.",
  "related": ["Interactive ritual", "Dismissive bow"]},

 {"topic": "Dismissive bow", "difficulty": "medium",
  "question": "The 'dismissive bow' from Curb Your Enthusiasm illustrates that in an interactive ritual:",
  "options": ["A. the ritual's precise form carries the actual meaning",
              "B. the words spoken matter more than the gesture",
              "C. rituals have no real meaning at all",
              "D. only sincere feelings ever matter socially"],
  "correct_answer": "A",
  "explanation": "A bow of the wrong depth reads as 'not sorry at all' — the ritual's exact form, not just the words, carries the meaning.",
  "related": ["Dismissive bow", "Interactive ritual"]},

 {"topic": "Swimming pool", "difficulty": "hard",
  "question": "Susie Scott analyses the swimming pool as a 'negotiated order', meaning:",
  "options": ["A. an order precariously upheld by participants' polite fiction",
              "B. a rigid order strictly enforced by the lifeguards",
              "C. total chaos with no order whatsoever",
              "D. an order fixed permanently by written law"],
  "correct_answer": "A",
  "explanation": "Scott (2009) shows the pool's orderliness is a negotiated order sustained by participants' shared polite fictions.",
  "related": ["Swimming pool", "Interactive ritual"]},

 {"topic": "Swimming pool", "difficulty": "hard",
  "question": "Which is one of the three swimming-pool norms Scott identifies?",
  "options": ["A. the desexualisation of encounters",
              "B. the encouragement of loud conversation",
              "C. a strict dress code for all swimmers",
              "D. compulsory racing between strangers"],
  "correct_answer": "A",
  "explanation": "Scott's three tacit pool norms are respect for personal space, respect for privacy, and the desexualisation of encounters.",
  "related": ["Swimming pool", "Norms"]},

 {"topic": "Swimming pool", "difficulty": "hard",
  "question": "Scott titles her study 'Re-clothing the Emperor' to make the point that swimmers:",
  "options": ["A. can't consciously attend to the order they build",
              "B. openly discuss and debate the order they create",
              "C. believe the pool has no real social order",
              "D. think lifeguards alone create all the order"],
  "correct_answer": "A",
  "explanation": "Like the emperor's subjects who dare not admit they see nothing, swimmers can't openly attend to the order they build yet uphold it.",
  "related": ["Swimming pool", "Negotiated order"]},

 {"topic": "Theorists overview", "difficulty": "hard",
  "question": "Which pairing of theorist and concept is correct?",
  "options": ["A. Hochschild — emotional labour",
              "B. Foucault — emotional labour",
              "C. Simmel — the panopticon",
              "D. Goffman — the spatial triad"],
  "correct_answer": "A",
  "explanation": "Hochschild gave us emotional labour; the panopticon is Foucault, the spatial triad Lefebvre, and dramaturgy Goffman.",
  "related": ["Theorists overview", "Emotional labour"]},
]

if __name__ == "__main__":
    sys.exit(emit(KEY, META, Q))
