#!/usr/bin/env python3
"""SOCI1010 W1 · What is Everyday Life? — regenerated bank.
Comprehensive concept coverage, duplicates collapsed, distractors are real
theorists/terms from the guide. Length-matched, no bracket tells, no daredevil."""
import os, sys, json
HERE = os.path.dirname(os.path.abspath(__file__))
sys.path.insert(0, os.path.join(HERE, "..", "tools"))
from qbank_lib import emit  # noqa

KEY = "soci1010_wk1_everyday_life.html"
BANK = json.load(open(os.path.join(HERE, "..", "..", "guide_quizzes.json"), encoding="utf-8"))
META = {k: BANK[KEY][k] for k in ("title", "subject", "unit", "content")}

Q = [
 {"topic": "Defining sociology", "difficulty": "easy",
  "question": "In the lecture, sociology is defined as:",
  "options": ["A. the study of how society shapes our lives",
              "B. the study of individual psychology and choice",
              "C. the study of ancient human biology",
              "D. the study of economic markets on their own"],
  "correct_answer": "A",
  "explanation": "Sociology examines society and how it shapes our lives — and serves as a tool for understanding the world.",
  "related": ["Defining sociology", "Sociological imagination"]},

 {"topic": "Sociological imagination", "difficulty": "medium",
  "question": "C. Wright Mills (1959) gave the name 'sociological imagination' to:",
  "options": ["A. a quality of mind linking personal life to society",
              "B. a talent for inventing fictional social worlds",
              "C. a statistical method for surveying populations",
              "D. a bias that hides society behind the lone individual"],
  "correct_answer": "A",
  "explanation": "Mills called it a quality of mind: vivid awareness of the relationship between personal experience and the wider society.",
  "related": ["Sociological imagination", "Private troubles"]},

 {"topic": "Sociological imagination", "difficulty": "medium",
  "question": "Which statement best captures Mills's sociological imagination?",
  "options": ["A. neither a life nor a history makes sense alone",
              "B. individual choices explain all of history",
              "C. society can be fully grasped without any real individuals",
              "D. personal biography is irrelevant to sociology"],
  "correct_answer": "A",
  "explanation": "The individual and society are mutually intelligible — you cannot grasp one without the other.",
  "related": ["Sociological imagination", "Micro and macro"]},

 {"topic": "Private troubles", "difficulty": "medium",
  "question": "For Mills, to 'relate private troubles to public issues' means to:",
  "options": ["A. find the social patterns within individual lives",
              "B. blame individuals for their own hardships",
              "C. treat every problem as purely personal",
              "D. ignore the structures around a person"],
  "correct_answer": "A",
  "explanation": "Thinking sociologically links private troubles to public issues — seeing the social structure behind individual experience.",
  "related": ["Private troubles", "Sociological imagination"]},

 {"topic": "Sociological imagination", "difficulty": "hard",
  "question": "For Mills, blaming an unemployed person for 'laziness':",
  "options": ["A. mistakes a public issue for a private trouble",
              "B. mistakes a private trouble for a public issue",
              "C. correctly locates the cause in the person",
              "D. shows a fully developed sociological imagination"],
  "correct_answer": "A",
  "explanation": "Unemployment is shaped by social forces such as the job market and offshoring; blaming the individual misreads a public issue.",
  "related": ["Sociological imagination", "Private troubles"]},

 {"topic": "Monobloc chair", "difficulty": "medium",
  "question": "Why does the lecture open with the mass-produced monobloc plastic chair?",
  "options": ["A. to show a mundane object is sociologically significant",
              "B. to argue design history is the core of sociology",
              "C. to prove cheap objects have no social meaning",
              "D. to celebrate the genius of industrial designers"],
  "correct_answer": "A",
  "explanation": "The monobloc — cheap, mass-produced, ignored — is 'making something out of nothing', showing the mundane is worth study.",
  "related": ["Monobloc chair", "Everyday life"]},

 {"topic": "Highmore", "difficulty": "medium",
  "question": "Ben Highmore's point about answering 'nothing much' to 'what have you been up to?' is that:",
  "options": ["A. ordinary life is never 'nothing', only 'nothing much'",
              "B. most people genuinely do nothing much at all",
              "C. small talk should always be avoided",
              "D. ordinary life is too trivial to study"],
  "correct_answer": "A",
  "explanation": "Highmore (2011) insists the 'nothing much' of ordinary life is full of social activity worth examining.",
  "related": ["Highmore", "Everyday life"]},

 {"topic": "Everyday life", "difficulty": "easy",
  "question": "'Everyday life' is best defined as:",
  "options": ["A. the taken-for-granted, routine parts of daily life",
              "B. the rare, dramatic events of a lifetime",
              "C. the formal rituals of the state and church",
              "D. the private thoughts we never act upon"],
  "correct_answer": "A",
  "explanation": "Everyday life refers to the common-sensical, mundane, routine activities we all take for granted.",
  "related": ["Everyday life", "Features of everyday life"]},

 {"topic": "Toothbrushing", "difficulty": "hard",
  "question": "The lecture calls tooth-brushing 'ritualistic' because it is:",
  "options": ["A. based on repetition and habituation",
              "B. performed only on special occasions",
              "C. required by an explicit written law",
              "D. done differently every single time"],
  "correct_answer": "A",
  "explanation": "As a ritual, brushing rests on repetition and habituation; each person develops their own methods over time.",
  "related": ["Toothbrushing", "Everyday life"]},

 {"topic": "Toothbrushing", "difficulty": "hard",
  "question": "Learning the 'proper way' to brush until it feels natural is described as:",
  "options": ["A. an embodied practice acquired through socialisation",
              "B. an instinct we are simply born with",
              "C. a purely biological reflex action",
              "D. a one-off choice made in adulthood"],
  "correct_answer": "A",
  "explanation": "Embodied practice means socialisation and training in the correct technique, which becomes familiar and internalised.",
  "related": ["Toothbrushing", "Structure"]},

 {"topic": "Toothbrushing", "difficulty": "medium",
  "question": "That we 'can't imagine anyone NOT brushing their teeth' expresses:",
  "options": ["A. a social norm, a shared expectation",
              "B. a formal law with legal penalties",
              "C. a purely individual preference",
              "D. a biological need for survival"],
  "correct_answer": "A",
  "explanation": "The sense that everyone does it marks brushing as a social norm — a shared expectation about behaviour.",
  "related": ["Toothbrushing", "Deviance"]},

 {"topic": "Toothbrushing", "difficulty": "medium",
  "question": "Saying brushing norms are 'tied to age, class, gender and race' makes the point that:",
  "options": ["A. personal habits are socially structured, not just individual",
              "B. hygiene is identical across every single social group",
              "C. class has no bearing on daily routines",
              "D. private habits are beyond sociology's reach"],
  "correct_answer": "A",
  "explanation": "A private-seeming act is patterned by social position — the recurring theme that the personal is social.",
  "related": ["Toothbrushing", "Class"]},

 {"topic": "Idealised beauty", "difficulty": "medium",
  "question": "The lecture traces the modern demand for a 'perfect smile' to:",
  "options": ["A. Hollywood and idealised standards of beauty",
              "B. medieval European court fashion",
              "C. ancient Roman medical practice",
              "D. the invention of the toothbrush itself"],
  "correct_answer": "A",
  "explanation": "The 'perfect smile' originates in Hollywood, where perfectly white teeth became an idealised beauty requirement.",
  "related": ["Idealised beauty", "Toothbrushing"]},

 {"topic": "Structural inequality", "difficulty": "hard",
  "question": "The 'unseen dentist' — dentists clustering in middle-class areas — illustrates:",
  "options": ["A. structural inequality between haves and have-nots",
              "B. a free market working perfectly for everyone",
              "C. individual laziness among rural patients",
              "D. the irrelevance of geography to health",],
  "correct_answer": "A",
  "explanation": "Unequal access to dental care exposes structural inequality and power differences between rich and poor.",
  "related": ["Structural inequality", "Medicalisation"]},

 {"topic": "Global capitalism", "difficulty": "hard",
  "question": "Most toothpaste brands being owned by a few multinationals makes the point that:",
  "options": ["A. everyday consumption sits inside global capitalism",
              "B. consumers enjoy truly unlimited free choice",
              "C. small local firms dominate the market",
              "D. branding has no effect on what we buy"],
  "correct_answer": "A",
  "explanation": "A handful of corporations control production and supply, so the apparent variety of choice is largely an illusion.",
  "related": ["Global capitalism", "Structural inequality"]},

 {"topic": "Medicalisation", "difficulty": "hard",
  "question": "Medicine's monopoly of expert knowledge over the human body is called:",
  "options": ["A. medicalisation", "B. socialisation",
              "C. reflexivity", "D. secularisation"],
  "correct_answer": "A",
  "explanation": "The 'unseen dentist' example introduces medicalisation — medicine holding a monopoly of knowledge over the body.",
  "related": ["Medicalisation", "Structural inequality"]},

 {"topic": "Sociology and comedy", "difficulty": "medium",
  "question": "Peter Berger argued a social scientist blind to the comic dimension will:",
  "options": ["A. miss essential features of social reality",
              "B. produce more objective, rigorous work",
              "C. avoid all bias in their findings",
              "D. understand society far more deeply"],
  "correct_answer": "A",
  "explanation": "Berger (1970) held that the comic dimension reveals essential features of social reality that are otherwise missed.",
  "related": ["Sociology and comedy", "Reflexivity"]},

 {"topic": "Sociology and comedy", "difficulty": "hard",
  "question": "Zijderveld compared the scrutinising sociologist to which figure?",
  "options": ["A. the fool holding up a mirror to society",
              "B. the king who issues the laws to society",
              "C. the priest blessing the community",
              "D. the soldier defending the nation"],
  "correct_answer": "A",
  "explanation": "Zijderveld (1997) likened the sociologist to the traditional fool who holds up a mirror to show people themselves.",
  "related": ["Sociology and comedy", "Reflexivity"]},

 {"topic": "Sociology and comedy", "difficulty": "medium",
  "question": "In what way is sociology LIKE comedy, according to the lecture?",
  "options": ["A. both hold everyday customs up to scrutiny",
              "B. both aim mainly to entertain an audience",
              "C. both avoid questioning any authority",
              "D. both rely on invented, fictional data"],
  "correct_answer": "A",
  "explanation": "Like comedy, sociology holds everyday arrangements up to scrutiny and asks whether they make sense, often questioning authority.",
  "related": ["Sociology and comedy", "Defining sociology"]},

 {"topic": "Sociology and comedy", "difficulty": "medium",
  "question": "How does the lecture say sociology DIFFERS from comedy?",
  "options": ["A. its methods are systematic and objective",
              "B. it never examines everyday manners",
              "C. it always avoids specialised concepts",
              "D. it aims only to make people laugh"],
  "correct_answer": "A",
  "explanation": "Unlike comedy, sociology employs more systematic, objective methods and a specialised set of concepts and language.",
  "related": ["Sociology and comedy", "Qualitative methods"]},

 {"topic": "Reflexivity", "difficulty": "hard",
  "question": "When Seinfeld's characters constantly reflect on how to act, they show what sociologists call:",
  "options": ["A. reflexivity", "B. deviance", "C. socialisation", "D. medicalisation"],
  "correct_answer": "A",
  "explanation": "Reflexivity is the ongoing monitoring of the rules of interaction — asking what the rules are and how to read them.",
  "related": ["Reflexivity", "Sociology and comedy"]},

 {"topic": "Micro and macro", "difficulty": "hard",
  "question": "Scott answers the charge that everyday life is 'trivial' by arguing that:",
  "options": ["A. everyday life is the wider picture in miniature",
              "B. big events have nothing to do with small acts",
              "C. only large institutions deserve real study",
              "D. daily routines truly are of no importance"],
  "correct_answer": "A",
  "explanation": "Scott's core claim: micro-level small-scale practices relate to and are shaped by macro-level patterns.",
  "related": ["Micro and macro", "Agency and structure"]},

 {"topic": "Agency and structure", "difficulty": "medium",
  "question": "Social order, disorder and change, Scott says, reflect the relationship between:",
  "options": ["A. individual and society, agency and structure",
              "B. profit and loss in the marketplace",
              "C. nature and the physical environment",
              "D. past and future technological change"],
  "correct_answer": "A",
  "explanation": "Everyday life expresses the relationship between individual and society, agency and structure, process and regularity.",
  "related": ["Agency and structure", "Micro and macro"]},

 {"topic": "Structure", "difficulty": "medium",
  "question": "In sociology, 'structure' refers to:",
  "options": ["A. the social rules we largely conform to",
              "B. the physical buildings that a society constructs",
              "C. an individual's freedom to rebel",
              "D. the biology of the human body"],
  "correct_answer": "A",
  "explanation": "Structure is the social rules — from parents and teachers to the law — that most of us conform to most of the time.",
  "related": ["Structure", "Agency"]},

 {"topic": "Agency", "difficulty": "medium",
  "question": "'Agency' refers to:",
  "options": ["A. the capacity to express individuality and challenge norms",
              "B. the fixed rules society imposes on everyone else",
              "C. a government office that enforces law",
              "D. the inability to act against structure"],
  "correct_answer": "A",
  "explanation": "Agency is the individual's capacity to express individuality, think differently and challenge restrictive norms.",
  "related": ["Agency", "Structure"]},

 {"topic": "Deviance", "difficulty": "easy",
  "question": "Someone who refuses to conform to social structure is typically labelled:",
  "options": ["A. deviant", "B. reflexive", "C. structural", "D. quotidian"],
  "correct_answer": "A",
  "explanation": "Those who do not conform to social rules are often seen as deviant.",
  "related": ["Deviance", "Structure"]},

 {"topic": "Durkheim on deviance", "difficulty": "hard",
  "question": "Durkheim argued that deviance is:",
  "options": ["A. functional, uniting 'us' against 'them'",
              "B. purely destructive of every society",
              "C. entirely a matter of individual choice",
              "D. completely absent from healthy groups"],
  "correct_answer": "A",
  "explanation": "For Durkheim (1893) deviance is functional: labelling a rule-breaker as deviant reinforces the group's shared values.",
  "related": ["Durkheim on deviance", "Deviance"]},

 {"topic": "Quotidian space", "difficulty": "hard",
  "question": "In Moran's four types of 'quotidian space', a 'non-place' is:",
  "options": ["A. a transit space such as a bus or station",
              "B. a private family home that is full of memories",
              "C. a workplace where people earn a wage",
              "D. a sacred site of religious worship"],
  "correct_answer": "A",
  "explanation": "Moran (2005) lists workspaces, urban/mobile spaces, living spaces and non-places — the last being transit spaces.",
  "related": ["Quotidian space", "Everyday life"]},

 {"topic": "Features of everyday life", "difficulty": "hard",
  "question": "Scott says everyday life is mundane, private and also:",
  "options": ["A. routine, repetitive and rhythmic",
              "B. rare, dramatic and unpredictable",
              "C. formal, official and ceremonial",
              "D. secret, hidden and unknowable"],
  "correct_answer": "A",
  "explanation": "The three defining features are mundane and unremarkable, private and personal, and routine, repetitive and rhythmic.",
  "related": ["Features of everyday life", "Everyday life"]},

 {"topic": "Features of everyday life", "difficulty": "hard",
  "question": "The claim that everyday life is 'habitual in nature' is attributed to:",
  "options": ["A. Felski", "B. Bennett", "C. Martin", "D. Lefebvre"],
  "correct_answer": "A",
  "explanation": "Felski (1999) characterised everyday life as habitual, which is what makes it feel so familiar.",
  "related": ["Features of everyday life", "Connective tissue"]},

 {"topic": "Elusiveness", "difficulty": "hard",
  "question": "Martin (2003) describes everyday phenomena as 'obvious to the point of...':",
  "options": ["A. elusiveness", "B. triviality", "C. absurdity", "D. rigidity"],
  "correct_answer": "A",
  "explanation": "Martin's phrase is 'obvious to the point of elusiveness' — the everyday is so pervasive it slips from view.",
  "related": ["Elusiveness", "Power in the everyday"]},

 {"topic": "Connective tissue", "difficulty": "hard",
  "question": "Everyday phenomena are called the 'connective tissue' holding everything together by:",
  "options": ["A. Bennett", "B. Felski", "C. Martin", "D. Sacks"],
  "correct_answer": "A",
  "explanation": "Bennett (2004) called the everyday the 'connective tissue' forming the background against which experience stands out.",
  "related": ["Connective tissue", "Features of everyday life"]},

 {"topic": "Power in the everyday", "difficulty": "medium",
  "question": "Martin (2003) insists the everyday is NOT trivial because it is:",
  "options": ["A. infused with power, politics and history",
              "B. merely a set of harmless routines",
              "C. separate from all social structures",
              "D. beyond the reach of any analysis"],
  "correct_answer": "A",
  "explanation": "Martin reminds us the everyday world is infused with power, politics and historical significance.",
  "related": ["Power in the everyday", "Elusiveness"]},

 {"topic": "Absent presence", "difficulty": "hard",
  "question": "Before it was studied in its own right, Scott says everyday life had an:",
  "options": ["A. 'absent presence' in the discipline",
              "B. exclusive focus of every scholar",
              "C. official ban from academic work",
              "D. clearly named field of its own"],
  "correct_answer": "A",
  "explanation": "Everyday life had an 'absent presence' — implicitly addressed within earlier studies of poverty, kinship and deviance.",
  "related": ["Absent presence", "Rise of the field"]},

 {"topic": "Key theorists", "difficulty": "hard",
  "question": "Scott names which trio as the most prominent early theorists of everyday life?",
  "options": ["A. Lukács, Lefebvre and de Certeau",
              "B. Durkheim, Weber and Marx",
              "C. Berger, Luckmann and Garfinkel",
              "D. Mills, Highmore and Moran"],
  "correct_answer": "A",
  "explanation": "The most prominent theorists in this mode were Georg Lukács, Henri Lefebvre and Michel de Certeau.",
  "related": ["Key theorists", "Lukács"]},

 {"topic": "Lukács", "difficulty": "hard",
  "question": "Lukács warned that being too immersed in daily routine produces:",
  "options": ["A. a 'pre-reflective acceptance' of life",
              "B. a heightened political awareness",
              "C. a creative resistance to authority",
              "D. a total escape from all structure"],
  "correct_answer": "A",
  "explanation": "Lukács's 'pre-reflective acceptance' stops people realising their potential or living authentically.",
  "related": ["Lukács", "Key theorists"]},

 {"topic": "Lefebvre", "difficulty": "hard",
  "question": "Applying Marx, Lefebvre argued dreary, repetitive capitalist workplaces kept people in:",
  "options": ["A. false consciousness, alienated from their conditions",
              "B. full awareness of their exploitation",
              "C. permanent open rebellion against bosses",
              "D. complete control of the means of production"],
  "correct_answer": "A",
  "explanation": "Lefebvre held that the factory's repetitive cycles alienated workers and sustained false consciousness.",
  "related": ["Lefebvre", "Global capitalism"]},

 {"topic": "de Certeau", "difficulty": "hard",
  "question": "de Certeau argued people subvert authority by breaking minor everyday rules — a tactic he called:",
  "options": ["A. 'making do'", "B. 'false consciousness'",
              "C. 'pre-reflective acceptance'", "D. 'absent presence'"],
  "correct_answer": "A",
  "explanation": "de Certeau (1984) stressed how people 'do' everyday life creatively and defiantly, resisting through minor rule-breaking.",
  "related": ["de Certeau", "Key theorists"]},

 {"topic": "Berger and Luckmann", "difficulty": "hard",
  "question": "Berger and Luckmann (1967) famously argued that:",
  "options": ["A. we construct social reality through everyday encounters",
              "B. one fixed objective reality exists for all",
              "C. society is determined only by biology",
              "D. individuals have no role in shaping reality"],
  "correct_answer": "A",
  "explanation": "For Berger and Luckmann there is no single objective reality but many local, subjective realities built with others.",
  "related": ["Berger and Luckmann", "Interpretivism"]},

 {"topic": "Interpretivism", "difficulty": "hard",
  "question": "The view that there is no single objective reality, only local realities seen from the insider's view, is central to:",
  "options": ["A. interpretivist sociology",
              "B. positivist sociology",
              "C. structural functionalism",
              "D. Marxist political economy"],
  "correct_answer": "A",
  "explanation": "This tenet informs interpretivist sociology — symbolic interactionists, phenomenologists and ethnomethodologists.",
  "related": ["Interpretivism", "Berger and Luckmann"]},

 {"topic": "Cultural Studies", "difficulty": "medium",
  "question": "Cultural Studies theorists treat the places and artefacts of everyday life as:",
  "options": ["A. 'texts' to be read for their ideologies",
              "B. neutral objects that carry no real meaning",
              "C. purely economic units of value",
              "D. facts to be counted statistically"],
  "correct_answer": "A",
  "explanation": "Cultural Studies reads everyday places and artefacts as 'texts' conveying particular ideologies (Moran 2005).",
  "related": ["Cultural Studies", "Interpretivism"]},

 {"topic": "Studying the everyday", "difficulty": "medium",
  "question": "Garfinkel's contribution to studying everyday life is the technique of:",
  "options": ["A. challenging assumptions by studying broken rules",
              "B. surveying huge populations by questionnaire",
              "C. measuring behaviour in a laboratory",
              "D. reading historical archives for patterns"],
  "correct_answer": "A",
  "explanation": "Garfinkel (1967) urged us to challenge taken-for-granted assumptions; norm-breaking makes implicit rules visible.",
  "related": ["Studying the everyday", "Deviance"]},

 {"topic": "Studying the everyday", "difficulty": "hard",
  "question": "'Making the familiar strange' requires the researcher to:",
  "options": ["A. bracket out prior assumptions and stay descriptive",
              "B. judge each setting by personal morals",
              "C. rely only on their common-sense views",
              "D. avoid observing ordinary settings at all"],
  "correct_answer": "A",
  "explanation": "The first technique is descriptive and analytical, not evaluative — you suspend assumptions about what is normal.",
  "related": ["Studying the everyday", "Interpretivism"]},

 {"topic": "Studying the everyday", "difficulty": "hard",
  "question": "The phrase 'the anthropologist on Mars', viewing the familiar as if never seen, is credited to:",
  "options": ["A. Sacks", "B. Highmore", "C. Garfinkel", "D. Berger"],
  "correct_answer": "A",
  "explanation": "Sacks's 'anthropologist on Mars' captures the detached observer stance; Highmore's own analogy was the detective.",
  "related": ["Studying the everyday", "Making the familiar strange"]},

 {"topic": "Gracia's thesis", "difficulty": "hard",
  "question": "Gracia's thesis is that we laugh at something because in it we see:",
  "options": ["A. the significance of the insignificant",
              "B. the insignificance of the significant",
              "C. the danger of the harmless",
              "D. the sadness of the joyful"],
  "correct_answer": "A",
  "explanation": "Gracia proposes we laugh when we grasp the significance of the insignificant — and cry at the reverse.",
  "related": ["Gracia's thesis", "Gracia on tragedy"]},

 {"topic": "Gracia on tragedy", "difficulty": "hard",
  "question": "By contrast, Gracia says we cry at something because through it we grasp:",
  "options": ["A. the insignificance of the significant",
              "B. the significance of the insignificant",
              "C. the humour of the ordinary",
              "D. the order behind the chaos"],
  "correct_answer": "A",
  "explanation": "Tragedy makes us see that what we hold to be significant is, in the larger scheme, insignificant.",
  "related": ["Gracia on tragedy", "Gracia's thesis"]},

 {"topic": "Comedy vs tragedy", "difficulty": "hard",
  "question": "For Gracia, comedy deals with the ordinary, whereas tragedy deals with subject matter that is:",
  "options": ["A. momentous — love, death and betrayal",
              "B. trivial — errands and small talk",
              "C. technical — machinery and tools",
              "D. financial — profit and loss"],
  "correct_answer": "A",
  "explanation": "Tragedy's subject matter is momentous — love, death, betrayal, virtue, injustice and revenge.",
  "related": ["Comedy vs tragedy", "Gracia on tragedy"]},

 {"topic": "Comedy vs tragedy", "difficulty": "hard",
  "question": "Which everyday example does Gracia give as too insignificant ever to be a tragedy?",
  "options": ["A. non-fat yogurt", "B. a soldier's death",
              "C. a betrayed marriage", "D. a fatal illness"],
  "correct_answer": "A",
  "explanation": "Gracia's own examples are the sale of a van, mail delivery and non-fat yogurt; the distractors are genuine tragic themes.",
  "related": ["Comedy vs tragedy", "Gracia's thesis"]},

 {"topic": "Why comedy dates", "difficulty": "hard",
  "question": "Gracia argues comedy 'dates more easily than tragedy' because:",
  "options": ["A. comedy leans on culture-specific customs",
              "B. tragedy depends on passing fashions",
              "C. comedy addresses universal human themes",
              "D. tragedy is always about trivial matters"],
  "correct_answer": "A",
  "explanation": "Tragedy's shared human core (death, suffering, virtue) ages slowly, while comedy relies on culture-specific customs.",
  "related": ["Why comedy dates", "Comedy vs tragedy"]},

 {"topic": "Show about nothing", "difficulty": "medium",
  "question": "The Seinfeld pitch 'a show about nothing' fits Gracia's argument because:",
  "options": ["A. its significance lies in overlooked everyday life",
              "B. it deliberately avoids all social content",
              "C. it dramatises only momentous events",
              "D. it proves the everyday has no meaning"],
  "correct_answer": "A",
  "explanation": "Seinfeld's characters never think their doings are significant; the series draws out overlooked everyday commonplaces.",
  "related": ["Show about nothing", "Gracia's thesis"]},

 {"topic": "Qualitative methods", "difficulty": "medium",
  "question": "Participant observation, ethnography and focus groups are examples of:",
  "options": ["A. qualitative methods", "B. quantitative methods",
              "C. laboratory experiments", "D. statistical modelling"],
  "correct_answer": "A",
  "explanation": "These are qualitative methods — they capture the depth and quality of participants' experience of the social world.",
  "related": ["Qualitative methods", "Quantitative methods"]},

 {"topic": "Quantitative methods", "difficulty": "medium",
  "question": "The Australian census is used as an example of:",
  "options": ["A. a quantitative method", "B. a qualitative method",
              "C. participant observation", "D. an ethnographic study"],
  "correct_answer": "A",
  "explanation": "The census is quantitative — a large-sample survey producing statistics, trends and snapshots of a changing society.",
  "related": ["Quantitative methods", "Qualitative methods"]},

 {"topic": "Class", "difficulty": "hard",
  "question": "The lecture argues that a person's class:",
  "options": ["A. is not just wealth but also taste and status",
              "B. is decided purely by annual income",
              "C. has no genuine connection to one's lifestyle at all",
              "D. is fixed permanently at birth"],
  "correct_answer": "A",
  "explanation": "The same income can carry very different tastes; class is not just wealth but also status and taste.",
  "related": ["Class", "Cultural capital"]},

 {"topic": "Cultural capital", "difficulty": "hard",
  "question": "The idea that taste and lifestyle act as a marker of status is the concept of:",
  "options": ["A. cultural capital", "B. false consciousness",
              "C. structural inequality", "D. the sociological imagination"],
  "correct_answer": "A",
  "explanation": "Taste as a status marker is cultural capital — the concept behind the 'who could sit on a monobloc' example.",
  "related": ["Cultural capital", "Class"]},

 {"topic": "Context-free object", "difficulty": "hard",
  "question": "Ethan Zuckerman labelled the monobloc chair a:",
  "options": ["A. 'context-free object'", "B. 'connective tissue'",
              "C. 'non-place'", "D. 'context-rich artefact'"],
  "correct_answer": "A",
  "explanation": "Zuckerman calls the monobloc a 'context-free object' — unlike most objects it gives no clue of time or place.",
  "related": ["Context-free object", "Monobloc chair"]},
]

if __name__ == "__main__":
    sys.exit(emit(KEY, META, Q))
