#!/usr/bin/env python3
"""SOCI1010 W6 · Everyday Religion — quiz bank (new guide; META defined inline)."""
import os, sys
HERE = os.path.dirname(os.path.abspath(__file__))
sys.path.insert(0, os.path.join(HERE, "..", "tools"))
from qbank_lib import emit  # noqa

KEY = "soci1010_wk6_everyday_religion.html"
META = {
    "title": "Everyday Religion — Belief, Secularisation & the Consumer Church",
    "subject": "Sociology",
    "unit": "SOCI1010",
    "content": ("Week 6 of Introduction to Sociology: the sociology of religion (Dr Randa Abdel-Fattah) "
                "plus the required reading, Sanders (2016) on corporate megachurches. Covers the sociological "
                "lens and 'lived religion'; the three classical theorists — Durkheim (sacred/profane, collective "
                "effervescence, social solidarity), Marx (opium of the people, false consciousness, alienation, "
                "ideology, and the critiques) and Weber (predestination, inner-worldly asceticism, the spirit of "
                "capitalism, rationalization and disenchantment); the secularisation thesis and its critics (Bruce, "
                "Bouma, Casanova); Australia's religious landscape (Census 2021, new religions, Pentecostal "
                "mega-churches, Bouma's 'shy' dimensions); Sanders' megachurch as an Auge 'non-place' (Willow "
                "Creek, seekers, prosperity gospel, Zizek's false disidentification); and the Islamophobia case study.")
}

Q = [
 {"topic": "The lens", "difficulty": "easy",
  "question": "The 'lived religion' approach is mainly interested in:",
  "options": ["A. the official doctrines a faith teaches",
              "B. religion's embodied, everyday practice",
              "C. proving which religion is true",
              "D. the founding texts of world faiths"],
  "correct_answer": "B",
  "explanation": "Lived religion attends to the embodied, everyday practice of a faith and to how people explain themselves, not to doctrine.",
  "related": ["The lens", "Islam & the secular"]},

 {"topic": "The lens", "difficulty": "medium",
  "question": "In studying religion, sociology deliberately sets aside the question of:",
  "options": ["A. how rituals bind a group",
              "B. the social functions of belief",
              "C. whether any god actually exists",
              "D. how faith shapes everyday life"],
  "correct_answer": "C",
  "explanation": "The truth-claim is bracketed because it is not a social fact; sociology studies religion's meanings and functions instead.",
  "related": ["The lens", "Durkheim"]},

 {"topic": "Durkheim", "difficulty": "easy",
  "question": "For Durkheim, the 'sacred' is best defined as things that are:",
  "options": ["A. set apart and forbidden",
              "B. ordinary and used routinely",
              "C. private and personal only",
              "D. modern and newly invented"],
  "correct_answer": "A",
  "explanation": "The sacred is set apart and forbidden, belonging to the supernatural; the profane is the everyday and mundane.",
  "related": ["Durkheim", "The lens"]},

 {"topic": "Durkheim", "difficulty": "medium",
  "question": "Durkheim's definition of religion ties it above all to:",
  "options": ["A. belief in a single high god",
              "B. fear of death and the afterlife",
              "C. private individual experience",
              "D. a united moral community"],
  "correct_answer": "D",
  "explanation": "Religion is a unified system of beliefs and practices about sacred things that unites adherents into one moral community, a 'Church'.",
  "related": ["Durkheim", "Marx"]},

 {"topic": "Durkheim", "difficulty": "hard",
  "question": "When a congregation reveres its sacred symbol, Durkheim argues it is really revering:",
  "options": ["A. the supernatural power itself",
              "B. society, or the group itself",
              "C. the worshipper's own soul",
              "D. the founder of the religion"],
  "correct_answer": "B",
  "explanation": "The sacred is a symbol of the collective, so worship recharges social solidarity — society becoming conscious of itself.",
  "related": ["Durkheim", "Sanders' megachurch"]},

 {"topic": "Durkheim", "difficulty": "medium",
  "question": "In Durkheim's terms, a community turning ordinary bread into a holy object is an act of:",
  "options": ["A. sacralisation",
              "B. alienation",
              "C. rationalization",
              "D. disenchantment"],
  "correct_answer": "A",
  "explanation": "Sacralisation is the social act of setting something apart as sacred; nothing is sacred in itself.",
  "related": ["Durkheim", "Weber"]},

 {"topic": "Marx", "difficulty": "easy",
  "question": "Marx calls religion the 'opium of the people' because it:",
  "options": ["A. is banned under true socialism",
              "B. originated among the wealthy elite",
              "C. dulls the felt pain of exploitation",
              "D. explains the natural world scientifically"],
  "correct_answer": "C",
  "explanation": "Religion offers an illusory comfort that numbs the suffering caused by exploitation, so the oppressed tolerate their conditions.",
  "related": ["Marx", "Marx critique"]},

 {"topic": "Marx", "difficulty": "hard",
  "question": "To say religion is 'false consciousness' means the comfort it gives is:",
  "options": ["A. genuine but wrongly explained",
              "B. faked by insincere believers",
              "C. available only to the rich",
              "D. proof that god exists"],
  "correct_answer": "A",
  "explanation": "The comfort is genuine, but its source is misread — the ache comes from exploitation, yet the cure is relocated to heaven.",
  "related": ["Marx", "Durkheim"]},

 {"topic": "Marx", "difficulty": "medium",
  "question": "Religion produces alienation, for Marx, chiefly because people:",
  "options": ["A. spend money on churches they lack",
              "B. hand their own agency to god",
              "C. gather too often in crowds",
              "D. read sacred texts too literally"],
  "correct_answer": "B",
  "explanation": "Humans project their own power onto a god and then feel subordinate to it; if conditions are 'God's will', there is no reason to change them.",
  "related": ["Marx", "Marx critique"]},

 {"topic": "Marx", "difficulty": "medium",
  "question": "'Ideology', in the Marxist sense used here, refers to beliefs that:",
  "options": ["A. can be tested by careful science",
              "B. unite a moral community",
              "C. arise only in secular societies",
              "D. naturalise existing power relations"],
  "correct_answer": "D",
  "explanation": "Ideology justifies existing power relations and makes a changeable, historical arrangement look eternal and inevitable.",
  "related": ["Marx", "Sanders' megachurch"]},

 {"topic": "Marx critique", "difficulty": "hard",
  "question": "Martin Luther King Jr and Arab Spring clerics are raised to show that religion can:",
  "options": ["A. drive rebellion, not only passivity",
              "B. always side with the powerful",
              "C. disappear once societies modernise",
              "D. exist without a moral community"],
  "correct_answer": "A",
  "explanation": "Both are cases of religion motivating revolt against oppression — a weakness in Marx's assumption that religion only pacifies.",
  "related": ["Marx critique", "Marx"]},

 {"topic": "Marx critique", "difficulty": "medium",
  "question": "The Soviet gulag, Nazi Germany and the Khmer Rouge are cited to argue that:",
  "options": ["A. religion causes most modern violence",
              "B. secular states are always peaceful",
              "C. oppression needs no religion at all",
              "D. all ideologies are basically religious"],
  "correct_answer": "C",
  "explanation": "These atheist regimes produced mass oppression, so religion cannot be the essential engine of oppression Marx implies.",
  "related": ["Marx critique", "Marx"]},

 {"topic": "Weber", "difficulty": "easy",
  "question": "Weber's Protestant Ethic sets out to explain why capitalism first developed in:",
  "options": ["A. ancient trading empires",
              "B. Protestant parts of Europe",
              "C. the secular modern USA",
              "D. Catholic southern Europe"],
  "correct_answer": "B",
  "explanation": "Weber's puzzle is why capitalism arose specifically in Europe, and specifically where Protestantism took hold.",
  "related": ["Weber", "Marx"]},

 {"topic": "Weber", "difficulty": "hard",
  "question": "Calvin's doctrine of predestination fuelled capitalist conduct because believers:",
  "options": ["A. sought signs of election in success",
              "B. could buy salvation with donations",
              "C. were told wealth was sinful",
              "D. expected priests to save them"],
  "correct_answer": "A",
  "explanation": "Unable to change a pre-decided fate, Calvinists read worldly success as a sign of being God's elect, so hard work and thrift became duties.",
  "related": ["Weber", "Prosperity gospel"]},

 {"topic": "Weber", "difficulty": "hard",
  "question": "Protestant asceticism helped build capital because hard-won profits tended to be:",
  "options": ["A. donated entirely to the church",
              "B. spent on visible luxuries",
              "C. taxed away by the state",
              "D. reinvested rather than spent"],
  "correct_answer": "D",
  "explanation": "Work hard, succeed, and refuse to spend, and the money can only be reinvested — self-denial plus profit equals capital accumulation.",
  "related": ["Weber", "Marx"]},

 {"topic": "Weber", "difficulty": "medium",
  "question": "The 'spirit of capitalism' names Weber's claim that capitalism became:",
  "options": ["A. purely a mode of production",
              "B. a sign of god's disfavour",
              "C. a moral good and duty",
              "D. a passing historical accident"],
  "correct_answer": "C",
  "explanation": "Capitalism was reframed as a moral force — more than Marx's mode of production, it carried an ethos with religious roots.",
  "related": ["Weber", "Marx"]},

 {"topic": "Weber", "difficulty": "hard",
  "question": "Calling the Protestant ethic and capitalism an 'elective affinity' means one:",
  "options": ["A. directly caused the other",
              "B. fit and reinforced the other",
              "C. was a disguise for the other",
              "D. slowly replaced the other"],
  "correct_answer": "B",
  "explanation": "Elective affinity means two things fit so well they select for and reinforce each other — not simple one-way causation.",
  "related": ["Weber", "Sanders' megachurch"]},

 {"topic": "Weber", "difficulty": "medium",
  "question": "Weber's 'disenchantment' refers to the world progressively losing its:",
  "options": ["A. magic and mystery",
              "B. economic inequality",
              "C. moral communities",
              "D. work discipline"],
  "correct_answer": "A",
  "explanation": "As rational calculation spreads (rationalization), mystery and the sacred drain out of the world — its disenchantment.",
  "related": ["Weber", "Secularisation"]},

 {"topic": "Secularisation", "difficulty": "easy",
  "question": "The secularisation thesis predicts that modernisation will:",
  "options": ["A. spread religion across the globe",
              "B. merge all faiths into one",
              "C. shrink religion's structure and influence",
              "D. return society to medieval belief"],
  "correct_answer": "C",
  "explanation": "The thesis holds that as societies modernise, religion's structure and influence decline and the sacred retreats to the private realm.",
  "related": ["Secularisation", "Weber"]},

 {"topic": "Secularisation", "difficulty": "hard",
  "question": "A central critique is that the secularisation thesis measures religion by a model that is:",
  "options": ["A. Christian and institutional",
              "B. Eastern and mystical",
              "C. private and individual",
              "D. political and legal"],
  "correct_answer": "A",
  "explanation": "Using a Christian, institutional-Church yardstick (membership, weekly attendance) makes non-institutional religiosity register as zero.",
  "related": ["Secularisation", "Australia"]},

 {"topic": "Secularisation", "difficulty": "medium",
  "question": "Casanova reframes secularisation less as decline than as religion being:",
  "options": ["A. abolished by the state",
              "B. proven false by science",
              "C. revived as fundamentalism",
              "D. differentiated and privatised"],
  "correct_answer": "D",
  "explanation": "Casanova separates decline from differentiation, arguing religion is marginalised to a privatised sphere rather than erased.",
  "related": ["Secularisation", "Australia"]},

 {"topic": "Secularisation", "difficulty": "medium",
  "question": "The USA is the awkward case for the secularisation thesis because it is:",
  "options": ["A. modern and thoroughly secular",
              "B. modern yet highly religious",
              "C. pre-modern and highly religious",
              "D. modern with no new religions"],
  "correct_answer": "B",
  "explanation": "In the 1990s data 96% of Americans believed in God and 45% attended weekly — a highly modern yet highly religious society.",
  "related": ["Secularisation", "Australia"]},

 {"topic": "Australia", "difficulty": "easy",
  "question": "The 2021 Australian Census marked the point at which:",
  "options": ["A. 'no religion' became the largest response",
              "B. Christianity regained a clear majority",
              "C. Islam overtook all other faiths",
              "D. weekly attendance rose sharply"],
  "correct_answer": "A",
  "explanation": "Christianity fell below half the population and 'no religion' became the single largest response — a change in form as much as decline.",
  "related": ["Australia", "Secularisation"]},

 {"topic": "Australia", "difficulty": "medium",
  "question": "The lecture describes the Pentecostal mega-church as:",
  "options": ["A. institutional and highly traditional",
              "B. small, local and volunteer-run",
              "C. 'not institutional, but organised'",
              "D. hostile to business and marketing"],
  "correct_answer": "C",
  "explanation": "It rejects old denominational bureaucracy yet runs like a slick enterprise around business, entertainment and a success gospel.",
  "related": ["Australia", "Sanders' megachurch"]},

 {"topic": "Australia", "difficulty": "hard",
  "question": "Bouma's five dimensions capture Australian religiosity as broadly:",
  "options": ["A. intense, frequent and central",
              "B. low-key, occasional and marginal",
              "C. political, public and combative",
              "D. Eastern, mystical and private"],
  "correct_answer": "B",
  "explanation": "Bouma's 'shy' religiosity tends to low intensity and expressivity, infrequent attendance and a marginal social location.",
  "related": ["Australia", "Islam & the secular"]},

 {"topic": "Australia", "difficulty": "hard",
  "question": "A secular Australian taking up yoga or meditation best illustrates:",
  "options": ["A. the triumph of the secular thesis",
              "B. a return to institutional religion",
              "C. false consciousness at work",
              "D. religiosity changing its form"],
  "correct_answer": "D",
  "explanation": "A religious disciplinary practice migrates into everyday life — the 'change of form' the institutional yardstick misses.",
  "related": ["Australia", "Secularisation"]},

 {"topic": "Sanders' megachurch", "difficulty": "medium",
  "question": "Augé's 'non-place' is a site that is:",
  "options": ["A. stripped of history and identity",
              "B. rich in collective memory",
              "C. sacred and set firmly apart",
              "D. owned by one community"],
  "correct_answer": "A",
  "explanation": "A non-place (airport lounge, mall) lacks historical, cultural and relational reference points, so you feel 'nowhere in particular'.",
  "related": ["Sanders' megachurch", "Durkheim"]},

 {"topic": "Sanders' megachurch", "difficulty": "medium",
  "question": "Sanders' 'corporate' megachurch deliberately copies the:",
  "options": ["A. structure of a medieval cathedral",
              "B. rituals of the early church",
              "C. model of the modern corporation",
              "D. layout of a university campus"],
  "correct_answer": "C",
  "explanation": "It adopts CEO-pastors, marketing, audits and franchising — the corporation, which Deleuze says has 'sublimated' the factory.",
  "related": ["Sanders' megachurch", "Weber"]},

 {"topic": "Sanders' megachurch", "difficulty": "medium",
  "question": "Bill Hybels built Willow Creek after market research found people thought church was:",
  "options": ["A. too political and divisive",
              "B. boring and off-putting",
              "C. too focused on money",
              "D. too small and intimate"],
  "correct_answer": "B",
  "explanation": "Hybels polled people on what they disliked about church; the top answer was 'boring', so he rebuilt it as entertainment.",
  "related": ["Sanders' megachurch", "Prosperity gospel"]},

 {"topic": "Prosperity gospel", "difficulty": "hard",
  "question": "Corporate megachurches market a 'prosperity gospel' to 'seekers' rather than:",
  "options": ["A. an entertaining spectacle",
              "B. giant suburban campuses",
              "C. sermons and merchandise",
              "D. fire-and-brimstone judgment"],
  "correct_answer": "D",
  "explanation": "A 'Christianity Lite' of optimism and felt needs replaces guilt and judgment, to appeal to 'unchurched Harry and Mary'.",
  "related": ["Prosperity gospel", "Sanders' megachurch"]},

 {"topic": "Sanders' megachurch", "difficulty": "hard",
  "question": "'False disidentification' (Žižek) describes worshippers who:",
  "options": ["A. feel outside consumerism while performing it",
              "B. openly reject all religious tradition",
              "C. consciously embrace consumer capitalism",
              "D. withdraw fully from modern society"],
  "correct_answer": "A",
  "explanation": "They cognitively distance themselves from consumerism while behaviourally reproducing it — the felt distance is what lets the ideology work.",
  "related": ["Sanders' megachurch", "Marx"]},

 {"topic": "Sanders' megachurch", "difficulty": "medium",
  "question": "Selling standardised, franchised sermons across sister churches makes the megachurch a case of:",
  "options": ["A. collective effervescence",
              "B. disenchantment",
              "C. McDonaldization",
              "D. alienation"],
  "correct_answer": "C",
  "explanation": "Efficiency, calculability, predictability and control applied to worship — Sanders notes the 'McDonaldized homogeneity' of buyable sermons.",
  "related": ["Sanders' megachurch", "Weber"]},

 {"topic": "Islam & the secular", "difficulty": "medium",
  "question": "The Islamophobia case study shows that calling a society 'secular' is not the same as it being:",
  "options": ["A. modern and industrialised",
              "B. neutral about religion",
              "C. wealthy and democratic",
              "D. Christian in heritage"],
  "correct_answer": "B",
  "explanation": "Secularism carries its own Christian-shaped, 'shy' norm for how much religion may show, so visible Muslim devotion is judged excessive.",
  "related": ["Islam & the secular", "Australia"]},

 {"topic": "Islam & the secular", "difficulty": "hard",
  "question": "Applying 'lived religion' to Muslim Australians means studying their:",
  "options": ["A. everyday practice and self-understanding",
              "B. conformity to an institutional church",
              "C. scores on a secular attendance scale",
              "D. agreement with classical theorists"],
  "correct_answer": "A",
  "explanation": "It looks at actual embodied practice and how people explain themselves, rather than scoring them against an institutional or secular template.",
  "related": ["Islam & the secular", "The lens"]},
]

if __name__ == "__main__":
    sys.exit(emit(KEY, META, Q))
