#!/usr/bin/env python3
"""SOCI1010 W4 · Researching Everyday Life (ethnography & the go-along) — regenerated bank."""
import os, sys, json
HERE = os.path.dirname(os.path.abspath(__file__))
sys.path.insert(0, os.path.join(HERE, "..", "tools"))
from qbank_lib import emit  # noqa

KEY = "soci1010_wk4_researching_everyday_life.html"
BANK = json.load(open(os.path.join(HERE, "..", "..", "guide_quizzes.json"), encoding="utf-8"))
META = {k: BANK[KEY][k] for k in ("title", "subject", "unit", "content")}

Q = [
 {"topic": "Ethnomethodology", "difficulty": "easy",
  "question": "Which sociologist coined 'ethnomethodology' and used breaching experiments?",
  "options": ["A. Harold Garfinkel", "B. Erving Goffman",
              "C. Max Weber", "D. Georg Simmel"],
  "correct_answer": "A",
  "explanation": "Garfinkel introduced ethnomethodology in Studies in Ethnomethodology (1967) and used breaching experiments.",
  "related": ["Ethnomethodology", "Breaching experiments"]},

 {"topic": "Breaching experiments", "difficulty": "easy",
  "question": "A breaching experiment works by:",
  "options": ["A. deliberately breaking a tacit rule to expose it",
              "B. carefully obeying every social rule closely",
              "C. surveying a very large random sample of people",
              "D. running a controlled laboratory experiment"],
  "correct_answer": "A",
  "explanation": "Breaking an unwritten rule — like over-answering 'How are you?' — makes it suddenly visible.",
  "related": ["Breaching experiments", "Ethnomethodology"]},

 {"topic": "Goffman — dramaturgy", "difficulty": "easy",
  "question": "In Goffman's dramaturgy, a waiter relaxing out of role in the kitchen is on the:",
  "options": ["A. back stage", "B. front stage", "C. centre stage", "D. off stage"],
  "correct_answer": "A",
  "explanation": "Back stage is where the performance relaxes; front stage is where one performs to the audience.",
  "related": ["Goffman — dramaturgy", "Total institution"]},

 {"topic": "Ethnography — meaning", "difficulty": "easy",
  "question": "The word 'ethnography' breaks down to mean, roughly:",
  "options": ["A. writing about people or culture",
              "B. counting large populations statistically",
              "C. studying only ancient history",
              "D. measuring the physical body"],
  "correct_answer": "A",
  "explanation": "Ethno = people/culture, graphy = writing; ethnography means writing about people and culture.",
  "related": ["Ethnography — meaning", "Ethnography — two components"]},

 {"topic": "Qualitative vs quantitative", "difficulty": "easy",
  "question": "Which method best captures people's subjective, lived experience?",
  "options": ["A. qualitative research", "B. a national census",
              "C. an opinion poll", "D. a laboratory experiment"],
  "correct_answer": "A",
  "explanation": "Qualitative research prioritises meaning and lived experience; the census and polls are quantitative.",
  "related": ["Qualitative vs quantitative", "Ethnography — meaning"]},

 {"topic": "History — Malinowski", "difficulty": "easy",
  "question": "Bronisław Malinowski's foundational ethnographic fieldwork was conducted in the:",
  "options": ["A. Trobriand Islands", "B. Shetland Islands",
              "C. Chicago slums", "D. Parisian suburbs"],
  "correct_answer": "A",
  "explanation": "Malinowski studied the Trobriand Islands (1915–19); Goffman's PhD fieldwork was in the Shetlands.",
  "related": ["History — Malinowski", "Malinowski — method"]},

 {"topic": "The go-along", "difficulty": "easy",
  "question": "The 'go-along' method, as Kusenbach defines it, means the researcher:",
  "options": ["A. accompanies an informant on an everyday outing",
              "B. interviews an informant in a quiet office",
              "C. mails a survey to many strangers",
              "D. watches an informant on hidden camera"],
  "correct_answer": "A",
  "explanation": "A go-along walks or rides with the informant on their own routine trip, asking questions along the way.",
  "related": ["The go-along", "Kusenbach — five themes"]},

 {"topic": "Kusenbach — five themes", "difficulty": "easy",
  "question": "Which is one of Kusenbach's five themes the go-along is suited to explore?",
  "options": ["A. spatial practices", "B. economic markets",
              "C. genetic inheritance", "D. chemical reactions"],
  "correct_answer": "A",
  "explanation": "Kusenbach's five themes are perception, spatial practices, biographies, social architecture and social realms.",
  "related": ["Kusenbach — five themes", "The go-along"]},

 {"topic": "Weber — self-checkouts", "difficulty": "easy",
  "question": "The lecture frames the self-checkout mainly through which Weberian idea?",
  "options": ["A. rationalisation and the 'iron cage'",
              "B. the sacred and the profane",
              "C. moral consensus and solidarity",
              "D. class conflict and revolution"],
  "correct_answer": "A",
  "explanation": "Self-checkouts illustrate rationalisation, the iron cage and the irrationality of rationality.",
  "related": ["Weber — self-checkouts", "Rationalisation of space"]},

 {"topic": "Deductive vs inductive", "difficulty": "medium",
  "question": "A researcher watches a class with no prior hypothesis and builds a conclusion from what they see. This is:",
  "options": ["A. inductive", "B. deductive", "C. quantitative", "D. experimental"],
  "correct_answer": "A",
  "explanation": "Building a general conclusion up from specific observations is inductive; deductive starts from a hypothesis.",
  "related": ["Deductive vs inductive", "Emic vs etic"]},

 {"topic": "Emic vs etic", "difficulty": "medium",
  "question": "Knowing that a 'wink' carries a coded insider meaning while a 'blink' is just dust is the:",
  "options": ["A. emic perspective", "B. etic perspective",
              "C. deductive method", "D. quantitative method"],
  "correct_answer": "A",
  "explanation": "The emic perspective is the insider's point of view that distinguishes a meaningful wink from a mere blink.",
  "related": ["Emic vs etic", "Positioned subject"]},

 {"topic": "Ethnography — two components", "difficulty": "medium",
  "question": "Alongside participant observation, the second component of ethnography is:",
  "options": ["A. recording and documenting fieldnotes",
              "B. running a large statistical survey",
              "C. mailing questionnaires to strangers",
              "D. testing a formal hypothesis"],
  "correct_answer": "A",
  "explanation": "The two components are participant observation and the recording and documenting of fieldnotes.",
  "related": ["Ethnography — two components", "Ethnography — meaning"]},

 {"topic": "Positioned subject", "difficulty": "medium",
  "question": "Describing ethnographers as 'positioned subjects' captures the claim that they:",
  "options": ["A. become part of the world they study",
              "B. stay fully detached and objective the whole time",
              "C. never enter the field at all",
              "D. rely only on official statistics"],
  "correct_answer": "A",
  "explanation": "Ethnographers are the research tool; the work is experiential and subjective, so they join the world they study.",
  "related": ["Positioned subject", "Emic vs etic"]},

 {"topic": "Chicago School", "difficulty": "medium",
  "question": "The Chicago School's approach to studying the city is best summarised as:",
  "options": ["A. treating the city as a 'social experiment'",
              "B. surveying the whole city with mailed forms",
              "C. avoiding the city street entirely",
              "D. studying only rural farming villages"],
  "correct_answer": "A",
  "explanation": "Dissatisfied with the survey method, the Chicago School treated the city as a living social experiment studied first-hand.",
  "related": ["Chicago School", "History — Malinowski"]},

 {"topic": "Malinowski — method", "difficulty": "medium",
  "question": "Which practice was central to Malinowski's method?",
  "options": ["A. keeping daily diaries while living among people",
              "B. sending a single brief questionnaire by mail",
              "C. reading old records from a distance",
              "D. running experiments in a laboratory"],
  "correct_answer": "A",
  "explanation": "Malinowski kept daily diaries, learned the language and stayed long-term in the field.",
  "related": ["Malinowski — method", "History — Malinowski"]},

 {"topic": "Total institution", "difficulty": "medium",
  "question": "Goffman's 'total institution' is defined by which feature?",
  "options": ["A. an enclosed, formally administered, cut-off life",
              "B. an open community free to come and go",
              "C. a temporary weekend gathering of friends",
              "D. an online forum with no physical site"],
  "correct_answer": "A",
  "explanation": "A total institution — asylum, prison, monastery, army camp — encloses similar people in a formally administered life.",
  "related": ["Total institution", "Covert observation — Asylums"]},

 {"topic": "Willis — Learning to Labour", "difficulty": "medium",
  "question": "Willis's central explanation for why working-class 'lads' end up in working-class jobs is that:",
  "options": ["A. the lads 'let themselves' through a counter-school culture",
              "B. the lads simply lacked the natural ability",
              "C. the teachers deliberately failed each of the lads",
              "D. the economy offered them no jobs at all"],
  "correct_answer": "A",
  "explanation": "Willis argued the lads consciously reject school via a culture of resistance, steering themselves into working-class jobs.",
  "related": ["Willis — Learning to Labour", "Wacquant / Bourdieu"]},

 {"topic": "Wacquant / Bourdieu", "difficulty": "medium",
  "question": "Wacquant trained as a boxer to honour which Bourdieu claim?",
  "options": ["A. 'we learn by body'", "B. 'the disenchanted world'",
              "C. 'the sacred and profane'", "D. 'the presentation of self'"],
  "correct_answer": "A",
  "explanation": "Bourdieu's 'we learn by body' warrants embodied participation — the sociologist trains as a boxer to understand the gym.",
  "related": ["Wacquant / Bourdieu", "Positioned subject"]},

 {"topic": "Venkatesh", "difficulty": "medium",
  "question": "How did Venkatesh's Robert Taylor Homes research change after his first encounter?",
  "options": ["A. he refocused from poverty onto the gang",
              "B. he abandoned the whole research project entirely",
              "C. he switched to a mailed survey",
              "D. he studied only the police instead"],
  "correct_answer": "A",
  "explanation": "Held at first, then invited to 'live with people', Venkatesh refocused from poverty generally onto the gang.",
  "related": ["Venkatesh", "Chicago School"]},

 {"topic": "Go-along — natural vs contrived", "difficulty": "medium",
  "question": "For authenticity, Kusenbach argues a go-along should ideally be:",
  "options": ["A. natural, following a trip they'd take anyway",
              "B. staged along a route chosen by the researcher",
              "C. replaced entirely by a phone survey",
              "D. done only inside a closed office"],
  "correct_answer": "A",
  "explanation": "Natural go-alongs track routine trips — same day, time and route — preserving authenticity.",
  "related": ["Go-along — natural vs contrived", "The go-along"]},

 {"topic": "Go-along — why interviews fall short", "difficulty": "medium",
  "question": "A key limit of the sit-down interview that the go-along overcomes is that it:",
  "options": ["A. removes people from the place being discussed",
              "B. always captures the whole environment perfectly well",
              "C. is always faster than a go-along",
              "D. needs no informant at all"],
  "correct_answer": "A",
  "explanation": "Interviews are static and pull informants out of place, hiding the pre-reflective, trivial detail a go-along reveals.",
  "related": ["Go-along — why interviews fall short", "Go-along — natural vs contrived"]},

 {"topic": "Rationalisation of space", "difficulty": "medium",
  "question": "Replacing 10 staffed lanes with 20 self-service machines is an example of:",
  "options": ["A. rationalisation of space", "B. moral consensus",
              "C. banal nationalism", "D. emotional labour"],
  "correct_answer": "A",
  "explanation": "Reconfiguring the shop floor around self-checkout machines is the 'rationalisation of space'.",
  "related": ["Rationalisation of space", "Weber — self-checkouts"]},

 {"topic": "Perception — relevance", "difficulty": "hard",
  "question": "Ross calls an overgrown house a 'jungle' eyesore while Jill calls the same house lovely. This shows:",
  "options": ["A. pre-existing 'relevances' filter perception first",
              "B. everyone perceives a scene identically",
              "C. words always carry a single fixed meaning",
              "D. perception is purely biological, not social"],
  "correct_answer": "A",
  "explanation": "The same word carrying opposite meanings shows perception is filtered by pre-existing relevances — tastes and values.",
  "related": ["Perception — relevance", "Spatial practices — thickening"]},

 {"topic": "Spatial practices — thickening", "difficulty": "hard",
  "question": "Tony times his walk and buys a lottery ticket for 'fun'. Under which theme does this fall?",
  "options": ["A. spatial practices, since 'thickening' is unobservable",
              "B. perception, since it involves the senses",
              "C. biographies, since it recalls the past",
              "D. social realms, since it is fully public"],
  "correct_answer": "A",
  "explanation": "Reframing a routine as fun or competition is a spatial practice — 'thickening' — that a static interview cannot observe.",
  "related": ["Spatial practices — thickening", "Kusenbach — five themes"]},

 {"topic": "Biographies vs social architecture", "difficulty": "hard",
  "question": "Tony recalling his post-war home when passing an old bungalow is which theme?",
  "options": ["A. biographies", "B. spatial practices",
              "C. perception", "D. social architecture"],
  "correct_answer": "A",
  "explanation": "A personal landmark triggering memory is the 'biographies' theme — the environment sparking one's own life story.",
  "related": ["Biographies vs social architecture", "Kusenbach — five themes"]},

 {"topic": "Social architecture", "difficulty": "hard",
  "question": "Jill reading a 'rental' and a model's 'wonderful' house as a status map for herself is:",
  "options": ["A. comparing and positioning", "B. perception and relevance",
              "C. spatial practice", "D. biographies"],
  "correct_answer": "A",
  "explanation": "Reading other houses as a status map to place oneself is 'comparing and positioning' within social architecture.",
  "related": ["Social architecture", "Perception — relevance"]},

 {"topic": "Social realms — matching method", "difficulty": "hard",
  "question": "Kusenbach argues the lone, transient observer suits the public realm because it rests on:",
  "options": ["A. categoric, anonymous knowing rather than personal",
              "B. personal knowing rather than anonymous",
              "C. no knowing of others at all",
              "D. purely statistical knowing of crowds"],
  "correct_answer": "A",
  "explanation": "In public space anonymity reigns, so conduct rests on categoric (anonymous) rather than personal knowing.",
  "related": ["Social realms — matching method", "The go-along"]},

 {"topic": "Familiar vs unfamiliar", "difficulty": "hard",
  "question": "Ethnography at home, the lecture says, makes the:",
  "options": ["A. 'familiar unfamiliar' at home for sociology",
              "B. 'unfamiliar familiar' abroad for sociology",
              "C. no change to familiarity at all",
              "D. only unfamiliar settings ever studied"],
  "correct_answer": "A",
  "explanation": "Anthropology abroad makes the unfamiliar familiar; sociology at home makes the familiar unfamiliar.",
  "related": ["Familiar vs unfamiliar", "Ethnography — meaning"]},

 {"topic": "Ethnomethodology vs symbolic interactionism", "difficulty": "hard",
  "question": "Answering 'How are you?' with 'In regard to what — my health, my finances?' shows that:",
  "options": ["A. order only appears orderly, recreated moment to moment",
              "B. social order is completely fixed and permanent forever",
              "C. order comes solely from written law",
              "D. order needs no human effort at all"],
  "correct_answer": "A",
  "explanation": "The breach shows order is a fragile achievement, continually re-created by actors moment to moment.",
  "related": ["Ethnomethodology vs symbolic interactionism", "Breaching experiments"]},

 {"topic": "Covert observation — Asylums", "difficulty": "hard",
  "question": "Goffman posed as an assistant in the asylum in order to capture:",
  "options": ["A. the 'unofficial reality' from the patients' view",
              "B. the official view held by the doctors",
              "C. a purely statistical picture of the ward",
              "D. the architecture of the hospital building"],
  "correct_answer": "A",
  "explanation": "Covert immersion gave Goffman the 'unofficial reality' seen from the patients' standpoint.",
  "related": ["Covert observation — Asylums", "Total institution"]},

 {"topic": "Method combination", "difficulty": "hard",
  "question": "Kusenbach's overall argument about the go-along relative to observation and interviews is that it is:",
  "options": ["A. a hybrid whose strengths accumulate when combined",
              "B. clearly superior to every other method",
              "C. always worse than a sit-down interview",
              "D. useful only for studying private homes"],
  "correct_answer": "A",
  "explanation": "Kusenbach argues not for the go-along's superiority but for combining methods to gather many kinds of knowledge.",
  "related": ["Method combination", "The go-along"]},
]

if __name__ == "__main__":
    sys.exit(emit(KEY, META, Q))
