#!/usr/bin/env python3
"""SOCI1010 W2 · The Meaning of Everyday Life — regenerated bank."""
import os, sys, json
HERE = os.path.dirname(os.path.abspath(__file__))
sys.path.insert(0, os.path.join(HERE, "..", "tools"))
from qbank_lib import emit  # noqa

KEY = "soci1010_wk2_meaning_of_everyday_life.html"
BANK = json.load(open(os.path.join(HERE, "..", "..", "guide_quizzes.json"), encoding="utf-8"))
META = {k: BANK[KEY][k] for k in ("title", "subject", "unit", "content")}

Q = [
 {"topic": "Defining the everyday", "difficulty": "medium",
  "question": "In its wide meaning, everyday life includes:",
  "options": ["A. sacred and profane, private and public alike",
              "B. only the trivial, private and ordinary moments",
              "C. just festivals, holidays and sacred events",
              "D. exclusively the lives of ordinary people"],
  "correct_answer": "A",
  "explanation": "The wide definition spans profane and sacred, private and public, and people of all kinds.",
  "related": ["Defining the everyday", "The new everyday"]},

 {"topic": "The new everyday", "difficulty": "easy",
  "question": "Which is offered as an example of a 'new everyday' or 'new normal'?",
  "options": ["A. life under COVID", "B. a royal coronation",
              "C. an Olympic games", "D. a religious festival"],
  "correct_answer": "A",
  "explanation": "Life under COVID becoming the 'new normal' shows how the everyday itself can be reshaped.",
  "related": ["The new everyday", "Defining the everyday"]},

 {"topic": "Repetition", "difficulty": "hard",
  "question": "The claim that 'we become who we are through acts of repetition' is credited to:",
  "options": ["A. Durkheim", "B. Weber", "C. Simmel", "D. Bourdieu"],
  "correct_answer": "A",
  "explanation": "For Durkheim, repetition is not mere boredom but key to the gradual formation of social identity.",
  "related": ["Repetition", "Habitus"]},

 {"topic": "Techniques of the body", "difficulty": "hard",
  "question": "Mauss's 'techniques of the body' makes the point that:",
  "options": ["A. even bodily habits are learned and socially shaped",
              "B. bodily habits are purely biological instincts",
              "C. the body has no real place in sociology",
              "D. all humans move in exactly the same way"],
  "correct_answer": "A",
  "explanation": "Mauss showed that how we hold and use our bodies is assembled by and for social authority.",
  "related": ["Techniques of the body", "Habitus"]},

 {"topic": "Habitus", "difficulty": "hard",
  "question": "The term 'habitus' was coined by Mauss and developed as 'durable dispositions' by:",
  "options": ["A. Bourdieu", "B. Mauss", "C. Giddens", "D. Goffman"],
  "correct_answer": "A",
  "explanation": "Bourdieu developed habitus as 'durable dispositions' — acquired, class- and gender-shaped ways of being.",
  "related": ["Habitus", "Techniques of the body"]},

 {"topic": "Habitus", "difficulty": "medium",
  "question": "For Bourdieu, our habitus is most strongly shaped by:",
  "options": ["A. class and gender", "B. age and height",
              "C. genes and instinct", "D. climate and diet"],
  "correct_answer": "A",
  "explanation": "Habitus is strongly influenced by class and gender, reaching into eating, home decoration and taste.",
  "related": ["Habitus", "Repetition"]},

 {"topic": "Ontological security", "difficulty": "hard",
  "question": "Giddens's 'ontological security' refers to:",
  "options": ["A. trust in the world that stabilises identity",
              "B. financial security against future loss",
              "C. legal protection provided by the state",
              "D. certainty that science alone explains everything fully"],
  "correct_answer": "A",
  "explanation": "Ontological security is the confidence and trust we place in the people and things we share our world with.",
  "related": ["Ontological security", "Habitus"]},

 {"topic": "Democratic everyday", "difficulty": "medium",
  "question": "Everyday life is called a 'democratic' concept because:",
  "options": ["A. no one escapes it — even the Queen eats",
              "B. everyone gets an equal vote in it",
              "C. it is organised by elected officials",
              "D. only proper democracies actually have a real everyday life"],
  "correct_answer": "A",
  "explanation": "The modern everyday is democratic in the sense that all are anchored in it — 'even the Queen'.",
  "related": ["Democratic everyday", "Defining the everyday"]},

 {"topic": "Power and the everyday", "difficulty": "medium",
  "question": "The everyday 'feels natural but is actually political' is best shown by:",
  "options": ["A. the gendered spaces of home and lecture room",
              "B. the neutral, apolitical design of all rooms",
              "C. the purely private nature of family homes",
              "D. spaces having no effect on behaviour at all"],
  "correct_answer": "A",
  "explanation": "Spaces that feel neutral — the home, the lecture room — are in fact shaped by power and gender.",
  "related": ["Power and the everyday", "Politics of waiting"]},

 {"topic": "History of the everyday", "difficulty": "hard",
  "question": "According to Lefebvre, the everyday emerged as a 'social category' with:",
  "options": ["A. modernity — 19th-century capitalism and industry",
              "B. antiquity — the earliest human settlements",
              "C. the medieval feudal village economy",
              "D. the future — a fully automated society"],
  "correct_answer": "A",
  "explanation": "Lefebvre dates the everyday's visibility to modernity, as bodies massed in cities under industrial capitalism.",
  "related": ["History of the everyday", "Modernization vs modernity"]},

 {"topic": "Politics of waiting", "difficulty": "medium",
  "question": "Firms such as JCDecaux and Adshel, which build and own bus shelters, illustrate:",
  "options": ["A. the privatization of public space",
              "B. the total abolition of advertising",
              "C. a return to fully public ownership",
              "D. the decline of all outdoor advertising"],
  "correct_answer": "A",
  "explanation": "Firms owning the bus shelters turn public space into commercialised private/public space.",
  "related": ["Politics of waiting", "Power and the everyday"]},

 {"topic": "Politics of waiting", "difficulty": "medium",
  "question": "The Brandalism Project, which subverts bus-shelter advertising, raises the question of:",
  "options": ["A. vandalism versus social activism",
              "B. free speech versus censorship",
              "C. public art versus private art",
              "D. profit versus non-profit motives"],
  "correct_answer": "A",
  "explanation": "Altering corporate ads in public space poses the question of whether such acts are vandalism or activism.",
  "related": ["Politics of waiting", "Power and the everyday"]},

 {"topic": "Sociology of the queue", "difficulty": "hard",
  "question": "Sociologically, a queue is best described as:",
  "options": ["A. an embryonic social system whose violation is punished",
              "B. a purely random gathering of strangers",
              "C. a formal institution with written laws",
              "D. a space where no social rules apply at all"],
  "correct_answer": "A",
  "explanation": "A queue is a small but real pattern of social order; jumping it is a punishable violation.",
  "related": ["Sociology of the queue", "Goffman"]},

 {"topic": "Sociology of the queue", "difficulty": "hard",
  "question": "Goffman's point about the queue is that:",
  "options": ["A. the individual regulates conduct before others' eyes",
              "B. queues need police to stay orderly",
              "C. queue order comes from written rules",
              "D. individuals ignore everyone else while waiting"],
  "correct_answer": "A",
  "explanation": "For Goffman, members regulate themselves before others' eyes, which act as an informal guarantee of order.",
  "related": ["Sociology of the queue", "Saarbrücken experiment"]},

 {"topic": "Saarbrücken experiment", "difficulty": "hard",
  "question": "The Saarbrücken queue experiment found that a single feeder line:",
  "options": ["A. is a single feeder line, faster and fairer",
              "B. many separate lines always move faster",
              "C. queue design makes no measurable difference",
              "D. people always prefer many lines despite the delay"],
  "correct_answer": "A",
  "explanation": "A single serpentine queue feeding all desks was faster and felt fairer, so people were less grumpy.",
  "related": ["Saarbrücken experiment", "Sociology of the queue"]},

 {"topic": "Situating the everyday", "difficulty": "hard",
  "question": "Inglis's method for studying the everyday is to:",
  "options": ["A. denaturalize it, showing our 'normal' is peculiar",
              "B. accept our habits as simply natural",
              "C. measure it with large-scale surveys",
              "D. judge other cultures by our own standards"],
  "correct_answer": "A",
  "explanation": "Inglis argues we live 'like a fish in our own cultural water'; the task is to denaturalise the familiar.",
  "related": ["Situating the everyday", "Modernization vs modernity"]},

 {"topic": "Modernization vs modernity", "difficulty": "hard",
  "question": "'Modernization' refers to:",
  "options": ["A. the process by which traditional patterns weaken",
              "B. the society industrialization brought into being",
              "C. a return to pre-industrial ways of life",
              "D. the state's official list of modern laws"],
  "correct_answer": "A",
  "explanation": "Modernization is the process — the weakening of traditional patterns and worldviews.",
  "related": ["Modernization vs modernity", "History of the everyday"]},

 {"topic": "Modernization vs modernity", "difficulty": "hard",
  "question": "'Modernity' refers to:",
  "options": ["A. the society industrialization and urbanization created",
              "B. the process of traditional patterns weakening",
              "C. a purely economic theory of markets",
              "D. the earliest form of human settlement"],
  "correct_answer": "A",
  "explanation": "Modernity is the society that emerged with industrialization and urbanization; modernization is the process.",
  "related": ["Modernization vs modernity", "Modernity's signature"]},

 {"topic": "Modernity's signature", "difficulty": "hard",
  "question": "According to Hall et al, the cultural signature of the modern everyday is:",
  "options": ["A. rationality, routinization, market society, individualism",
              "B. tradition, kinship, religion and superstition",
              "C. feudalism, providence and divine right",
              "D. anarchy, chaos and total disorder"],
  "correct_answer": "A",
  "explanation": "As cities grew, everyday culture was reshaped by rationality, routinization, market society and individualism.",
  "related": ["Modernity's signature", "Weber"]},

 {"topic": "Pre-modern to modern", "difficulty": "medium",
  "question": "The shift from pre-modern to modern society replaced providence and religion with:",
  "options": ["A. progress, science and rationality",
              "B. providence, magic and religion",
              "C. kinship, tradition and ritual",
              "D. chaos, flux and uncertainty"],
  "correct_answer": "A",
  "explanation": "Modernity substitutes progress, science and rationality for the older worldview of providence and religion.",
  "related": ["Pre-modern to modern", "Modernity's signature"]},

 {"topic": "Weber", "difficulty": "medium",
  "question": "For Weber, what makes modern Western culture unique is:",
  "options": ["A. its exceptionally high level of rationality",
              "B. its unusually deep religious devotion",
              "C. its return to magical explanation",
              "D. its rejection of all bureaucratic rules"],
  "correct_answer": "A",
  "explanation": "Weber held that no other society has been so organised around rational procedures.",
  "related": ["Weber", "Zweckrational"]},

 {"topic": "Zweckrational", "difficulty": "hard",
  "question": "Zweckrational action is oriented to:",
  "options": ["A. the most efficient means to a given end",
              "B. an ultimate moral or spiritual value",
              "C. blind obedience to ancient tradition",
              "D. pure spontaneous emotion felt in the very moment"],
  "correct_answer": "A",
  "explanation": "Zweckrational (instrumental) action calculates the most efficient means to a goal.",
  "related": ["Zweckrational", "Wertrational"]},

 {"topic": "Wertrational", "difficulty": "hard",
  "question": "Wertrational action is oriented to:",
  "options": ["A. an ultimate value, moral or spiritual",
              "B. the most efficient means to an end",
              "C. habitual action based on tradition",
              "D. emotional action driven by feeling"],
  "correct_answer": "A",
  "explanation": "Wertrational (value-rational) action works toward an ultimate value, like the devout believer.",
  "related": ["Wertrational", "Zweckrational"]},

 {"topic": "Protestant Ethic", "difficulty": "medium",
  "question": "In 'The Protestant Ethic and the Spirit of Capitalism', Weber located capitalism's origin in:",
  "options": ["A. the protestant ethic and religious ideas",
              "B. purely economic and material forces",
              "C. the invention of new technology",
              "D. the decline of all religious belief"],
  "correct_answer": "A",
  "explanation": "Weber traced capitalism to religious ideas — the protestant valuing of hard work as a calling.",
  "related": ["Protestant Ethic", "Weber"]},

 {"topic": "Disenchantment", "difficulty": "hard",
  "question": "Weber's 'disenchantment of the world' means:",
  "options": ["A. the retreat of magic before science",
              "B. a return of religion to public life",
              "C. growing enchantment with the world",
              "D. the collapse of all rational thought"],
  "correct_answer": "A",
  "explanation": "Disenchantment is the withdrawal of magical and miraculous belief as science and rational calculation spread.",
  "related": ["Disenchantment", "Weber"]},

 {"topic": "Legal-rational authority", "difficulty": "hard",
  "question": "Weber's 'legal-rational authority' means people are governed by:",
  "options": ["A. the systematic application of rules and procedures",
              "B. the personal charisma of a great leader",
              "C. the weight of ancient, sacred tradition",
              "D. the arbitrary whim of a single ruler"],
  "correct_answer": "A",
  "explanation": "Legal-rational authority replaces tradition and religion; power flows through impersonal rules and procedures.",
  "related": ["Legal-rational authority", "Bureaucracy"]},

 {"topic": "Bureaucracy", "difficulty": "medium",
  "question": "The word 'bureaucracy' literally means:",
  "options": ["A. control through the use of regulations",
              "B. rule by a hereditary noble class",
              "C. government without any written rules",
              "D. direct rule by the whole people"],
  "correct_answer": "A",
  "explanation": "Bureaucracy literally means 'control through regulations' — the characteristic form domination takes in modernity.",
  "related": ["Bureaucracy", "Legal-rational authority"]},

 {"topic": "Obeying the role", "difficulty": "hard",
  "question": "Weber's key insight about paying a tax inspector is that:",
  "options": ["A. we obey the role and rules, not the person",
              "B. we obey the person alone, not their official role",
              "C. we obey only leaders we personally like",
              "D. we obey no authority in modern society"],
  "correct_answer": "A",
  "explanation": "In a bureaucratic culture it is the role — tax inspector, teacher — and its rules that we obey, not the individual.",
  "related": ["Obeying the role", "Bureaucracy"]},

 {"topic": "Professionalization", "difficulty": "medium",
  "question": "The horror provoked by an unqualified 'fake doctor' reflects:",
  "options": ["A. the deep professionalization of modern work",
              "B. a healthy distrust of all experts",
              "C. the decline of professional standards",
              "D. the irrelevance of formal qualifications"],
  "correct_answer": "A",
  "explanation": "Only credentialed experts are deemed competent; outrage at a fake doctor shows how professionalized work has become.",
  "related": ["Professionalization", "Legal-rational authority"]},

 {"topic": "Iron cage", "difficulty": "hard",
  "question": "Weber's 'iron cage' describes modernity as:",
  "options": ["A. a bloodless, over-rationalized world without meaning",
              "B. a joyful, enchanted world full of magic",
              "C. a lawless world with no rules at all",
              "D. a traditional world governed by religion"],
  "correct_answer": "A",
  "explanation": "The iron cage is Weber's pessimistic image of a hyper-rational, bureaucratized world stripped of spiritual meaning.",
  "related": ["Iron cage", "Disenchantment"]},

 {"topic": "Feeling rules", "difficulty": "hard",
  "question": "Hochschild's 'feeling rules' refer to:",
  "options": ["A. workplace prescriptions for which emotions to display",
              "B. laws banning emotion in the workplace",
              "C. private feelings that no one can control",
              "D. rules about how fast staff must work"],
  "correct_answer": "A",
  "explanation": "Feeling rules are the prescribed, predictable emotions demanded of workers — for example, cabin crew.",
  "related": ["Feeling rules", "Role ambivalence"]},

 {"topic": "Role ambivalence", "difficulty": "hard",
  "question": "The doctor's 'role ambivalence' (Merton) is the tension between:",
  "options": ["A. being a detached scientist and a caring carer",
              "B. earning a high wage yet working long hours",
              "C. holding two different jobs at the same time",
              "D. liking and disliking the same colleague"],
  "correct_answer": "A",
  "explanation": "Role ambivalence is the tension between the detached, dispassionate diagnostician and the caring carer.",
  "related": ["Role ambivalence", "Feeling rules"]},

 {"topic": "Money mentality", "difficulty": "hard",
  "question": "For Simmel, money reshapes social relations because it is:",
  "options": ["A. impersonal and universalizing, breeding calculation",
              "B. deeply personal and emotionally warm",
              "C. rooted in local tradition and custom",
              "D. irrelevant to how we judge people"],
  "correct_answer": "A",
  "explanation": "Money is impersonal and universalizing; it makes us judge things and people by quantity, not quality.",
  "related": ["Money mentality", "Blasé attitude"]},

 {"topic": "Rationalizing sport", "difficulty": "medium",
  "question": "Eichberg's account of modern sport shows that:",
  "options": ["A. loose pre-modern games became standardized pitches",
              "B. modern sport abolished all fixed rules",
              "C. sport has never really changed at all",
              "D. games moved from pitches back to open land"],
  "correct_answer": "A",
  "explanation": "Pre-modern ball-games played across open land became demarcated, standardized, rule-governed pitches.",
  "related": ["Rationalizing sport", "Rationalizing space"]},

 {"topic": "Rationalizing space", "difficulty": "hard",
  "question": "Augé argues that motorway travel makes places:",
  "options": ["A. mere names and signs flashing by",
              "B. rich, detailed places worth stopping at",
              "C. the true heart of every region",
              "D. sacred sites of deep local meaning"],
  "correct_answer": "A",
  "explanation": "Motorways bypass the towns they name for the sake of speed, so places become abstract signs flashing past.",
  "related": ["Rationalizing space", "Rationalizing sport"]},

 {"topic": "Marx on flux", "difficulty": "hard",
  "question": "'All that is solid melts into air' is Marx's image for:",
  "options": ["A. modernity's constant flux destroying the solid",
              "B. the permanence of traditional society",
              "C. the slow, stable growth of markets",
              "D. the return of timeless ancient customs"],
  "correct_answer": "A",
  "explanation": "Marx captured modernity's ceaseless upheaval — capitalist society lets nothing remain stable for long.",
  "related": ["Marx on flux", "Modernity's signature"]},

 {"topic": "Blasé attitude", "difficulty": "hard",
  "question": "Simmel's 'blasé attitude' is:",
  "options": ["A. a protective detachment screening out city stimuli",
              "B. an eager fascination with every stranger",
              "C. a warm intimacy with all one's neighbours",
              "D. a violent hostility toward the crowd"],
  "correct_answer": "A",
  "explanation": "The blasé attitude is the 'seen it all' detachment that lets the city dweller cope with constant stimulation.",
  "related": ["Blasé attitude", "Metropolis paradox"]},

 {"topic": "Metropolis paradox", "difficulty": "medium",
  "question": "Simmel's paradox of the metropolis is that:",
  "options": ["A. the bigger the crowd, the lonelier one feels",
              "B. the bigger the crowd, the safer one feels",
              "C. small towns are lonelier than big cities",
              "D. crowds always make people feel connected"],
  "correct_answer": "A",
  "explanation": "Confronted with a vast array of strangers, the individual withdraws — the crowd can deepen loneliness.",
  "related": ["Metropolis paradox", "Blasé attitude"]},

 {"topic": "Revolt into style", "difficulty": "hard",
  "question": "Style is called 'individuality off the peg' because:",
  "options": ["A. a subculture lets you look distinctive yet belong",
              "B. style is always invented alone from nothing",
              "C. fashion has no real link to group identity",
              "D. only the rich can ever have a style"],
  "correct_answer": "A",
  "explanation": "Subcultures and lifestyles let you appear distinctive without inventing yourself from scratch — 'individuality off the peg'.",
  "related": ["Revolt into style", "Uniqueness and sameness"]},

 {"topic": "Uniqueness and sameness", "difficulty": "medium",
  "question": "The horror of two women arriving in the same designer dress shows that:",
  "options": ["A. uniqueness is the flip side of sameness",
              "B. we are all completely unique individuals",
              "C. taste makes us identical to everyone",
              "D. style has nothing to do with others"],
  "correct_answer": "A",
  "explanation": "Taste and style make us different from some yet uncomfortably like others — uniqueness and sameness are linked.",
  "related": ["Uniqueness and sameness", "Revolt into style"]},

 {"topic": "Invented traditions", "difficulty": "hard",
  "question": "An 'invented tradition' (Hobsbawm and Ranger) is:",
  "options": ["A. a recent practice presented as if ancient",
              "B. a genuinely ancient, unbroken custom",
              "C. a tradition that everyone has forgotten",
              "D. a law formally passed by the parliament"],
  "correct_answer": "A",
  "explanation": "Invented traditions are recent inventions dressed up as timeless, offered to the public as age-old.",
  "related": ["Invented traditions", "Tourism paradox"]},

 {"topic": "Invented traditions", "difficulty": "medium",
  "question": "Which is given as an example of an invented tradition?",
  "options": ["A. the 'traditional' Victorian family Christmas",
              "B. the ancient Greek Olympic torch",
              "C. a medieval harvest festival",
              "D. a prehistoric burial rite"],
  "correct_answer": "A",
  "explanation": "The 'traditional family Christmas' of trees, cards and Santa is largely a Victorian invention.",
  "related": ["Invented traditions", "Tourism paradox"]},

 {"topic": "Tourism paradox", "difficulty": "hard",
  "question": "The paradox of mass tourism is that:",
  "options": ["A. tourists destroy the authentic culture they seek",
              "B. tourism perfectly preserves local culture",
              "C. tourists never affect the places they visit",
              "D. authentic culture cannot be found anywhere"],
  "correct_answer": "A",
  "explanation": "Seeking 'unspoiled' authenticity, tourists remake places around the tourist dollar, commodifying what they came to find.",
  "related": ["Tourism paradox", "The post-tourist"]},

 {"topic": "The post-tourist", "difficulty": "hard",
  "question": "The 'post-tourist':",
  "options": ["A. knowingly and ironically embraces the fake experience",
              "B. desperately searches for untouched authenticity",
              "C. refuses to travel anywhere at all",
              "D. believes every tourist site is completely real"],
  "correct_answer": "A",
  "explanation": "The post-tourist accepts that no uncommodified 'reality' remains and enjoys the ironies of the packaged experience.",
  "related": ["The post-tourist", "The age of irony"]},

 {"topic": "The age of irony", "difficulty": "hard",
  "question": "Eco's line 'As Barbara Cartland would put it, I love you madly' illustrates:",
  "options": ["A. sincerity smuggled back through self-conscious irony",
              "B. the total death of all sincerity",
              "C. a return to plain, earnest speech",
              "D. the rejection of every cultural cliché"],
  "correct_answer": "A",
  "explanation": "When plain words sound like clichés, one recovers sincerity by ironically flagging the cliché.",
  "related": ["The age of irony", "Post vs late modern"]},

 {"topic": "Post vs late modern", "difficulty": "medium",
  "question": "Post-modernity (Lyotard) and late modernity (Giddens) both describe a culture of:",
  "options": ["A. irony, knowingness and self-consciousness",
              "B. sincerity, faith and certainty",
              "C. tradition, ritual and religion",
              "D. chaos, violence and disorder"],
  "correct_answer": "A",
  "explanation": "Whether called post-modern or late modern, the culture is marked by irony, knowingness and self-consciousness.",
  "related": ["Post vs late modern", "The age of irony"]},
]

if __name__ == "__main__":
    sys.exit(emit(KEY, META, Q))
