#!/usr/bin/env python3
"""MHHS2401 W5 · Upper Limb Blood Supply & Lymphatics — regenerated bank (length-matched, no bracket tells, no daredevil)."""
import os, sys, json
HERE = os.path.dirname(os.path.abspath(__file__))
sys.path.insert(0, os.path.join(HERE, "..", "tools"))
from qbank_lib import emit  # noqa

KEY = "upper_limb_blood_supply_mhhs2401_wk5.html"
BANK = json.load(open(os.path.join(HERE, "..", "..", "guide_quizzes.json"), encoding="utf-8"))
META = {k: BANK[KEY][k] for k in ("title", "subject", "unit", "content")}

Q = [
 # ── easy ──────────────────────────────────────────────────────────────
 {"topic": "Arterial highway", "difficulty": "easy",
  "question": "The brachial artery is the main blood supply to which region?",
  "options": ["A. the arm", "B. the neck",
              "C. the hand", "D. the thorax"],
  "correct_answer": "A",
  "explanation": "The brachial artery is the main supply to the arm; it ends in the cubital fossa by dividing into the radial and ulnar arteries.",
  "related": ["Arterial highway", "Brachial artery"]},

 {"topic": "Axilla", "difficulty": "easy",
  "question": "The axilla is best described as which kind of space?",
  "options": ["A. a pyramidal passageway", "B. a flat sheet",
              "C. a bony canal", "D. a fluid-filled sac"],
  "correct_answer": "A",
  "explanation": "The axilla is a pyramidal space between arm and thorax through which vessels, nerves and lymphatics reach the upper limb.",
  "related": ["Axilla", "Arterial highway"]},

 {"topic": "Forearm arteries", "difficulty": "easy",
  "question": "The classic wrist pulse is taken from which artery?",
  "options": ["A. the radial artery", "B. the ulnar artery",
              "C. the brachial artery", "D. the axillary artery"],
  "correct_answer": "A",
  "explanation": "The radial artery is palpated laterally at the wrist and is the classic pulse point and arterial sampling site.",
  "related": ["Forearm arteries", "Palmar arches"]},

 {"topic": "Superficial veins", "difficulty": "easy",
  "question": "Which superficial vein is the standard site for taking blood at the elbow?",
  "options": ["A. the median cubital vein", "B. the cephalic vein",
              "C. the basilic vein", "D. the brachial vein"],
  "correct_answer": "A",
  "explanation": "The median cubital vein crosses the cubital fossa and is large and fixed, making it the standard venepuncture site.",
  "related": ["Superficial veins", "Venous drainage"]},

 {"topic": "Lymphatic drainage", "difficulty": "easy",
  "question": "Lymph from the upper limb mainly converges on which group of nodes?",
  "options": ["A. the axillary nodes", "B. the cervical nodes",
              "C. the inguinal nodes", "D. the popliteal nodes"],
  "correct_answer": "A",
  "explanation": "Both superficial and deep lymphatics of the upper limb converge on the axillary lymph nodes.",
  "related": ["Lymphatic drainage", "Axillary nodes"]},

 # ── medium ────────────────────────────────────────────────────────────
 {"topic": "Name changes", "difficulty": "medium",
  "question": "The subclavian artery becomes the axillary artery at the lateral margin of which structure?",
  "options": ["A. the first rib", "B. the teres major",
              "C. the clavicle", "D. the coracoid process"],
  "correct_answer": "A",
  "explanation": "The subclavian becomes the axillary artery at the lateral margin of rib 1, then the brachial at the inferior border of teres major.",
  "related": ["Name changes", "Arterial highway"]},

 {"topic": "Name changes", "difficulty": "medium",
  "question": "The axillary artery becomes the brachial artery at the inferior border of which muscle?",
  "options": ["A. teres major", "B. pectoralis minor",
              "C. subscapularis", "D. latissimus dorsi"],
  "correct_answer": "A",
  "explanation": "The axillary artery becomes the brachial artery at the inferior margin of teres major.",
  "related": ["Name changes", "Brachial artery"]},

 {"topic": "Axillary artery parts", "difficulty": "medium",
  "question": "The axillary artery is divided into three parts by which muscle?",
  "options": ["A. pectoralis minor", "B. pectoralis major",
              "C. teres major", "D. serratus anterior"],
  "correct_answer": "A",
  "explanation": "Pectoralis minor divides the axillary artery into three parts, which give one, two and three branches respectively.",
  "related": ["Axillary artery parts", "Arterial highway"]},

 {"topic": "Brachial artery", "difficulty": "medium",
  "question": "The brachial artery divides into the radial and ulnar arteries in the:",
  "options": ["A. cubital fossa", "B. carpal tunnel",
              "C. axilla", "D. anatomical snuffbox"],
  "correct_answer": "A",
  "explanation": "The brachial artery divides opposite the neck of the radius in the cubital fossa into the radial and ulnar arteries.",
  "related": ["Brachial artery", "Cubital fossa"]},

 {"topic": "Cubital fossa", "difficulty": "medium",
  "question": "Which muscle forms the lateral boundary of the cubital fossa?",
  "options": ["A. brachioradialis", "B. pronator teres",
              "C. biceps brachii", "D. brachialis"],
  "correct_answer": "A",
  "explanation": "Brachioradialis forms the lateral boundary and pronator teres the medial boundary of the triangular cubital fossa.",
  "related": ["Cubital fossa", "Brachial artery"]},

 {"topic": "Forearm arteries", "difficulty": "medium",
  "question": "In the forearm, the radial artery runs on the lateral side and the ulnar artery runs:",
  "options": ["A. medially", "B. posteriorly",
              "C. deep in the membrane", "D. across the wrist"],
  "correct_answer": "A",
  "explanation": "The radial artery runs laterally and the ulnar artery runs medially down the forearm to reach the hand.",
  "related": ["Forearm arteries", "Palmar arches"]},

 {"topic": "Palmar arches", "difficulty": "medium",
  "question": "The superficial palmar arch is formed mainly by which artery?",
  "options": ["A. the ulnar artery", "B. the radial artery",
              "C. the brachial artery", "D. the interosseous artery"],
  "correct_answer": "A",
  "explanation": "The superficial palmar arch comes mainly from the ulnar artery and lies more distally; the deep arch comes mainly from the radial artery.",
  "related": ["Palmar arches", "Forearm arteries"]},

 {"topic": "Palmar arches", "difficulty": "medium",
  "question": "The deep palmar arch is formed mainly by which artery?",
  "options": ["A. the radial artery", "B. the ulnar artery",
              "C. the axillary artery", "D. the profunda brachii"],
  "correct_answer": "A",
  "explanation": "The deep palmar arch comes mainly from the radial artery and lies more proximally than the ulnar-derived superficial arch.",
  "related": ["Palmar arches", "Forearm arteries"]},

 {"topic": "Venae comitantes", "difficulty": "medium",
  "question": "Deep veins that run in pairs alongside an artery are called:",
  "options": ["A. venae comitantes", "B. superficial veins",
              "C. perforating veins", "D. cutaneous veins"],
  "correct_answer": "A",
  "explanation": "Venae comitantes are paired deep veins wrapped around an artery; the arterial pulse squeezes them to aid venous return.",
  "related": ["Venae comitantes", "Venous drainage"]},

 {"topic": "Superficial veins", "difficulty": "medium",
  "question": "Which superficial vein runs on the lateral (radial) side of the upper limb?",
  "options": ["A. the cephalic vein", "B. the basilic vein",
              "C. the median cubital vein", "D. the brachial vein"],
  "correct_answer": "A",
  "explanation": "The cephalic vein runs laterally, the basilic vein medially, and the median cubital vein connects them at the elbow.",
  "related": ["Superficial veins", "Venous drainage"]},

 {"topic": "Axillary nodes", "difficulty": "medium",
  "question": "Which group of axillary lymph nodes chiefly drains the breast?",
  "options": ["A. the pectoral group", "B. the subscapular group",
              "C. the humeral group", "D. the apical group"],
  "correct_answer": "A",
  "explanation": "The pectoral (anterior) group drains the anterior thoracic wall and breast, making it the first site of breast cancer spread.",
  "related": ["Axillary nodes", "Lymphatic drainage"]},

 {"topic": "Axilla walls", "difficulty": "medium",
  "question": "The anterior wall of the axilla is formed by which muscles?",
  "options": ["A. pectoralis major and minor", "B. teres major and latissimus",
              "C. subscapularis and scapula", "D. serratus anterior alone"],
  "correct_answer": "A",
  "explanation": "Pectoralis major and minor form the anterior wall of the axilla; the posterior wall includes the scapula and subscapularis.",
  "related": ["Axilla walls", "Axilla"]},

 # ── hard ──────────────────────────────────────────────────────────────
 {"topic": "Axillary branches", "difficulty": "hard",
  "question": "The first part of the axillary artery gives which single branch?",
  "options": ["A. the superior thoracic artery", "B. the lateral thoracic artery",
              "C. the subscapular artery", "D. the thoraco-acromial artery"],
  "correct_answer": "A",
  "explanation": "The first part gives the superior thoracic artery; the second part gives two branches and the third part gives three.",
  "related": ["Axillary branches", "Axillary artery parts"]},

 {"topic": "Axillary branches", "difficulty": "hard",
  "question": "The third part of the axillary artery gives the subscapular artery and the:",
  "options": ["A. circumflex humeral arteries", "B. superior thoracic artery",
              "C. thoraco-acromial artery", "D. lateral thoracic artery"],
  "correct_answer": "A",
  "explanation": "The third part gives the anterior and posterior circumflex humeral arteries plus the subscapular artery.",
  "related": ["Axillary branches", "Scapular anastomosis"]},

 {"topic": "Circumflex humeral", "difficulty": "hard",
  "question": "The posterior circumflex humeral artery winds around which part of the humerus?",
  "options": ["A. the surgical neck", "B. the anatomical neck",
              "C. the deltoid tuberosity", "D. the medial epicondyle"],
  "correct_answer": "A",
  "explanation": "The posterior circumflex humeral artery winds around the surgical neck with the axillary nerve, so both are at risk in fractures there.",
  "related": ["Circumflex humeral", "Axillary branches"]},

 {"topic": "Brachial branches", "difficulty": "hard",
  "question": "The main deep branch of the brachial artery in the arm is the:",
  "options": ["A. profunda brachii", "B. ulnar collateral",
              "C. radial recurrent", "D. common interosseous"],
  "correct_answer": "A",
  "explanation": "The profunda brachii (deep artery of the arm) is the main branch, along with the ulnar collateral arteries feeding the elbow.",
  "related": ["Brachial branches", "Brachial artery"]},

 {"topic": "Anastomoses", "difficulty": "hard",
  "question": "Why do arterial anastomoses form around the shoulder, elbow and hand?",
  "options": ["A. to give collateral bypass routes", "B. to slow the blood flow",
              "C. to raise the local pressure", "D. to store extra blood"],
  "correct_answer": "A",
  "explanation": "Anastomoses provide collateral routes so blood can bypass a joint even when the main vessel is kinked by movement or blocked.",
  "related": ["Anastomoses", "Arterial highway"]},

 {"topic": "Allen's test", "difficulty": "hard",
  "question": "Allen's test before radial artery cannulation checks that the hand can be supplied by the:",
  "options": ["A. ulnar artery", "B. brachial artery",
              "C. interosseous artery", "D. profunda brachii"],
  "correct_answer": "A",
  "explanation": "Allen's test confirms the ulnar artery can supply the hand through the palmar arches, so sampling the radial artery is safe.",
  "related": ["Allen's test", "Palmar arches"]},

 {"topic": "Interosseous arteries", "difficulty": "hard",
  "question": "The anterior and posterior interosseous arteries arise from which vessel?",
  "options": ["A. the common interosseous artery", "B. the profunda brachii",
              "C. the deep palmar arch", "D. the superior ulnar collateral"],
  "correct_answer": "A",
  "explanation": "The common interosseous artery, a branch of the ulnar, gives the anterior and posterior interosseous arteries along the membrane.",
  "related": ["Interosseous arteries", "Forearm arteries"]},

 {"topic": "Node sequence", "difficulty": "hard",
  "question": "The pectoral, subscapular and humeral node groups drain next into which group?",
  "options": ["A. the central group", "B. the apical group",
              "C. the cervical group", "D. the inguinal group"],
  "correct_answer": "A",
  "explanation": "The three peripheral groups drain into the central nodes, which then drain into the apical nodes at the axilla's apex.",
  "related": ["Node sequence", "Axillary nodes"]},

 {"topic": "Lymph exit", "difficulty": "hard",
  "question": "The apical axillary nodes drain onward via which structure?",
  "options": ["A. the subclavian trunk", "B. the cephalic vein",
              "C. the thoracic wall", "D. the cisterna chyli"],
  "correct_answer": "A",
  "explanation": "The apical nodes empty via the subclavian lymphatic trunk into the right lymphatic duct or the thoracic duct.",
  "related": ["Lymph exit", "Axillary nodes"]},

 {"topic": "Median cubital vein", "difficulty": "hard",
  "question": "During venepuncture, which structures lie just deep to the median cubital vein?",
  "options": ["A. brachial artery and median nerve", "B. radial artery and radial nerve",
              "C. ulnar artery and ulnar nerve", "D. cephalic vein and musculocutaneous nerve"],
  "correct_answer": "A",
  "explanation": "The brachial artery and median nerve lie just deep to the median cubital vein, behind the bicipital aponeurosis.",
  "related": ["Median cubital vein", "Superficial veins"]},

 {"topic": "Axilla contents", "difficulty": "hard",
  "question": "Besides the axillary vessels and lymph nodes, the axilla transmits which neural structure?",
  "options": ["A. the brachial plexus cords", "B. the vagus nerve",
              "C. the phrenic nerve", "D. the sympathetic chain"],
  "correct_answer": "A",
  "explanation": "The axilla transmits the cords of the brachial plexus alongside the axillary artery and vein and the axillary lymph nodes.",
  "related": ["Axilla contents", "Axilla"]},
]

if __name__ == "__main__":
    sys.exit(emit(KEY, META, Q))
